### ISSUE TITLE
CSS prop as object in a composition context - Color conflict with Styled-System

### ISSUE THREAD

**Issue by samuelcastro** [emotion-js/emotion#1879] opened 2020-05-26 16:57 UTC
**The problem**

With styled-components I'm able to do something like this:

```typescript
const BoxWrapper = styled.div<BoxProps>(
  base,
  themed('Box'),
  (props: BoxProps) =>
    props?.flexBox &&
    css(
      { display: 'flex' },
      flexWrap,
      flexDirection,
      alignItems,
      justifyContent,
      themed('FlexBox')
    )
);
```

Which does not work with emotion, I'm getting this error:

```
 Argument of type 'styleFn' is not assignable to parameter of type 'Interpolation<undefined>'.
      Type 'styleFn' is not assignable to type 'ObjectInterpolation<undefined>'.
        Index signature is missing in type 'styleFn'.ts(2769)
```

**Proposed solution**

The proposed solution would be make the `css` prop work with object composition similarly how styled-components works.

[CodeSandbox](https://codesandbox.io/s/emotion-typescript-example-4zgfm?file=/src/Box.tsx)

Thanks.

**Comment by Andarist** [comment] 2020-05-26 19:49
Could you share a repro case? It's hard to tell where the problem is from that snippet of code alone.

**Comment by samuelcastro** [comment] 2020-05-26 20:24
Hi @Andarist this is a codesandbox reproducing the error: https://codesandbox.io/s/emotion-typescript-example-4zgfm?file=/src/Box.tsx

Thanks!

**Comment by Andarist** [comment] 2020-05-26 22:05
You just shouldn't use `css` there, you can return an array of functions. Take a look at the adjusted example:
https://codesandbox.io/s/emotion-typescript-example-bugij?file=/src/Box.tsx

**Comment by samuelcastro** [comment] 2020-05-27 01:08
Oh I see, thank you, it was my misunderstanding, this fixed it.

**Comment by samuelcastro** [comment] 2020-05-27 17:00
Ok, so the array in fact fixed the issue, however now I'm getting this conflict error with the native color prop: `Types of property 'color' are incompatible.`.

See codesandbox: https://codesandbox.io/s/emotion-typescript-example-4zgfm?file=/src/Box.tsx

**Comment by Andarist** [comment] 2020-05-28 07:21
Well, this seems like one of the quirks with the styled API. To solve it you could extend the global `React.HTMLAttributes` with a color that would match your criteria. However, it would affect *all* of the color props, not only ones passed to styled components.

Could you prepare a repro case of `styled-components` working with this? I would be interested in seeing how they types differ to allow that as I would expect they would have suffered from the very same issue.

Keep also in mind that you probably should configure `shouldForwardProp` on your styled component appropriately when doing this as right now non-valid colors will be forwarded to the DOM.

**Comment by samuelcastro** [comment] 2020-05-28 16:53
This is how I managed to fix it with styled-components: https://codesandbox.io/s/emotion-typescript-example-bcsjp?file=/src/Box.tsx

Wondering whether there is a similar approach for Emotion, although this looks like more as a workaround than a proper fix.

More context:
- https://github.com/styled-system/styled-system/issues/464
- https://spectrum.chat/styled-components/general/typescript-styled-system-styled-components~5593dbf2-7588-4c6d-9e76-b4eadd77ec90

Thank you!

**Comment by samuelcastro** [comment] 2020-05-28 17:25
> Keep also in mind that you probably should configure shouldForwardProp on your styled component appropriately when doing this as right now non-valid colors will be forwarded to the DOM.

Could you elaborate more on that, I'm not sure what you mean, this is a [codesandbox](https://codesandbox.io/s/emotion-typescript-example-tpob5?file=/src/index.tsx) I'm using the `shouldForwardProp` however even though I'm using a non-valid color prop value the prop is being forward anyway.

**Comment by Andarist** [comment] 2020-05-28 22:18
> This is how I managed to fix it with styled-components: https://codesandbox.io/s/emotion-typescript-example-bcsjp?file=/src/Box.tsx

I get "Type instantiation is excessively deep and possibly infinite" error on that codesandbox 😅 

> Could you elaborate more on that, I'm not sure what you mean, this is a codesandbox I'm using the shouldForwardProp however even though I'm using a non-valid color prop value the prop is being forward anyway.

As far as I can tell the color is not being forwarded to the DOM element here as this is what you get in DOM:
<img width="309" alt="Screenshot 2020-05-28 at 23 43 44" src="https://user-images.githubusercontent.com/9800850/83197020-1e33a700-a13d-11ea-8cac-bb4bfe92fb0e.png">
but using [the previously given codesandbox](https://codesandbox.io/s/emotion-typescript-example-4zgfm?file=/src/Box.tsx) when I pass `color` prop to the `<Box/>` there I get this:
<img width="291" alt="Screenshot 2020-05-29 at 00 17 44" src="https://user-images.githubusercontent.com/9800850/83199605-db280280-a141-11ea-8cb8-5ec379da8f2a.png">

**Comment by Andarist** [comment] 2020-06-11 22:16
Closing this as the discussion seems to has reached its end. If you have any further comments/questions - please just comment back and I will make sure to get back to you.

**Closed by Andarist** 2020-06-11 22:16 UTC
Labels: question
