### ISSUE TITLE
Styles order when use as prop

### ISSUE THREAD

**Issue by javialon26** [emotion-js/emotion#1885] opened 2020-06-03 17:34 UTC
**Current behavior:**

When I use the as prop in a styled component, the order of styles is not clear. The styles of the original component have more specificity. I don't know if this behavior is intentional or not.

**To reproduce:**
https://codesandbox.io/s/emotion-issue-template-r6zuq?file=/src/index.js

1. Create a styled component with styles
2. Use the component and pass the as prop with another styled component with styles
3. The original component has more specificity over the as component

**Expected behavior:**

The component passed in the as prop should override the styles

**Environment information:**

- `react` version: 16.13.1
- `emotion` version: 10.0.28
- `emotion styled` version: 10.0.27

**Comment by javialon26** [comment] 2020-06-03 18:07
In styled-components the as component override the styles, check it here:
https://codesandbox.io/s/styled-components-base-et1gl?file=/index.js

**Comment by javialon26** [comment] 2020-06-05 14:47
@Andarist any news on this?

**Comment by Andarist** [comment] 2020-06-06 20:08
I would classify this for now as "working as intended". This behavior here is like that since we've introduced support for the `as` prop which was 1.5 years ago and this is the first issue about the order of styles being problematic with it.

I certainly understand where are you coming from, but changing this would be a breaking change which I don't want to introduce now and I'm not sure if your version would be much better. The main use case for `as` prop is to change the underlying HTML tag without having to create new styled components upfront just to do that. It's not really meant as a mechanism for style composition.

I'm going to close this but feel free to answer back - I will make sure to get back to you.

**Closed by Andarist** 2020-06-06 20:08 UTC
Labels: question
