### ISSUE TITLE
Snapshot tests showing components as '<ForwardRef />' instead of component name

### ISSUE THREAD

**Issue by hammadj** [emotion-js/emotion#1204] opened 2019-02-01 00:56 UTC
- `emotion` version: 
```
"@emotion/core": "^10.0.6",
"@emotion/native": "^10.0.6",
```
- `react` version:
```
"react": "16.6.3",
"react-native": "0.57.8",
```

**Relevant code:**

```tsx
const StyledText = styled.Text<StyledTextProps>`
  ${space}
  ${textType}
  ${textAlign}
  ${textColor}
`;

StyledText.defaultProps = {
  type: 'default',
};

StyledText.displayName = 'StyledText';
```

**What you did:**
Used the `StyledText` component I just created in another component and did a snapshot test.

**What happened:**
 I expected the name in the snapshots to show up as `<StyledText ...>` but it showed up as  `<ForwardRef ...>` instead.

**Suggested solution:**
The displayName should be honoured when created styled components like this, or at least there should be an API to provide that name to emotion.

**Comment by kylegach** [comment] 2019-02-01 16:04
Are you sure that babel-plugin-emotion is running in your test environment?

If you're unable to do that, you can also [manually add a `label`](https://emotion.sh/docs/labels) to your components.

**Comment by Iuriy-Budnikov** [comment] 2019-02-23 19:53
I have the same issue

**Comment by drainpip** [comment] 2019-02-25 17:52
Just to mirror those here, I am having the same problem, but not in React Native.

We're running 10.0.7 of `@emotion/core`, `jest-emotion`, and `babel-plugin-emotion`. This isn't a full blocker for us, however it does make testing for DOM elements and copy difficult.

**Comment by jooj123** [comment] 2019-03-08 00:08
Yeah we have the same issue with enzyme & shallow render.

Have some jsx: 

```
<h1 css={styles.cityHeading}>Sydney</h1>
```

Cant target with:

```
expect(wrapper.find('h1')).to.have.text(
        'Sydney'
      );
```

Because `@emotion/babel-preset-css-prop` converts to:

```
<ForwardRef(render) css={{...}} __EMOTION_TYPE_PLEASE_DO_NOT_USE__="h1" __EMOTION_LABEL_PLEASE_DO_NOT_USE__="EmotionTest">
    Sydney
  </ForwardRef(render)>
```

Converting to mount works around the issue - but its not ideal for all our tests to be mount tests

**Comment by ar7casper** [comment] 2019-03-10 09:00
Any updates on that? 
Having similar issues, across the board (Storybook, Jest, etc.)
Works fine with a pure function, trying out `styled` resulted in these problems.

**Comment by jooj123** [comment] 2019-03-13 09:24
Got around this by not applying `@emotion/babel-preset-css-prop` specifically for test babel config

But yeah maybe not the best way - ideally should work out of the box

**Comment by frankishh** [comment] 2019-03-24 10:04
> Yeah we have the same issue with enzyme (shallow render) + mocha (so its not just jest related)
> 
> Have some jsx:
> 
> ```js
> <h1 css={styles.cityHeading}>Sydney</h1>
> ```
> 
> Cant target with:
> 
> ```js
> expect(wrapper.find('h1')).to.have.text(
>   'Sydney'
> );
> ```
> 
> Because `@emotion/babel-preset-css-prop` converts to:
> 
> ```js
> <ForwardRef(render) 
>   css={{...}} __EMOTION_TYPE_PLEASE_DO_NOT_USE__="h1" 
>   __EMOTION_LABEL_PLEASE_DO_NOT_USE__="EmotionTest">
>   Sydney
> </ForwardRef(render)>
> ```
> 
> Converting to mount works around the issue - but its not ideal for all our tests to be mount tests

Have the exactly same issue with you @jooj123

**Comment by danieldelcore** [comment] 2019-03-24 23:51
Hi all, this might be have been fixed in this pr: https://github.com/emotion-js/emotion/pull/1280
We just merged it, so it might be a couple of days until it's released. 

@mitchellhamilton how often do you cut new releases?

**Comment by mitchellhamilton** [comment] 2019-03-25 02:45
I'll probably do a release later today.

**Comment by mitchellhamilton** [comment] 2019-03-25 07:43
Done.

**Comment by danieldelcore** [comment] 2019-03-25 08:19
Excellent! Thanks Mitch 😊

**Comment by jooj123** [comment] 2019-03-26 10:33
@danieldelcore @mitchellhamilton im not 100% across the code change - seems this will only work for jest emotion is that correct? 
I can only see jest emotion plugin changes (im not using jest - using mocha)

**Comment by drainpip** [comment] 2019-04-12 17:58
> Hi all, this might be have been fixed in this pr: #1280 We just merged it, so it might be a couple of days until it's released.

After a quick test and naive update to 10.0.10 (except `babel-plugin-emotion@10.0.9`), the `<ForwardRef>` stuff does indeed go away, but it's replaced with `css="unknown styles"`. I'll keep digging in and report back if I find what I did wrong (if anything).

**Comment by danieldelcore** [comment] 2019-04-12 22:27
Sweet! Yes that is intentional because the styles haven’t been mounted yet 😊

**Comment by drainpip** [comment] 2019-04-15 21:06
> Sweet! Yes that is intentional because the styles haven’t been mounted yet 

OK, that's interesting because behavior in v9 was quite different. We were able to get the names of the classes being used and write tests against them. If this is the intended behavior I'll have to revisit things from a different angle.

**Comment by Andarist** [comment] 2019-11-04 19:11
Seems like this has been fixed by #1280 so I'm going to close this issue. If you still have any problems with emotion - please just open a new issue.

**Closed by Andarist** 2019-11-04 19:11 UTC

**Comment by jooj123** [comment] 2019-11-06 01:21
@Andarist its only fixed for users of `jest-emotion` ? Is there a mocha solution that you know of ?

**Comment by torressam333** [comment] 2024-09-12 20:28
@jooj123 I am having the same issue. I am on emotion 11.13.x and using the latest enzyme.

I tried your solution:

```
    ].concat(
                    !isTest ? [
                        [
                            '@emotion/babel-preset-css-prop',
                            {
                                sourceMap: true,
                                autoLabel: 'never', // Use a valid value like 'never' for test environments
                                cssPropOptimization: true
                            }
                        ]
                    ] : []
                ),
```

But when I have a simple condition
```
 <ul css={someCondition ? styles.someStyles: [styles.list, styles.list[isSomething ? 'yes' : 'maybe']]}>
```

Then even with mount or shallow in enzyme I see the forwardRef

```
LOG: 'Shallow component:', '<ForwardRef css={[undefined]} __EMOTION_TYPE_PLEASE_DO_NOT_USE__="div" comps={{...}}>
  <ForwardRef css={{...}} __EMOTION_TYPE_PLEASE_DO_NOT_USE__="ul">
    <ForwardRef css={[undefined]} __EMOTION_TYPE_PLEASE_DO_NOT_USE__="li">
      <Chiclet data-at="filter_chiclet" onClick={[Function: onClick]} showX={true} variant="fill" maxWidth="32ch" display="inline-flex" alignItems="center" position="relative">
        bareMinerals
      </Chiclet>
    </ForwardRef>
    <li>
      <Link data-at="clear_all_link" onClick={[Function: onClick]} color="blue" fontSize={{...}} padding={2} marginX={-2} marginY={-2} theme={{...}} display="inline-block" arrowPosition="after">
        Clear all
      </Link>
    </li>
  </ForwardRef>
</ForwardRef>'

```

Any work around for this? Not even using mount solves my problem. Enzyme/jasmine is not able to find a simple ul tag.

```
  it('should render ul tag', () => {

        console.log('Shallow component:', wrapper.debug()); // Logs the full rendered output

        const elem = wrapper.find('ul');

        expect(elem.length).toEqual(1);

    });

```
