### ISSUE TITLE
CSS Class label applied twice

### ISSUE THREAD

**Issue by nicmosc** [emotion-js/emotion#1328] opened 2019-04-25 13:35 UTC
- `emotion` version: 10.0.9
- `react` version: 16.8.6

**What you did:**
We're working with `emotion` to style our components in our component library, and we're currently using it in a monorepo.

We're using the following `babel-plugin-emotion` options when transpiling the code:
```
["babel-plugin-emotion", {
   sourceMap: true,
   autoLabel: true,
   labelFormat: '[filename]__[local]',
}],
```
Because of some transformation we do to the CSS after building (production & dev) we need the labels to be always on, and we also specify a specific format as seen above. The labels are applied properly when building the component library.

This is the interesting part. In the same monorepo we have an app which will showcase those components, and the app itself also uses `emotion` to style its own custom components (similarly to how you would use [react-styleguidist](https://github.com/styleguidist/react-styleguidist)).

**What happened:**
Because the two packages use the same babel configuration, when using the transpiled components in development, the labels for those classes are applied twice. See screenshot below:

![image](https://user-images.githubusercontent.com/16778318/56739474-0128e980-676f-11e9-9ac1-68d16d0fddc8.png)

As you can see, the highlighted line is generated by the `Button` component from the library, and the "double" label can be seen as `css-1ert58-Button__base-Button__base `. Inspecting the bundled output from the "styleguide" app which uses the component, looking for the `Button` component styles we can see the following:

```
var Button_styles = {
  base:
  /*#__PURE__*/

  /*#__PURE__*/
  emotion_esm_css( true ? {
    name: "10sdv60-Button__base",
    styles: "background:red;label:Button__base;"
  } : undefined, "label:Button__base;" + ( true ? "" : undefined))
};
```
Where in the last section the label `Button__base` is added twice. Whereas in the `Button.js` transpiled component from the component library, we only have this:
```
base:
  /*#__PURE__*/
  _css(process.env.NODE_ENV === "production" ? {
    name: "10sdv60-Button__base",
    styles: "background:red;label:Button__base;"
  }
```
**Reproduction:**
You can reproduce this through this repo we made to show the issue: https://github.com/nicmosc/emotion-bug

**Suggested solution:**
We tried to use package-specific babel options but with the current behaviour it is impossible for us to get the desired outcome.

**Comment by danielhusar** [comment] 2019-06-16 19:40
Same for me:

<img width="604" alt="Screen Shot 2019-06-16 at 12 39 22" src="https://user-images.githubusercontent.com/1857751/59568751-cbe49d80-9033-11e9-9579-7a7fd92f8d52.png">

I think this happens when you change styles with `props` callback inside `styled`.

**Comment by Andarist** [comment] 2019-11-03 16:43
This will be fixed by https://github.com/emotion-js/emotion/pull/1602 . The issue has been caused by transpiling already transpiled code.

**Closed by Andarist** 2019-11-03 16:43 UTC
