### ISSUE TITLE
@import doesn't work with injectGlobal in production environment

### ISSUE THREAD

**Issue by OlesZadorozhnyy** [emotion-js/emotion#1177] opened 2019-01-15 15:01 UTC
```
injectGlobal`
   @import url('https://fonts.googleapis.com/css?family=Poppins:200,400,500,600');
   @import url('https://fonts.googleapis.com/css?family=Nunito:400,600');
`
```

This code doesn't load fonts with production environment. If i put there @font-face instead of @import, it'll be loaded. Strange behavior.

**Comment by FezVrasta** [comment] 2019-11-03 14:29
Thanks for the issue, would you be able to provide a CodeSandbox reproduction please?

**Comment by Andarist** [comment] 2019-11-03 21:22
I've tried to reproduce this without luck - so we are forced to close this, taken into account that the issue is quite old at this point in time. If OP provides a repro case I would be happy to take a look at the problem. I hope you understand.

**Closed by Andarist** 2019-11-03 21:22 UTC
Labels: needs more information
