### ISSUE TITLE
VS Code syntax highlighting

### ISSUE THREAD

**Issue by sandervspl** [emotion-js/emotion#1316] opened 2019-04-14 16:44 UTC
I would like to have syntax highlighting for my styled in VS Code, but I can't find anything in the docs or on Google. Is there anything similar to https://marketplace.visualstudio.com/items?itemName=jpoissonnier.vscode-styled-components for Emotion?

**Comment by lee-reinhardt** [comment] 2019-04-14 17:33
That plugin works for emotion as well.

**Comment by markogresak** [comment] 2019-04-16 22:21
Duplicate of #447.

**Comment by jasondonnette** [comment] 2019-04-24 08:27
I found that I had a conflicting plugin (for me it was `vscode-styled-jsx`) that broke certain syntax highlighting.

Works great after disabling that plugin!

**Comment by FezVrasta** [comment] 2019-04-24 12:02
Closing as dupe of #447 as mentioned by @markogresak (thanks!).

AFAIK, the recent `styled-components` versions introduced support for the `css` property so I think they will add (or added already) support for syntax highlighting for this property as well.

**Closed by FezVrasta** 2019-04-24 12:02 UTC

**Comment by aleclarson** [comment] 2020-04-27 12:48
The `vscode-styled-components` package will **not** support the entire Emotion API.

https://github.com/styled-components/vscode-styled-components/issues/107#issuecomment-413512135

Time for a fork?

**Comment by Andarist** [comment] 2020-04-27 21:08
@aleclarson do you have any example on when this vscode plugin fails with current emotion APIs?

**Comment by aleclarson** [comment] 2020-04-27 21:12
`injectGlobal`
![image](https://user-images.githubusercontent.com/1925840/80421286-3c8e5480-88aa-11ea-8c13-8dcb7016fd50.png)

**Comment by Andarist** [comment] 2020-04-27 21:19
Hm, that's weird - `injectGlobal` is also part of their API: https://styled-components.com/docs/api#deprecated-injectglobal . It might be deprecated now - but given not everyone had a chance to migrate to the newest version of SC etc it should be supported for the extended time period. They still even have such fixture:
https://github.com/styled-components/vscode-styled-components/blob/9fc89daf82f6dcf7f7d608d7801c5b20ef65b918/test/colorize-fixtures/injectGlobal.js
with accompanying snapshot:
https://github.com/styled-components/vscode-styled-components/blob/4320c223666ea835e8c63c85573c2704f550b7df/test/colorize-results/injectGlobal_js.json

Maybe there is some bug somewhere? 🤔

**Comment by aleclarson** [comment] 2020-04-28 13:47
@Andarist This syntax also has problems:
![image](https://user-images.githubusercontent.com/1925840/80494980-4e690980-8935-11ea-9c49-b73628f4aee4.png)

**Comment by Andarist** [comment] 2020-05-01 21:38
Hm, this code is also not emotion-specific. Could you check if that VScode extension handles this if you use `styled-components`? If not then it might be worth reporting a bug there. If yes then I would have to dig into this and potentially fork that plugin (but if we could avoid this I would prefer not doing this).

**Comment by karlhorky** [comment] 2020-06-19 12:56
> I found that I had a conflicting plugin (for me it was `vscode-styled-jsx`) that broke certain syntax highlighting.

Confirmed that [vscode-styled-jsx](https://github.com/iFwu/vscode-styled-jsx) breaks [`vscode-styled-components`](https://github.com/styled-components/vscode-styled-components) with Emotion and styled-components code.

This only started happening for me on the May 2020 version of VS Code (version 1.46).

![Kapture 2020-06-19 at 14 50 36](https://user-images.githubusercontent.com/1935696/85134376-a8eb5b80-b23c-11ea-8794-32c66ce30b78.gif)

See also:

- https://github.com/iFwu/vscode-styled-jsx/issues/4#issuecomment-646619998
- https://github.com/styled-components/vscode-styled-components/issues/208#issuecomment-646606763

**Comment by rgg-ccunningham** [comment] 2021-10-05 16:42
I've noticed the syntax highlighting works when I do an implicit return but when I do an explicit return it does not highlight syntax... any update on this?
<img width="1311" alt="Screen Shot 2021-10-05 at 12 40 43 PM" src="https://user-images.githubusercontent.com/82908442/136066168-034d6889-1633-4506-90a3-c8265ee9ed7c.png">
<img width="1267" alt="Screen Shot 2021-10-05 at 12 41 52 PM" src="https://user-images.githubusercontent.com/82908442/136066190-cef584c2-4419-45e3-9c4e-aa0fdc06a2b0.png">

**Comment by VictorLenevich97** [comment] 2021-12-14 13:35
**plugin** emotion-auto-css - helped me!

**Comment by tettoffensive** [comment] 2022-05-03 03:52
I've always had issues with vscode-styled-jsx and emotion. I finally just disabled it since it messes up my syntax highlighting for the rest of my file for everything after a css block.

```ts
<div
        css={[
          tw`bg-primary-lighter w-full h-full rounded-50 row-start-1 col-start-1 row-end-auto col-end-auto`,
          css`
            animation: ${breatheAnimation} 7s infinite;
          `,
        ]}
      />
```

**Comment by aderchox** [comment] 2023-02-10 11:37
For future visitors: If it's not working, also make sure it's not the fault of your VSCode theme, in my case I use "Kimbie Light" and it appeared as if syntax highlighting of vscode-styled-components was not working, but after testing with other themes, I've realized that it's actually working, but "Kimbie Light" is using similar colors for those tokens.
