### ISSUE TITLE
Next.js - Link - Styled <a> - Navigation Tab

### ISSUE THREAD

**Issue by Lulololu** [emotion-js/emotion#2196] opened 2020-12-30 17:25 UTC
**Hola**,

I don't know if it's an issue, but I would like to write this at least as an observation about the Tab Key Navigation on Next.js Link Component when you also use Emotion.

`import Link from 'next/link'
`

**1 - Next.js Link without Emotion**

As it's writtend in the documentation, you just have to wrap the <a>  inside the Link component :

```
function Home() {
  return (
    <ul>
      <li>
        <Link href="/">
          <a>Home</a>
        </Link>
      </li>
      <li>
        <Link href="/about">
          <a>About Us</a>
        </Link>
      </li>
      <li>
        <Link href="/blog/hello-world">
          <a>Blog Post</a>
        </Link>
      </li>
    </ul>
  )
}
```

**The Tab Key Navigation workds perfectly. You can also follow links when you use Enter.**

**2 - Next.js Link with Emotion**

```
const StyledLink = styled.a`
  background-color = blue;
  }
`;

function Home() {
  return (
    <ul>
      <li>
        <Link href="/">
          <a>Home</a>
        </Link>
      </li>
      <li>
        <Link href="/about">
          <a>About Us</a>
        </Link>
      </li>
      <li>
        <Link href="/blog/hello-world">
          <a>Blog Post</a>
        </Link>
      </li>
    </ul>
  )
}
```

Here, the Tab Key Navigation does NOT work at all.

**3 - Work-Around**

For me, what did work is that I duplicated the Link href into the <a> tag.

**2 - Next.js Link with Emotion**

```
const StyledLink = styled.a`
  background-color = blue;
  }
`;

function Home() {
  return (
    <ul>
      <li>
        <Link href="/">
          <a href="/">Home</a>
        </Link>
      </li>
      ...
      ....
    </ul>
  )
}
```

**Then, the Tab Key Navigation would work.**

**I don't know if it's an issue and where it's located (Next.js, Emotion...). If someone got an idea, please, share it.**

**Thank you all for your attention and your great great great work,**

**Comment by Andarist** [comment] 2020-12-30 17:32
I believe this is somewhat a duplicate of https://github.com/emotion-js/emotion/issues/2153 . It's Next-specific issue - they require you to use `passHref` prop on the `Link`

**Comment by Banaanas** [comment] 2020-12-30 18:09
@Andarist 

Ah ok. Sorry for the duplicate issue.

And thank you !

**Closed** 2020-12-30 20:32 UTC
