### ISSUE TITLE
CSS code after a function call nested in some media query breaks

### ISSUE THREAD

**Issue by cyrilchapon** [emotion-js/emotion#1937] opened 2020-07-21 11:35 UTC
**Current behavior:**

This works perfectly
```
const mqUntil = (bp: number) => `@media (max-width: ${bp}px)`

const NavbarWrapper = styled.div`
  ${props => mqUntil(props.theme.breakpoints.mobile)} {
    padding-left: ${props => props.theme.space[3]};
    padding-right: ${props => props.theme.space[3]};
  }

  background-color: green;
`
```

Whereas, in **some scenarios I couldn't reproduce consistently**, this breaks :
```
const mqUntil = (bp: number) => `@media (max-width: ${bp}px)`

export const CustomHorizontalPadding = (x: number) => css`
  padding-left: ${x}px;
  padding-right: ${x}px;
`

const NavbarWrapper = styled.div`
  ${props => mqUntil(props.theme.breakpoints.mobile)} {
    ${props => CustomHorizontalPadding(props.theme.space[3])}
  }

  /* HERE : ⚠️ this line is basically ignored */
  background-color: green;
`
```

Commenting `${props => CustomHorizontalPadding(props.theme.space[3])}` (leaving just the empty media query) makes the background appear

**To reproduce:**

It's very hard 😞
I have no clue why, but this exact same piece of code is working in other parts of application.

**Environment information:**

- `react` version: 16.13.1
- `emotion` version: 10.0.28

**Comment by Andarist** [comment] 2020-07-24 22:40
Well - if you don't provide a repro there is no much we can do as we can't just guess what's the problem.

**Comment by Andarist** [comment] 2020-08-02 14:46
Please note that if you don't provide a repro case I won't be able to take a look at your issue and will have to close this issue soon-ish.

**Closed** 2020-08-18 12:47 UTC
Labels: bug

**Comment by badsyntax** [comment] 2022-07-21 11:52
Hi. We're experiencing something similar in our project. Here's a repo: https://codesandbox.io/s/inspiring-feather-dp1dix?file=/src/App.js

Line 15 is the cause of the problem. If we replace line 15 with the contents of `nestedMediaQuery` then it works, but if we try reference the variable, it doesn't.

<img width="474" alt="Screenshot 2022-07-21 at 12 51 15" src="https://user-images.githubusercontent.com/102141/180207146-3089d3e5-97b8-42dd-a472-671ac51ae417.png">

**Comment by srmagura** [comment] 2022-07-31 15:26
Hey @badsyntax, you can fix it like this:

```
const StyledButton = styled.button`
  ${true
    ? css`
    @media (min-width: 20px) {
      ${nestedMediaQuery}
    }`
    : nestedMediaQuery}
  background-color: red;
`;
```

The only change is adding `css` on the line with the question mark. It seems to just have been a case of bad syntax :joy:.

The reason `css` is necessary there is that `nestedMediaQuery` is a `SerializedStyles` object. An object like that cannot be interpolated into a string using the normal JavaScript string interpolation. That's why you have to make it a `css` tagged template literal which _does_ know how to interpolate `SerializedStyles` objects.

**Comment by badsyntax** [comment] 2022-08-01 09:00
@srmagura thank you for the reply, solution, and explanation :)
