### ISSUE TITLE
css functions only applied twice within component selector

### ISSUE THREAD

**Issue by ILovePug** [emotion-js/emotion#1652] opened 2019-11-25 14:22 UTC
**Current behavior:**

When using css function multiple times within component selectors, the styles are only applied for the first two component selectors.
For this example, ideally all four colors should turn black but only the first two are black.
```javascript
import styled from "@emotion/styled/macro";
import css from "@emotion/css/macro";

const ChildComp = styled.div``;
const ChildText = styled.p`
  color: red;
`;
const ChildText2 = styled.p`
  color: blue;
`;
const ChildText3 = styled.p`
  color: purple;
`;
const ChildText4 = styled.p`
  color: orange;
`;
const ParentComp = styled.div`
  font-size: 2rem;

  ${ChildText} {
    ${css`
      color: black;
    `}
  }
  ${ChildText2} {
    ${css`
      color: black;
    `}
  }
  ${ChildText3} {
    ${css`
      color: black;
    `}
  }
  ${ChildText4} {
    ${css`
      color: black;
    `}
  }
`;
function App() {
  return (
    <ParentComp>
      <ChildComp>
        <ChildText>Red</ChildText>
        <ChildText2>Blue</ChildText2>
        <ChildText3>Purple</ChildText3>
        <ChildText4>Orange</ChildText4>
      </ChildComp>
    </ParentComp>
  );
}
```
![Screen Shot 2019-11-25 at 9 16 23 AM](https://user-images.githubusercontent.com/19334427/69547875-524ac700-0f64-11ea-9e76-500e8f5d4902.png)

**To reproduce:**

latest emotion version example:
https://codesandbox.io/s/romantic-wilson-7up2w

emotion template version example: 
https://codesandbox.io/s/css-only-applied-twice-l8jjz

**Expected behavior:**

**Environment information:**

Tried both template version and latest version and reproducible in both. 
Template version: 
  "dependencies": {
    "@emotion/core": "10.0.10",
    "@emotion/css": "10.0.9",
    "@emotion/styled": "10.0.11",
    "react": "16.8.6",
    "react-dom": "16.8.6",
    "react-scripts": "2.1.8"
  },

Latest version: 
  "dependencies": {
    "@emotion/core": "10.0.22",
    "@emotion/styled": "10.0.23",
    "react": "16.8.6",
    "react-dom": "16.8.6",
    "react-scripts": "3.0.1"
  },

**Comment by Andarist** [comment] 2019-11-25 22:56
Based on your report I've identified a bug in the parser we use and reported a problem there https://github.com/thysultan/stylis.js/issues/154 . It might be hard to fix there though. 

At the same time, I've found a workaround for you - which of course is not ideal, but can be used in the meantime:
```diff
const ParentComp = styled.div`
  font-size: 2rem;

  ${ChildText} {
    ${css`
      color: black;
-    `}
+    `};
  }
  ${ChildText2} {
    ${css`
      color: black;
-    `}
+    `};

  }
  ${ChildText3} {
    ${css`
      color: black;
-    `}
+    `};

  }
  ${ChildText4} {
    ${css`
      color: black;
-    `}
+    `};

  }
`;
```

And it also possibly has uncovered a problem with source map being slightly incorrect sometimes (pointing to a different location) - a fix for that would actually, sort of, fix your problem, but I'm afraid that I need to study this issue a little bit more and I only plan to release it in upcoming v11 (we plan to release it before the end of the year).

**Comment by ILovePug** [comment] 2019-11-26 00:57
No problem. Thank you very much for looking into it! It is not a rush as for now I will only use string inside of component selector instead of css function and use css function externally to convert string to the styles.

**Comment by Andarist** [comment] 2019-11-26 07:14
I'm going to close the issue then because it seems that we can't really do much right now about it (I wouldn't like to introduce any accidental regression into v10 at this point in time) and because we've merged in a change that should "fix" it by coincidentally - https://github.com/emotion-js/emotion/pull/1653 . Hope you understand. Keep in mind that we release v11 versions regularly and they are very much usable, there won't be many breaking changes there except package renaming and similar stuff - so I encourage you to migrate to it if you have a little bit of time to do so.

**Closed by Andarist** 2019-11-26 07:14 UTC
Labels: bug
