### ISSUE TITLE
Unnecessary `@babel/core` peer dependency?

### ISSUE THREAD

**Issue by cpojer** [emotion-js/emotion#2660] opened 2022-02-23 01:20 UTC
**Current behavior:**

`@babel/core` is a peerDependency of `@emotion/styled`, `@emotion/css` and `@emotion/react`.

**To reproduce:**

Install one of the above packages when babel is not used, and your dependency manager will likely issue a warning.

**Expected behavior:**

Nothing in those packages seems to be actively depending on Babel. When using a Vite/esbuild environment, Babel may not be part of the dependencies.

**Environment information:**

React 18 RC, latest `@emotion/react`.

**Comment by srmagura** [comment] 2022-02-23 01:35
The `@babel/core` peerDep is marked as optional. Which package manager is producing a warning on this? I just added `@emotion/react` to an empty project using Yarn 3 and there was no warning.

**Comment by cpojer** [comment] 2022-02-23 01:37
This is pnpm:
<img width="328" alt="Screen Shot 2022-02-23 at 10 36 37" src="https://user-images.githubusercontent.com/13352/155248366-5cfa6c9d-f821-4f3b-b926-73df8043e0c4.png">

Either way, I don't see any usage of `@babel/core` in those packages. Why is it listed as a peer dependency?

**Comment by srmagura** [comment] 2022-02-23 01:42
I have no idea. It seems like the peerDep could be removed without causing any issues. @Andarist know anything about this?

**Comment by Andarist** [comment] 2022-02-25 23:43
The problem is that our `/macro` entries depend on `@babel/core`. To satisfy strict package managers we need to declare those. They are declared as optional though so if you are seeing warnings and stuff then I would classify this as a problem with the given package manager.

Is the current structure ideal? Probably not - I think that it's reasonable to move those entries to separate packages in the next major version. Doing this right now would be a breaking change though so it's not something that we can just do.

**Comment by SimonCJacobs** [comment] 2022-09-05 07:36
There is an error though even if the package manager treats the optional flags correctly.

`@emotion/babel-plugin` is a full dependency of `@emotion/css`, `@emotion/react` and `@emotion/styled`, and in turn `@babel/core` is a non-optional peer dependency of `@emotion/babel-plugin`.

So with the current structure you do correctly get an unmet peer dependency warning at the `@emotion/babel-plugin` level when using any of the headline packages.

**Comment by Andarist** [comment] 2022-09-05 08:39
Hm, just to make sure that I read this correctly - when installing, let's say, `@emotion/react` we pull in `@emotion/babel-plugin` because it's a regular dependency and it has non-optional peer dependency on `@babel/core` and thus we still end up with unmet peer dependency warnings. Is this correct?

**Comment by SimonCJacobs** [comment] 2022-09-05 09:03
Precisely correct, yes. Thanks for looking at.

**Closed** 2023-02-16 22:54 UTC
Labels: breaking change
