### ISSUE TITLE
Default theme in HOC withTheme

### ISSUE THREAD

**Issue by javialon26** [emotion-js/emotion#1193] opened 2019-01-24 06:10 UTC
- `emotion` version: 10.0.6
- `react` version: 16.7.0

**What you did:**
I'm building a library that uses the withTheme HOC and i want to set a default theme if the final user do not use a ThemeProvider.

**What happened:**

The withTheme HOC always set an empty object in the prop theme.

**Reproduction:**
Create a component and wrap it up with withTheme HOC. If use this component without a ThemeProvider the theme prop is always an empty object.

**Problem description:**
The issue is that if the library consumer is not using ThemeProvider then my components throws errors because the prop theme is empty. (By design i want the use of ThemeProvider is entirely optional.)

**Suggested solution:**
Maybe withTheme can set a null or undefined theme when a theme in context is not available.

Another idea is withTheme HOC can receive a second argument with the default theme and use it in case the theme in context is missing.

Or theming can have a create theming provider like in:
https://github.com/callstack/react-theme-provider

Thank you!

**Comment by danieldelcore** [comment] 2019-03-14 05:47
+1 Also running into this issue

**Comment by danieldelcore** [comment] 2019-03-14 05:56
The problem is that checking for an empty object is quite cumbersome. It would be lovely to instead do something like: 

`const theme = this.props.theme || defaultTheme;` 

I guess another way to fix the issue is to just assign `defaultTheme` as a default prop. It's not obvious at first but it's arguably better than passing undefined around.

```javascript
import { withTheme } from '@emotion/theming';

import { defaultTheme } from './theme';

const MyComponent = ({ theme }) => (
  <button>Hello, World!</button>
);

MyComponent.defaultProps ={ 
  theme: defaultTheme,
};

export default withTheme(MyComponent)
```

**Comment by mmartinsky** [comment] 2019-05-03 21:11
same issue - the problem with setting the defaultProp is that the empty object overrides it.

**Comment by Iuriy-Budnikov** [comment] 2019-09-11 20:03
any updates?

**Comment by anicholls** [comment] 2019-10-15 23:22
I am having the same problem on Emotion 10.

I've tried both a default parameter and default props. Both get overridden with an empty object.

```tsx
const MyComponent = styled('div')<TestProps>(({theme = defaultTheme}) => {
  // theme is {} and does not equal defaultTheme
  return {};
});

class Test extends React.Component<TestProps> {
  static defaultProps = {
    theme: defaultTheme,
  };

  render() {
    return <MyComponent>Hello World</MyComponent>;
  }
}
```

This was suggested for Emotion 9 in https://github.com/emotion-js/emotion/issues/811, but it doesn't seem like it has been resolved in Emotion 10. The typescript docs show how to [define a theme](https://emotion.sh/docs/typescript#define-a-theme), but it only gives you type checking for a theme used with `ThemeProvider` and does not allow you to set a default theme if no provider is used. 

It seems like we need support for a `defaultTheme` option in [`StyledOptions`](https://github.com/emotion-js/emotion/blob/master/packages/styled-base/src/index.js#L26), which we can fall back on [here](https://github.com/emotion-js/emotion/blob/master/packages/styled-base/src/index.js#L99). 

Please give us an update on this!

**Comment by Andarist** [comment] 2019-11-04 21:05
This is a "limitation" of React context - it's just impossible to provide a default value after creating the context and we need to create it upfront so we can consume it to provide it to you in interpolations etc.

For this and other reasons described here - https://github.com/emotion-js/emotion/pull/973 - we believe that theming really shouldn't be Emotion's concern. We will support it though for a foreseeable future because it's convenient and people want it. However builtin theme context has inherent problems associated with it (as described in the linked PR) and in cases such as yours, we believe that you should just create your own theme context (in which you would be able to embed a default theme value) - and we plan to make it easier to create "custom" themes with this PR https://github.com/emotion-js/emotion/pull/1577 .

**Closed by Andarist** 2019-11-04 21:05 UTC
