### ISSUE TITLE
Vercel build : registerStyles is not a function (not exported from @emotion/utils)

### ISSUE THREAD

**Issue by nomocas** [emotion-js/emotion#2702] opened 2022-03-30 14:48 UTC
**Current behavior:**

When our project is pushed on vercel (nextjs project with latest @chakra-ui) : we have a warning.
Warning which is visible in the build process (but that does not block the build).

Vercel build logs:
```
warn  - Compiled with warnings

./node_modules/@emotion/styled/base/dist/emotion-styled-base.browser.esm.js
--
16:18:19.896 | Attempted import error: 'registerStyles' is not exported from '@emotion/utils' (imported as 'registerStyles').
```

But it throws in the browser :

Browser logs: 
```
build.umd.js:3030 TypeError: (0 , r.registerStyles) is not a function
    at F (_app-b803f9892612ebe33cd7.js:1:73070)
    at ro (/_next/static/chunks/framework-4eeab015d61905b9a9e0.js?__WB_REVISION__=cBOMTQDRP5FizIkE0AzuO:1:60237)
    at Hu (/_next/static/chunks/framework-4eeab015d61905b9a9e0.js?__WB_REVISION__=cBOMTQDRP5FizIkE0AzuO:1:112695)
    at Pi (/_next/static/chunks/framework-4eeab015d61905b9a9e0.js?__WB_REVISION__=cBOMTQDRP5FizIkE0AzuO:1:99869)
    at xi (/_next/static/chunks/framework-4eeab015d61905b9a9e0.js?__WB_REVISION__=cBOMTQDRP5FizIkE0AzuO:1:99797)
    at _i (/_next/static/chunks/framework-4eeab015d61905b9a9e0.js?__WB_REVISION__=cBOMTQDRP5FizIkE0AzuO:1:99660)
    at vi (/_next/static/chunks/framework-4eeab015d61905b9a9e0.js?__WB_REVISION__=cBOMTQDRP5FizIkE0AzuO:1:96626)
    at /_next/static/chunks/framework-4eeab015d61905b9a9e0.js?__WB_REVISION__=cBOMTQDRP5FizIkE0AzuO:1:46005
    at /_next/static/chunks/framework-4eeab015d61905b9a9e0.js?__WB_REVISION__=cBOMTQDRP5FizIkE0AzuO:1:130410
    at Wl (/_next/static/chunks/framework-4eeab015d61905b9a9e0.js?__WB_REVISION__=cBOMTQDRP5FizIkE0AzuO:1:45782)
```

The page isn't working: 
```
Application error: a client-side exception has occurred (see the browser console for more information).
```

We do not have the error locally, even when doing `next build`.

Related ./node_modules/@emotion/styled/base/dist/emotion-styled-base.browser.esm.js import:
```
import { getRegisteredStyles, registerStyles, insertStyles } from '@emotion/utils';
```

**Environment information:**

```
"@chakra-ui/react": "^1.8.7",
"@emotion/react": "^11.8.2",
"@emotion/styled": "^11.8.1",
"@emotion/utils": "^1.1.0"
"next": "^12.1.2",
"react": "^17.0.2",
"react-dom": "^17.0.2",
...
"typescript": "^4.6.3"
```

**Comment by Andarist** [comment] 2022-03-30 15:58
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by danielfoxp2** [comment] 2022-03-30 18:17
`npm install` is not working too in local environment. It seems to be some react version conflicts. As you guys works with yarn, you probably are not seeing the npm part being broken.

**Comment by srmagura** [comment] 2022-03-30 18:34
@nomocas What does Vercel do differently than a normal, local build? If you can follow the exact same steps as Vercel does, I would expect you to be able to reproduce the error locally.

Some things to look into might be:

- npm version in Vercel
- Whether there are multiple versions of any `@emotion` packages lurking in your `node_modules` — I am a Yarn guy but I think you can do this with `npm list`

**Comment by srmagura** [comment] 2022-03-30 18:37
@danielfoxp2  You are using React 17 but `material-ui-numeric-input` has a peer dependency on React 16.

**Comment by danielfoxp2** [comment] 2022-03-30 18:46
Thanks @srmagura, can you explain me why with yarn it works?

**Comment by srmagura** [comment] 2022-03-30 18:53
I'm not sure if you're using Yarn 1 or Yarn 3 so I can't give you an exact answer. I would guess Yarn 1. Yarn 1 is likely less aggressive about strictly enforcing peer dependencies that the latest version of npm.

**Comment by danielfoxp2** [comment] 2022-03-30 18:59
Yeah, checked here, yarn 1.22. Thank you for your clarifications, sorry having mess up the issue.

**Comment by srmagura** [comment] 2022-03-30 23:34
@nomocas Yeah that's a really weird issue so I understand your frustration! 

Sorry for giving you the npm command — I see now that you are using Yarn 1. It does look like you have a single instance of `@emotion/utils` in `node_modules`, which is what we want.

If you are able to reproduce the issue locally in a small project, I will certainly take a lot at it.

Some things to consider:

- Is the Vercel build doing any sort of dependency caching? This could be screwing something up.
- You could try upgrading to Yarn 3 with `nodeLinker: node-modules`. This is typically a painless upgrade, and Yarn 3 does have some bug fixes and performance improvements over Yarn 1.

**Comment by nomocas** [comment] 2022-03-31 13:09
Ok so...

The problem is coming from the `@emotion/styled >=11.8.X`.  When I try with the v11.6.0 (last release before v11.8), it works.

Any idea about the dist changes between those version ? It's clearly related on the way you build the dist files.

**Comment by nomocas** [comment] 2022-03-31 13:17
Ah I didn't see your message in between. (I didn't refresh this page. My bad.)

Yes Vercel is using a build cache system. We could ask to redeploy without the cache. 

I did not find time to produce a small project today. And I go on holiday tomorrow... 

I'll give a try to update my yarn, but whatever, I think vercel should also do it (as they are currently in 1.22.17).

So for now, the workaround is to fix `"@emotion/styled": "11.6.0"` in package.json.

**Comment by srmagura** [comment] 2022-03-31 17:33
- That's interesting that it works with `@emotion/styled` 11.6.0. One possibility is that switching the package version caused Vercel to rebuild its cache, which may have been screwed up. If you go back to 11.8.1, does the problem begin occurring again?
- I am assigning this issue to myself. If you can confirm it's not a caching issue, I will compare the dist files for 11.6.0 and 11.8.1 to try to figure out what changed.
- I don't think this is super relevant but: the Yarn 3 installation lives in your repository, so if you upgraded to Yarn 3, Vercel would automatically use it even though the global Yarn version is 1.22.17.

**Comment by nomocas** [comment] 2022-03-31 22:29
Hello @srmagura,

I do confirm that this is not a cache problem from vercel. When I switch back to 11.8.1 it failed again. Even if I force re-deployment without using cache.

I'll definitely update my yarn to v3 but after my holiday... ;)

Thanks for assigning this issue to yourself.

Hello @Andarist,

I have only one entry about `@emotion/sytled` in my yarn.lock. And vercel is offering a full-fledged CI which does everything for us. So we do not control how it triggers the package installation. So no parameters are provided to yarn install.

Cheers.

**Comment by srmagura** [comment] 2022-03-31 22:33
Thanks for confirming it is not a caching problem, will investigate soon. 

I have not used Vercel but personally I prefer the model used in GitHub Actions and similar CI/CD platforms where you specify the exact commands to run.

**Comment by nomocas** [comment] 2022-03-31 22:52
I do understand that's better when you have control over your CI. Our backend is on a separated CI/CD from gitlab. But vercel (the company behind nextjs framework) is offering the state of the art for frontend projects. You should try... ;)

Ok, I close my laptop and go to the mountains!

Have a nice week.

**Comment by Andarist** [comment] 2022-04-01 08:15
> I have only one entry about @emotion/sytled in my yarn.lock.

Note that the question was about `@emotion/utils` :p

> and vercel is offering a full-fledged CI which does everything for us. So we do not control how it triggers the package installation. So no parameters are provided to yarn install.

do you have access to any logs from that CI? perhaps we would see there what commands are exactly executed there

---

The issue here is really hard to diagnose without a repro case (I understand why it's hard for you to create one though). This shouldn't happen (as it doesn't happen for you locally). The only reason that could cause this that comes to my mind is that the CI downloads an outdated `@emotion/utils` package. However, our dependency ranges shouldn't allow for that...

**Comment by nomocas** [comment] 2022-04-13 10:13
Hi @Andarist,

I also have only one entry for `@emotion/utils` in my `yarn.lock`.

As I explained above, yes I see the build logs but no I do not have more information about the exact command executed by Vercel.

And yep, is quite hard to provide a repo for repro, as it doesn't happen locally. But as you have read, when I fix any version below or equal to 11.6.x, it works. So in my opinion it's not linked to an outdated `@emotion/utils` package. It's really linked to newer versions.

Thanks for checking.

**Comment by MCK-Robert-Cowell** [comment] 2022-04-13 22:07
I'm also experiencing this error. I thought it might be because my Webpack config wasn't handling `*cjs.js` files, but fixing that hasn't made a difference.

I am not using Vercel at all either.

When I load a Chakra UI component (in dev mode locally), I get this error in my browser's console:
```
Uncaught TypeError: utils.registerStyles is not a function
```
The offending line is apparently: `emotion-styled-base.browser.cjs.js:81`

**Comment by MCK-Robert-Cowell** [comment] 2022-04-13 22:39
I'm guessing we somehow have an outdated (pre [1.1.0](https://github.com/emotion-js/emotion/releases/tag/%40emotion%2Futils%401.1.0)) version of `@emotion/utils` installed, as that's when this `registerStyles` function was added.

**Comment by jkimber** [comment] 2022-04-14 11:07
Running an install of the offending packages got an otherwise broken build working for me.  With resulting duplicates in the yarn.lock, rather than adding the dependencies (as they were already listed as subdependencies elsewhere) - adding resolutions to the package.json worked also:

```
"resolutions": {
    "@emotion/utils": "^1.1.0",
    "@emotion/sheet": "^1.1.0"
}

As @MCK-Robert-Cowell says above, the renderStyles didn't appear in the version of @emotion/utils that was getting installed / used by default.  Forcing it to ^1.1.0 seems to have done the trick.

**Comment by MCK-Robert-Cowell** [comment] 2022-04-14 18:44
> Running an install of the offending packages got an otherwise broken build working for me. With resulting duplicates in the yarn.lock, rather than adding the dependencies (as they were already listed as subdependencies elsewhere) - adding resolutions to the package.json worked also:
> 
> ```
> "resolutions": {
>     "@emotion/utils": "^1.1.0",
>     "@emotion/sheet": "^1.1.0"
> }
> ```
> 
> As @MCK-Robert-Cowell says above, `renderStyles` didn't appear in the version of @emotion/utils that was getting installed / used by default. Forcing it to ^1.1.0 seems to have done the trick.

This fixed it for me, thanks @jkimber!

**Comment by Andarist** [comment] 2022-04-14 19:31
So you both had duplicate versions of `@emotion/utils` installed? Would using [`yarn-deduplicate`](https://www.npmjs.com/package/yarn-deduplicate) work for you instead of forcing the version with resolutions?

**Comment by MCK-Robert-Cowell** [comment] 2022-04-15 15:54
> So you both had duplicate versions of `@emotion/utils` installed? Would using [`yarn-deduplicate`](https://www.npmjs.com/package/yarn-deduplicate) work for you instead of forcing the version with resolutions?

It might help if you're using Yarn, but I'm using npm. Earlier in this thread, you can see that things seem to be working in Yarn and not npm, so I'm thinking this could be related to how npm is deciding to resolve dependencies.

**Comment by Andarist** [comment] 2022-04-15 16:01
Could you share your lockfile with me?

**Comment by jkimber** [comment] 2022-04-19 07:08
@MCK-Robert-Cowell: I didn't think to use `yarn-deduplicate` and the "resolutions" fix is committed to our `main` now as it needed to get resolved.

I did take a snapshot of the offending duplicate-dependency lines in the lockfile though if that may help:

![image](https://user-images.githubusercontent.com/39876090/163944474-0f78fba2-0268-4bef-b2ba-aa8fc88c7270.png)

It was the hint about the versions that tipped me off to investigate `node_modules/@emotion/utils/src` and can confirm - having matched what was there to the emotion GitHub repo - that yarn had installed the first one from the image above, until I added the packages manually - but then instead of adding further dependencies we went with the resolutions option.

What was most troubling was that some developers on the team weren't having the problem - and neither was our build server (TeamCity).  😕 

I can try the de-duplicate a bit later if that might help others?

**Comment by jkimber** [comment] 2022-04-22 15:23
Just a quick follow up on this for anyone else that may be intrigued.  

I tried [yarn-deduplicate](https://www.npmjs.com/package/yarn-deduplicate) - but it didn't have the same effect alas.  

It would be slightly annoying to have to add this as a build step in CI anyway imho, but thought I'd at least check to see if it would work for me.  

`resolutions` seems to be the only workaround so far - until those other packages that have the earlier dependencies do their upgrades, or whatever is (seemingly randomly) selecting that previous version (yarn?) stops doing that.

**Comment by Andarist** [comment] 2022-07-31 08:44
From my point of view, this issue looks a lot like an issue with a package manager or a bundler and not with Emotion itself. So I don't think there is anything actionable on our side to fix this (until proven otherwise). That being said - I'm going to do a release of all packages in a moment, so perhaps once you upgrade everything will magically fix itself.

**Closed by Andarist** 2022-07-31 08:44 UTC
Labels: bug, needs triage

**Comment by Andarist** [comment] 2022-11-04 12:00
I just hit this issue myself and had to figure it out.

In my case, this was an issue with Yarn 1 which produced a broken `node_modules` layout when running `yarn` on top of existing `node_modules`. A fresh install created a valid layout and fixed the issue. The solution was to redeploy my Vercel builds without the build cache. This is as simple as clicking the Redeploy button on the failed build's page:
https://vercel.com/docs/concepts/deployments/troubleshoot-a-build#managing-build-cache

**Comment by softmarshmallow** [comment] 2023-03-11 13:11
For me, redploying it did it. (There were no issues on the local env)
