### ISSUE TITLE
Using the :not selector globally, is it possible?

### ISSUE THREAD

**Issue by kuworking** [emotion-js/emotion#1787] opened 2020-03-04 19:00 UTC
Is there a way to use the `:not()` global selector?

When using this (within a Gatsby site)

```css
& > div:nth-of-type(1) :not(ul) a {
/* ... */
}
```

it gets transformed into (without spacing before the `:not()` )

```css
& > div:nth-of-type(1):not(ul) a {
/* ... */
}
```

![image](https://user-images.githubusercontent.com/4474004/75913078-8df20880-5e52-11ea-9687-b21b240a7868.png)

(here there's a fiddle showing the consequence of this)
https://jsfiddle.net/qzxcyw0s/1/

**Comment by kuworking** [comment] 2020-03-04 21:14
Closed by mistake, reopening

**Comment by Andarist** [comment] 2020-03-07 09:40
I'm afraid that I don't know how to workaround this. It's how our parser ( https://github.com/thysultan/stylis.js/ ) works. I suspect this is related to this issue https://github.com/thysultan/stylis.js/issues/64 but it's uncertain when it will get fixed there and thus it's also uncertain when we'll benefit from the fix in emotion.

**Comment by kuworking** [comment] 2020-03-08 11:44
Fair enough, should this remain open for future users looking for this functionality?

**Comment by Andarist** [comment] 2020-03-10 21:16
Actually, after looking again at this and testing it with Emotion and with Stylis alone - I can't reproduce your problem. Could you prepare a repro case on CodeSandbox?

**Comment by thysultan** [comment] 2020-03-10 21:45
Even given the current heuristics i don't see why it wouldn't be possible given that `:not(ul)` is equivalent to `*:not(ul)` so the selector can be rewritten to `& > div:nth-of-type(1) *:not(ul) a`.

**Comment by Andarist** [comment] 2020-03-10 22:56
Thanks for the answer @thysultan ! You are right, those should be equivalent - I haven't thought of that. But even given that - I still cannot repro the reported case.

**Comment by Andarist** [comment] 2020-03-13 19:59
As mentioned above - I can't really repro this so I'm going to close this issue, but if you come back with a repro I will reopen this.

**Closed by Andarist** 2020-03-13 19:59 UTC
Labels: bug

**Comment by kuworking** [comment] 2020-03-13 20:47
Indeed I neither can reproduce it with a sandcodebox, 

- not with React
- and neither with Gatsby, which has surprised me

So I guess there's something obscure with my code (but I'm not crazy, there there's the screenshot 😬) 

Thanks for the fast responses!

*(I used another css to get the job done)
