### ISSUE TITLE
Bugged when trying to use CSS variables

### ISSUE THREAD

**Issue by LXSMNSYC** [emotion-js/emotion#1717] opened 2020-01-13 06:14 UTC
Bug when trying to use CSS variables in stylesheets.

**Current behavior:**
<img width="725" alt="Screen Shot 2020-01-13 at 2 10 50 PM" src="https://user-images.githubusercontent.com/4783372/72235763-e2c19180-360e-11ea-9f51-8f9d8e384200.png">

**Expected behavior:**
<img width="725" alt="Screen Shot 2020-01-13 at 2 09 31 PM" src="https://user-images.githubusercontent.com/4783372/72235757-d806fc80-360e-11ea-8671-75363e7d7ddf.png">

**Comment by LXSMNSYC** [comment] 2020-01-13 06:16
It seems that the classnames generated by css function itself is bugged when used for nested selectors:

<img width="716" alt="Screen Shot 2020-01-13 at 2 15 41 PM" src="https://user-images.githubusercontent.com/4783372/72235825-36cc7600-360f-11ea-8c6f-1f8ad7301963.png">

Notice how the whole paragraph gets the underline style

**Comment by Andarist** [comment] 2020-01-13 21:08
I believe this is a duplicate of #1715

**Closed by Andarist** 2020-01-13 21:08 UTC
Labels: bug, needs triage
