### ISSUE TITLE
[SUPPORT] Is there a reason why the grayscale filter was added to the documentation website?

### ISSUE THREAD

**Issue by ooade** [emotion-js/emotion#1927] opened 2020-07-08 18:04 UTC
I'm having a really hard time using the documentation website because of the grayscale filter on the main and aside elements. Is there a specific reason why we applied the filters?

**Comment by Andarist** [comment] 2020-07-08 20:02
Duplicate of https://github.com/emotion-js/emotion/issues/1918

I will remove this grayscale filter soon.

**Closed by Andarist** 2020-07-08 20:02 UTC
Labels: invalid
