### ISSUE TITLE
React18 cache global style order incorrect.

### ISSUE THREAD

**Issue by iDerekLi** [emotion-js/emotion#2741] opened 2022-04-29 06:10 UTC
**Current behavior:** React18 cache global style order incorrect.

**To reproduce:**

1. curl https://codeload.github.com/mui/material-ui/tar.gz/master | tar -xz --strip=2  material-ui-master/examples/nextjs
2. cd nextjs
3. yarn && yarn dev

**Expected behavior:** In the correct order.

This is React18.
![image](https://user-images.githubusercontent.com/24502299/165891181-a8f7f901-70c5-4b73-9159-60a03b9a6958.png)

This is React17.
![image](https://user-images.githubusercontent.com/24502299/165892695-e7956eec-6c19-46bf-85c3-93fa3eb6913a.png)

**Environment information:** 

- `react` version: 18.1.0
- `@emotion/react` version: 11.7.1

```
{
    "@emotion/cache": "^11.7.1",
    "@emotion/react": "^11.7.1",
    "@emotion/server": "^11.4.0",
    "@emotion/styled": "^11.8.1",
    "@mui/icons-material": "^5.6.2",
    "@mui/material": "^5.6.2",
    "react": "^18.1.0",
    "react-dom": "^18.1.0"
}
```

**Comment by Andarist** [comment] 2022-04-29 11:14
It looks like a duplicate of https://github.com/emotion-js/emotion/issues/2725 . I've confirmed that this is fixed with `next@12.1.6-canary.14`.

**Closed by Andarist** 2022-04-29 11:14 UTC
Labels: bug, needs triage
