### ISSUE TITLE
Safari will yell if using innerRef.

### ISSUE THREAD

**Issue by rockmandash** [emotion-js/emotion#757] opened 2018-07-09 05:43 UTC
Please see this minimum example with safari.
[![Edit n411l7qjkm](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/n411l7qjkm)
Opening safari's devtool and there is one error message says
```
Warning: div: `ref` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://fb.me/react-special-props)
```
I don't know how to fix this, please help, thank you!

**Comment by Andarist** [comment] 2018-07-09 07:33
Does it happen in real app? This might be some issue with codesandbox - if you comment out `console.log` in `componentDidMount` and uncomment it again the warning will disappear (without changing the code).

**Comment by rockmandash** [comment] 2018-07-09 07:46
@Andarist 
It happens in my development, howerver, it only happens in development mode.
When I run build, the warning goes away.

**Comment by mitchellhamilton** [comment] 2018-07-09 08:43
I did some debugging on this and it seems that safari accesses getters on nested objects passed to `console.log`.
<details>
<summary>Some code demonstrating this</summary>

```jsx
// run this in the safari console
let inner = {
  get someProperty() {
    console.log('this will log even though this property is not accessed by the user')
  }
}

let outer = {
  inner
}

console.log(outer)
```

</details>

The reason this happens is that when you pass props to `React.createElement` it creates a props object and if you pass a ref to createElement in dev, it sets a getter on the props with that warning so that you see it if you try to access ref as a prop. React sets the props object onto the dom node for internal react stuff so if you log the dom node in safari, safari will access all the getters and therefore log the warning.

You might want to open an issue with react about this though it's more of an issue with safari but the react team might want to try and find a way around it.
I made a reproduction with only react [here](https://codesandbox.io/s/1q3q5kv09q).

This isn't an issue with emotion so I'm going to close it.

**Closed by mitchellhamilton** 2018-07-09 08:43 UTC

**Comment by rockmandash** [comment] 2018-07-09 09:18
@mitchellhamilton Wow, thank you for your fast reply.
Now I know the problem, thank you!

**Comment by rockmandash** [comment] 2018-07-09 09:37
I've ref the issue
https://github.com/facebook/react/issues/13179

**Comment by burg** [comment] 2018-08-03 17:10
Upstream fix in Webkit tracked here:

https://bugs.webkit.org/show_bug.cgi?id=187542
