### ISSUE TITLE
Prop `className` did not match

### ISSUE THREAD

**Issue by andreyvital** [emotion-js/emotion#1462] opened 2019-08-07 14:56 UTC
**Current behavior:**

```
Warning: Prop `className` did not match. Server: "css-1ji17la-Object" Client: "css-o1vk5f"
```

Create a **pages/index.js** with this content:

```JS
import React from "react";

function WeirdStuff({ styles, children }) {
  return children(1, styles[0]());
}

export default () => {
  return (
    <table>
      <tbody>
        {[1, 2, 3, 4].map(value => {
          return (
            <tr key={value}>
              <WeirdStuff
                styles={[
                  () => ({
                    color: "green"
                  })
                ]}
              >
                {(hmm, css) => {
                  return (
                    <td
                      css={{
                        fontSize: 21,
                        ...css
                      }}
                    >
                      {hmm}
                    </td>
                  );
                }}
              </WeirdStuff>
            </tr>
          );
        })}
      </tbody>
    </table>
  );
};
```

**babel.config.js**
```
module.exports = {
  presets: ["next/babel", "@emotion/babel-preset-css-prop"]
};
```

**Expected behavior:**
Shouldn't be seeing the error.

**package.json**
```
{
  "scripts": {
    "start": "next"
  },
  "dependencies": {
    "@emotion/babel-preset-css-prop": "^10.0.14",
    "@emotion/core": "^10.0.15",
    "emotion": "^10.0.14",
    "next": "^9.0.3",
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
  }
}

```

**Comment by andreyvital** [comment] 2019-08-07 14:57
Interesting enuff, if you remove the 1st argument:

```JS
function WeirdStuff({ styles, children }) {
  return children(styles[0]());
}
```

```JS
<WeirdStuff
  styles={[
    () => ({
      color: "green"
    })
  ]}
>
  {(css) => {
    return (
      <td
        css={{
          fontSize: 21,
          ...css
        }}
      >
        1
      </td>
    );
  }}
</WeirdStuff>
```

It works.

**Comment by andreyvital** [comment] 2019-08-07 16:03
Look like it's the Node.js version—was using 11 and now with node @ 12.8 it is working.

**Comment by Andarist** [comment] 2019-10-26 13:22
Glad you have figured this out! Closing this as the issue got resolved.

**Closed by Andarist** 2019-10-26 13:22 UTC
Labels: bug, needs triage

**Comment by Iuriy-Budnikov** [comment] 2019-11-23 17:01
Update to 12 doesn't resolve an issue

**Comment by Andarist** [comment] 2019-11-23 17:22
Please create repro case and then please create a new issue for it.

**Comment by danvim** [comment] 2020-01-07 18:02
@Andarist  I'm currently having the same issue with Firefox (Chrome is working) with Next.js. And only the first element in DOM using Emotion is having this issue. I'm sorry, because I am not directly using Emotion, but rather, through Theme UI (Its creator has also made Rebass and Styled System).

I posted an issue on their repo: https://github.com/system-ui/theme-ui/issues/538. And I have an example repo at: https://github.com/danvim/theme-ui-problem in the `pure-theme-ui` branch as a minimum reproducible example. This must bother you since my "minimum example" is not so minimal because its not directly using Emotion.

The author believes that the problem does not lie in Theme UI, since it did not deal with SSR. It's curious because the problem only exist on Firefox for a fresh render, i.e. Enter address in URL or F5, and not through `<Link>`.

**Comment by Andarist** [comment] 2020-01-08 23:36
@danvim when I run this repro I get 404 page when I enter http://localhost:3000/ - is this expected?

**Comment by danvim** [comment] 2020-01-09 06:50
@Andarist Please use Firefox and Chrome for testing. The url should be `/theme_ui`. I'm sorry, since most of the info is in my other issue.

**Comment by Andarist** [comment] 2020-01-09 10:42
I'm afraid I can't reproduce this on my machine 😢 If you join our Slack and ping me there I could try to help you out debug this remotely though.

**Comment by danvim** [comment] 2020-01-10 15:10
Thanks again @Andarist so much for your time remote debugging my case.

To any reading this, apparently, the browser specific regex for extracting the React component name in `process.env.NODE_ENV !== 'production'` failed for my Firefox version and OS:

I'm using Ubuntu 18.04 and this is what I've gotten from `apt-cache showpkg firefox`.

```
Package: firefox
Versions: 
71.0+build5-0ubuntu0.18.04.1 (/var/lib/apt/lists/hk.archive.ubuntu.com_ubuntu_dists_bionic-updates_main_binary-amd64_Packages) (/var/lib/apt/lists/security.ubuntu.com_ubuntu_dists_bionic-security_main_binary-amd64_Packages) (/var/lib/dpkg/status) 
```

This line targets Safari and Firefox:

https://github.com/emotion-js/emotion/blob/117c6e42687cdcb773153f7400c5a430f228aa73/packages/core/src/jsx.js#L161

For my `error.stack` was:

```
jsx@http://localhost:3000/_next/static/development/pages/css-hash.js?ts=1578666104986:442:17
jsx$$1@http://localhost:3000/_next/static/development/pages/css-hash.js?ts=1578666104986:2777:60
CssHash@http://localhost:3000/_next/static/development/pages/css-hash.js?ts=1578666104986:23:62
renderWithHooks@http://localhost:3000/_next/static/development/dll/dll_d6a88dbe3071bd165157.js?ts=1578666104986:16511:27
mountIndeterminateComponent@http://localhost:3000/_next/static/development/dll/dll_d6a88dbe3071bd165157.js?ts=1578666104986:19045:13
beginWork$1@http://localhost:3000/_next/static/development/dll/dll_d6a88dbe3071bd165157.js?ts=1578666104986:20413:16
beginWork$$1@http://localhost:3000/_next/static/development/dll/dll_d6a88dbe3071bd165157.js?ts=1578666104986:26007:14
performUnitOfWork@http://localhost:3000/_next/static/development/dll/dll_d6a88dbe3071bd165157.js?ts=1578666104986:24946:12
workLoopSync@http://localhost:3000/_next/static/development/dll/dll_d6a88dbe3071bd165157.js?ts=1578666104986:24922:22
performSyncWorkOnRoot@http://localhost:3000/_next/static/development/dll/dll_d6a88dbe3071bd165157.js?ts=1578666104986:24521:11
scheduleUpdateOnFiber@http://localhost:3000/_next/static/development/dll/dll_d6a88dbe3071bd165157.js?ts=1578666104986:23949:28
updateContainer@http://localhost:3000/_next/static/development/dll/dll_d6a88dbe3071bd165157.js?ts=1578666104986:27354:15
legacyRenderSubtreeIntoContainer/<@http://localhost:3000/_next/static/development/dll/dll_d6a88dbe3071bd165157.js?ts=1578666104986:27779:22
unbatchedUpdates@http://localhost:3000/_next/static/development/dll/dll_d6a88dbe3071bd165157.js?ts=1578666104986:24684:12
legacyRenderSubtreeIntoContainer@http://localhost:3000/_next/static/development/dll/dll_d6a88dbe3071bd165157.js?ts=1578666104986:27778:21
hydrate@http://localhost:3000/_next/static/development/dll/dll_d6a88dbe3071bd165157.js?ts=1578666104986:27842:10
renderReactElement@http://localhost:3000/_next/static/runtime/main.js?ts=1578666104986:7401:28
_callee4$@http://localhost:3000/_next/static/runtime/main.js?ts=1578666104986:7561:31
tryCatch@http://localhost:3000/_next/static/runtime/main.js?ts=1578666104986:10357:40
invoke@http://localhost:3000/_next/static/runtime/main.js?ts=1578666104986:10583:30
defineIteratorMethods/</prototype[method]@http://localhost:3000/_next/static/runtime/main.js?ts=1578666104986:10409:21
asyncGeneratorStep@http://localhost:3000/_next/static/runtime/main.js?ts=1578666104986:248:24
_next@http://localhost:3000/_next/static/runtime/main.js?ts=1578666104986:270:27
_asyncToGenerator/</<@http://localhost:3000/_next/static/runtime/main.js?ts=1578666104986:277:12
F@http://localhost:3000/_next/static/runtime/main.js?ts=1578666104986:1802:28
_asyncToGenerator/<@http://localhost:3000/_next/static/runtime/main.js?ts=1578666104986:266:12
_doRender@http://localhost:3000/_next/static/runtime/main.js?ts=1578666104986:7575:20
doRender@http://localhost:3000/_next/static/runtime/main.js?ts=1578666104986:7503:20
_callee2$@http://localhost:3000/_next/static/runtime/main.js?ts=1578666104986:7282:20
tryCatch@http://localhost:3000/_next/static/runtime/main.js?ts=1578666104986:10357:40
invoke@http://localhost:3000/_next/static/runtime/main.js?ts=1578666104986:10583:30
defineIteratorMethods/</prototype[method]@http://localhost:3000/_next/static/runtime/main.js?ts=1578666104986:10409:21
asyncGeneratorStep@http://localhost:3000/_next/static/runtime/main.js?ts=1578666104986:248:24
_next@http://localhost:3000/_next/static/runtime/main.js?ts=1578666104986:270:27
_asyncToGenerator/</<@http://localhost:3000/_next/static/runtime/main.js?ts=1578666104986:277:12
F@http://localhost:3000/_next/static/runtime/main.js?ts=1578666104986:1802:28
_asyncToGenerator/<@http://localhost:3000/_next/static/runtime/main.js?ts=1578666104986:266:12
_render@http://localhost:3000/_next/static/runtime/main.js?ts=1578666104986:7303:18
render@http://localhost:3000/_next/static/runtime/main.js?ts=1578666104986:7254:18
_callee$@http://localhost:3000/_next/static/runtime/main.js?ts=1578666104986:7235:19
tryCatch@http://localhost:3000/_next/static/runtime/main.js?ts=1578666104986:10357:40
invoke@http://localhost:3000/_next/static/runtime/main.js?ts=1578666104986:10583:30
defineIteratorMethods/</prototype[method]@http://localhost:3000/_next/static/runtime/main.js?ts=1578666104986:10409:21
asyncGeneratorStep@http://localhost:3000/_next/static/runtime/main.js?ts=1578666104986:248:24
_next@http://localhost:3000/_next/static/runtime/main.js?ts=1578666104986:270:27
```

**Comment by erikdstock** [comment] 2020-10-26 22:18
I think I'm finding this issue affects me on Safari in development mode as well.
Using @emotion/core@10.0.35, theme-ui, nodejs 12.14.1

**Comment by Andarist** [comment] 2020-10-26 22:55
@erikdstock you must understand that this is not an appropriate issue report. Would you be fond of such a problem report at your day job? I kinda bet that you would ask for more details and preferably for a **repro steps**.

**Comment by shehi** [comment] 2021-08-09 15:05
Try importing dynamically.
