### ISSUE TITLE
regexp not work in IE

### ISSUE THREAD

**Issue by degr** [emotion-js/emotion#1228] opened 2019-02-13 12:14 UTC
Hello, my application not work in IE. It fail with error message: 

SCRIPT1012: Expected '/'

Error happen in:
node_modules/@emotion/stylis/src/stylis.min.js
IE can't parse this regular expression:
/[^]*?(:[rp][el]a[\w-]+)[^]*/
IE version: 11.904.16299.0

As I can see, regex101 shows that this regexp valid only for js parser, and invalid for others (php, golang and python - [https://regex101.com/r/Fkr0Ji/1](https://regex101.com/r/Fkr0Ji/1) )
Please replace it with something valid, or ask Bill Gates why he chose non-js regexp engine in browser.

**Comment by FezVrasta** [comment] 2019-08-27 15:55
Would any of you able to send a PR to fix the regexp? It would be very helpful

**Comment by Andarist** [comment] 2019-08-27 19:48
Could u prepare a small site with the issue reproduced? Can't reproduce it inside IE11's console.

**Comment by degr** [comment] 2019-08-29 14:27
Currently I can't reproduce it, may be it was related to build configuration. Also, I can't remember how did I solve this issue, because your library was in list of dependencies in react-select. But I definitely sure, that this problem was not my imagination, and I remember that I debug it on code without source maps and discover this problem on this line with this regexp.

**Comment by FezVrasta** [comment] 2019-08-29 21:12
Was IE maybe running in quirks mode?

**Comment by Andarist** [comment] 2019-11-01 23:31
Until we get exact repro steps for this I have to close this issue to keep the issue tracker clean. Thank you for your understanding.

**Closed by Andarist** 2019-11-01 23:31 UTC
Labels: bug, needs triage
