### ISSUE TITLE
React type pollution in generated .d.ts files

### ISSUE THREAD

**Issue by elierotenberg** [emotion-js/emotion#1676] opened 2019-12-06 13:22 UTC
**Current behavior:**

Currently, having `@emotion/core` as a dev-dependency forcefully includes `<reference types="@emotion/core" />` in generated `.d.ts` files, even when it isn't directly used.

In my current project, `@emotion/core` is required by a dev-dependency on `@storybook/addon-actions`:

```
$ npm ls "@emotion/core"
...
`-- @storybook/addon-actions@5.2.8
  `-- @storybook/theming@5.2.8
    `-- @emotion/core@10.0.22 
```

During compilation of production files (hence excluding storybook-related files), whenever I directly import either `Context` or `useContext` from `react`, a reference is added to `@emotion/core`. This doesn't happen when I import `React` from `react` and then use `React.createContext` or `React.useContext`.

Example below:

1. Import `React` and then use `React.createContext` (no bug):

```ts
// Test-with-import-React.ts (source)
import React from "react";

const MyContext = React.createContext(null);

export { MyContext };

// Test-with-import-React.d.ts (generated)
import React from "react";
declare const MyContext: React.Context<null>;
export { MyContext };
```

2. Import `createContext` directly (bug):

```ts
// Test-with-import-createContext.ts (source)
import { createContext } from "react";

const MyContext = createContext(null);

export { MyContext };

// Test-with-import-createContext.d.ts (generated)
/// <reference types="react" />
/// <reference types="@emotion/core" />
declare const MyContext: import("react").Context<null>;
export { MyContext };

```
**To reproduce:**
1. Add `@emotion/core` as a dev-dependency
2. Compile a `ts` file in which `import { createContext } from "react";` is used

**Expected behavior:**

No `<reference types="@emotion/core" />` should be emitted unless `@emotion/core` or a module that depends on it is included in the build

**Environment information:**

- `react` version: 16.12.0
- `emotion` version: 10.0.2
-  `typescript` version: 3.7.3

**Comment by Andarist** [comment] 2019-12-07 13:33
I believe this is a duplicate of https://github.com/emotion-js/emotion/issues/1257 and we plan to fix this in upcoming v11.

**Closed** 2019-12-08 15:05 UTC
Labels: TypeScript, bug
