### ISSUE TITLE
Alternative to Babel for NextJS 11.1 SWC toolchain

### ISSUE THREAD

**Issue by osdiab** [emotion-js/emotion#2467] opened 2021-08-31 21:52 UTC
**The problem**

I currently rely on the emotion babel config to add CSS prop support to my app. However, NextJS just released Next 11.1, where they use SWC instead of Babel to transpile JS. This is opt-in on their end, so I can just keep using Babel and not have a problem, but I would like to use that faster toolchain and still reap the syntactic niceness of the Emotion CSS prop without adding the JSX pragma everywhere.

**Proposed solution**

Some alternative that works with SWC for supporting the CSS prop; maybe a webpack plugin, since that should still be usable?

**Alternative solutions**

Just using the JSX pragma, sigh.

**Comment by DavidVaness** [comment] 2021-12-03 16:32
any news on this?

**Comment by Andarist** [comment] 2021-12-03 17:12
I’ve talked with Next maintainers and they plan to port our Babel plugin to Rust and their SWC-based plugin system. So we have to be patient and wait till they manage to do that. You must understand that this is still very early stage for them in this aspect and the plugin system is not publicly available.

**Comment by DavidVaness** [comment] 2021-12-03 17:39
Thank you so much. Would love to see this implemented

**Comment by refactorized** [comment] 2021-12-17 03:10
It wasn't clear to me that their plugin system was still closed - that's an important detail.

**Comment by tony** [comment] 2021-12-26 12:20
Issue for Next's swc support for emotion: https://github.com/vercel/next.js/issues/30804

**Comment by EqualMa** [comment] 2022-03-16 18:11
I have a question that might be stupid. Why do we need a plugin for `emotion`?
I just add `"jsxImportSource": "@emotion/react"` to `compilerOptions` in `tsconfig.json` and it [works](https://github.com/EqualMa/weibo-emoji/blob/3a568868bb24e043a6ae2b08291452a0fa29e708/tsconfig.json#L9). It seems this would also work for `jsconfig.json` in non-typescript projects. Am I missing something?

**Comment by srmagura** [comment] 2022-03-16 18:25
@EqualMa Not a stupid question and thanks for bringing this up.

The [Next documentation](https://nextjs.org/docs/advanced-features/compiler#importsource) states that `"jsxImportSource"` works in both `tsconfig.json` and `jsconfig.json`. I can personally confirm that it works with `tsconfig.json`. 

When using the modern JSX transform (the default in recent versions of Next), setting `jsxImportSource` is all that's needed for the `css` prop to work. This is enough for the vast majority of users.

`@emotion/babel-plugin` has some extra goodies like the ability to use components as selectors. If you need any of these features, you can still use a custom `.babelrc` with Next. The only downside is compilation will be slower, though there may not be much difference if type checking is the bottleneck.

So it would be cool to have an Emotion swc plugin with the same functionality as `@emotion/babel-plugin`, but that shouldn't be something that anybody truly needs.

@Andarist Seems like this issue can be closed. Do you agree?

**Comment by Andarist** [comment] 2022-03-17 18:08
> So it would be cool to have an Emotion swc plugin with the same functionality as @emotion/babel-plugin, but that shouldn't be something that anybody truly needs.

The plugin also provides some other goodies like auto labels, source maps, and some **very minor** optimizations (those are on the verge of micro-optimizations though so I wouldn't really call this a strong argument). 

Emotion plugin has been merged to Next 20 days ago~: https://github.com/vercel/next.js/pull/34687 . You can try looking there into how you can actually use it today (I think it's possible using their canary releases). As long as that plugin is written and maintained by the Next team - you should report issues/bugs/etc there and not here.

**Closed by Andarist** 2022-03-17 18:08 UTC
Labels: feature request, needs triage

**Comment by tianhuil** [comment] 2022-04-05 04:36
It looks like emotion is working as an experimental feature.  You have to `next.config.js` to

```js
const nextConfig = {
  reactStrictMode: true,
  experimental: {
    emotion: true,
  },
}

module.exports = nextConfig
```

I can confirm this works with `next@12.1.4`.  See this [merged PR](https://github.com/vercel/next.js/pull/34687/files#diff-21b741d57995c3ab8b9211b17e2617c26829addf58be9280fdf8112817aab993)

**Comment by mcrowder65** [comment] 2022-04-14 21:31
@tianhuil but looks like we may need to wait until nextjs team ports this plugin to @swc/core?

**Comment by fforres** [comment] 2022-06-27 22:20
(Looks like their next-swc is not public ATM https://github.com/vercel/next.js/blob/canary/packages/next-swc/crates/core/Cargo.toml#L2-L5)

**Comment by Andarist** [comment] 2022-06-28 07:07
> Are they keen on allowing for a non-nextjs-specific access to the plugin? Might not be a priority as it might drive folks away from using next.js?

I assume that the goal is to make this usable outside of Next but I might be mistaken.

**Comment by IvanRodriCalleja** [comment] 2022-06-28 16:21
@fforres I created a emotion plugin with a `next-swc` that you can use outside `next`

https://www.npmjs.com/package/emotion-swc-plugin

**Comment by fforres** [comment] 2022-06-28 20:15
@IvanRodriCalleja yes! This is awesome, i was clearing my afternoon to take a stab at this 🙏

**Comment by fforres** [comment] 2022-06-28 20:28
@IvanRodriCalleja do you have a repository where you are doing that work? 🙏

**Comment by IvanRodriCalleja** [comment] 2022-06-29 08:58
@fforres I added an example: https://github.com/IvanRodriCalleja/emotion-swc-plugin/tree/main/exampes/with-node
This is with node but the config is the same for a `.swcrc`

**Comment by IvanRodriCalleja** [comment] 2022-07-01 15:57
I don't think you need to configure transform option because you are already enabling emotion in the `next` config that you are linking to `next/jest`. With this approach you are using babel for transpilation and no `SWC`
