### ISSUE TITLE
NPM Package down?

### ISSUE THREAD

**Issue by riccardolardi** [emotion-js/emotion#1961] opened 2020-08-06 08:48 UTC
[https://www.npmjs.com/package/@emotion/stylis](https://www.npmjs.com/package/@emotion/stylis) timing out... this is breaking my dependency chain. Any hint on this?

**Comment by dcoxall** [comment] 2020-08-06 09:23
I'm getting the same issue with `@emotion/memoize` which is now blocking builds for us. NPM is returning a 404 on `https://registry.npmjs.org/@emotion/memoize/-/memoize-0.7.4.tgz`

**Comment by voidale** [comment] 2020-08-06 09:25
https://status.npmjs.org/

**Comment by bmtdh** [comment] 2020-08-06 09:26
Also experiencing this for this package, preventing application deployments at present

**Comment by riccardolardi** [comment] 2020-08-06 09:26
@dcoxall @voidale thanks I hope it's fixed soon

**Comment by Andarist** [comment] 2020-08-06 11:21
Closing this issue as it's not caused by us. Please track the linked npm's status page to check when this gets resolved.

**Closed by Andarist** 2020-08-06 11:21 UTC
Labels: bug, needs triage
