### ISSUE TITLE
Can't pass array to css prop

### ISSUE THREAD

**Issue by ruifortes** [emotion-js/emotion#1629] opened 2019-11-13 18:42 UTC
Hi.
I'm having trouble passing an array to css prop.
This is the webpack message: "Module not found: Error: Can't resolve '@emotion/css' in ..."

Can someone try to reproduce it? Is this a bug?
Here's a sample:

```
import React from 'react'
import ReactDOM from 'react-dom'
import {css} from '@emotion/core'

function Test() {
  var c1 = css`color: hotpink;`
  var c2 = css`background-color: lightgray;`
  var c3 = [c1, c2] 

  return <div css={c3}>OLA</div> // this works fine

  //   return <div css={[c1, c2]}>OLA</div> // this one doesn't work
}

ReactDOM.render(
  <Test/>,
  document.getElementById('root')
)

```

Thanks

**Comment by FezVrasta** [comment] 2019-11-13 18:57
Looking by your code snippet, both should work (or don't), may you provide a CodeSandbox example like explained in the issue template please?

**Comment by ruifortes** [comment] 2019-11-13 19:15
I don't know how to user babel plugins in codesandbox.
It works fine with the pragma but I'm using @emotion/babel-preset-css-prop preset

https://codesandbox.io/s/dazzling-benz-39frt?fontsize=14&hidenavigation=1&theme=dark

**Comment by FezVrasta** [comment] 2019-11-13 19:32
Feel free to prepare a small GitHub repository where the issue can be reproduced. Otherwise maybe you could wait for some of the maintainers to take a look at the issue and see if they can recognize this kind of problem, but it's gonna take some time.

**Comment by Andarist** [comment] 2019-11-13 20:52
Using `pnpm` can be a "culprit" here - we'd like to of course fix it, but to make it easier for us we'd really appreciate a repro case.

**Comment by ruifortes** [comment] 2019-11-21 12:06
Yes, it seams pnpm symlinks might be messing thing up a little.
Heres a link to the test repo: https://github.com/ruifortes/issues_emotion-pnpm

**Comment by Andarist** [comment] 2019-11-22 23:29
Ok, I see the problem. I have a piece of bad news and a piece of good news - the bad news is that we are unable to fix it, the good news is that we have already fixed it in https://github.com/emotion-js/emotion/pull/1600 😉 The fix is going to only hit upcoming v11 though, we can't easily backport it to v10. 

v11 is very much usable (this change has not been released yet, but if you like - I can do it) and changes since v10 are minor (and we don't plan to introduce major breaking changes anyway) but depending on the size of your project upgrade might take from 0 to some time (before final release we plan to prepare codemods which will help to migrate automatically, but they are not ready yet).

A workaround for v10 would be to do this:
```js
import {css} from '@emotion/core'

<div css={css([c1, c2])}>OLA</div> 
```

**Comment by Andarist** [comment] 2019-11-29 21:32
Closing because there is not much we can do about this in v10 as described above. I hope you understand.

**Closed by Andarist** 2019-11-29 21:32 UTC
Labels: bug, needs more information
