### ISSUE TITLE
Relaxed versions?

### ISSUE THREAD

**Issue by daveisfera** [emotion-js/emotion#1497] opened 2019-09-11 15:46 UTC
**Current behavior:**
Specific versions of `@emotion/hash` and `@emotion/memoize` are used

**To reproduce:**
View `package.json`

**Expected behavior:**
`^` is used so the latest compatible release can be used (i.e reduce the chance that multiple versions of the modules will be installed)

**Environment information:**
- `react` version: 16.9.0
- `emotion` version: 9.2.12

**Comment by FezVrasta** [comment] 2019-09-11 17:59
This looks like a duplicate of https://github.com/emotion-js/emotion/issues/1471

**Closed by FezVrasta** 2019-09-11 17:59 UTC
Labels: bug, needs triage

**Comment by daveisfera** [comment] 2019-09-11 20:01
Fixing #1497 would address my request if `^` is used as part of that, but technically this is a separate request to stop using specific versions regardless of whether `0.x.y` or `x.y.z` is used
