### ISSUE TITLE
@emotion/babel-preset-css-prop creating duplicate props causing app to not work on IE

### ISSUE THREAD

**Issue by patricklai8k** [emotion-js/emotion#1428] opened 2019-07-05 15:21 UTC
**Current behavior:**

Our app is not loading in IE11 because it complains about duplicate props not being allowed in strict mode.

These props are only appearing when we use babel-preset-css-prop
```
var ItemLinkStyle = Object(_providers_using_app_context__WEBPACK_IMPORTED_MODULE_5__["default"])(_styles_js__WEBPACK_IMPORTED_MODULE_8__["Link"].withComponent('a', {
  target: "e3pn35d0",
  label: "ItemLinkStyle",
  target: "e3pn35d0",
  label: "ItemLinkStyle"
}));
```
ItemLinkStyle comes from a node_module, but this issue persists whether or not the node modules uses the preset or just regular transform-jsx

and it looks to happen with any component that uses `withComponent` api

**Expected behavior:**

Would expect that there be no duplicate props.

**Environment information:**

- `react` version: 16.6.0
- `emotion` version: 10.0.10
- `@emotion/babel-preset-css-prop` version: 10.0.14

**Comment by Andarist** [comment] 2019-07-06 21:49
Could u prepare a repository with the issue reproduced?

**Comment by tomjschuster** [comment] 2019-07-24 21:41
I was running into the same issue until I realized I hadn't removed `emotion` from plugins in my babel config as described in the babel-preset-css-prop [documentation](https://github.com/emotion-js/emotion/tree/v10.0.6/packages/babel-preset-css-prop#usage).

This was my `.babelrc` when I encountered the error `Multiple definitions of a property not allowed in strict mode` in Internet Explorer:
```json
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react",
    "@emotion/babel-preset-css-prop"
  ],
  "plugins": [
    "emotion"
  ]
}
```
removing `"emotion"` from plugins solved the problem for me:
```json
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react",
    "@emotion/babel-preset-css-prop"
  ]
}
```

**Comment by lasseborly** [comment] 2019-09-18 11:39
I'm encountering the same problem but can't really replicate in a separate repository. We also use styled-system.

**Comment by Andarist** [comment] 2019-10-27 12:39
Closing this because we have not received a runnable repro case. If you manage to deliver such I can take a look at this then.

**Closed by Andarist** 2019-10-27 12:39 UTC
Labels: bug, needs triage
