### ISSUE TITLE
Error triying to use emotion on a Gatsby project.

### ISSUE THREAD

**Issue by gabrandalisse** [emotion-js/emotion#2143] opened 2020-11-28 21:12 UTC
**Current behavior:**

When I try to run gatsby develop it give me this error

`WebpackError: The @emotion/core package has been renamed to @emotion/react. Please import it like this import { jsx } from @emotion/react`

But I have installed the emotion/core and the emotion/react my imports on the components are:
```
import React from 'react';
import { Link } from 'gatsby';
import Navegacion from './navegacion';
import { jsx, css } from '@emotion/react';
```

**To reproduce:**

https://codesandbox.io/s/emotion-issue-template-forked-7su4k?file=/src/navegacion.js

1. run gatsby new project-name
2. npm i @emotion/styled @emotion/react gatsby-plugin-emotion
3. try to create a styled component

**Expected behavior:**

Expected behavior? I hope it works as it should, how it worked in older versions. 

**Environment information:**

```
"dependencies": {
    "@emotion/core": "^11.0.0",
    "@emotion/react": "^11.1.1",
    "@emotion/styled": "^11.0.0",
    "gatsby": "^2.26.1",
    "gatsby-image": "^2.5.0",
    "gatsby-plugin-emotion": "^4.5.0",
    "gatsby-plugin-manifest": "^2.6.1",
    "gatsby-plugin-offline": "^3.4.0",
    "gatsby-plugin-react-helmet": "^3.4.0",
    "gatsby-plugin-sharp": "^2.8.0",
    "gatsby-source-filesystem": "^2.5.0",
    "gatsby-transformer-sharp": "^2.6.0",
    "prop-types": "^15.7.2",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-helmet": "^6.1.0"
```

**Comment by Andarist** [comment] 2020-11-29 10:32
Please create a runnable repro case for this - ideallym the project should be already setup and I could see the error right after executing a command like `yarn && yarn start`

**Comment by gabrandalisse** [comment] 2020-11-30 01:07
1. You need install Gatsby on your pc.
2. Fork this project https://github.com/gabrandalisse/bienesraices-client
3. Install all dependences, npm install it should install @emotion/core @emotion/react @emotion/styled
4. Run gatsby develop
5. See the error.
In src/components/ are the imports of emotion.

**Comment by Andarist** [comment] 2020-11-30 11:13
The `gatsby-plugin-emotion` is still using Emotion 10. There is a prerelease version supporting Emotion 11 - you could try to use it: 5.1.0-next.0 .

**Comment by Cretezy** [comment] 2020-11-30 16:06
After moving to `gatsby-plugin-emotion@5.1.0-next.0` and using `@emotion/react@11.1.1`, I'm getting the following:

```
TypeError: can't access property "type", parent is null

node_modules/@emotion/cache/dist/emotion-cache.browser.esm.js:69
```

![image](https://user-images.githubusercontent.com/2672503/100633471-217e3a00-32fc-11eb-8c46-f4e374ed530e.png)

**Comment by Andarist** [comment] 2020-11-30 22:57
Please push out your changes and ensure that you can reproduce on a fresh copy of your repository. If you do that and the error still occurs then please ping me so I could take a look.

**Comment by timmywil** [comment] 2020-12-09 19:51
I also encountered this error when trying to upgrade, but when I went to try to reproduce it in a fresh repo everything seemed fine. I was able to debug the issue and narrow it down to something more specific.

See https://codesandbox.io/s/charming-chebyshev-h9dtw

Here's some sample code:

```js
<Global
  styles={css`
    @media (min-width: 300px) {
      .header:after {
        content: '';
      }
    }
  `}
/>
```

In the above example, the error is thrown when any `element:pseudo` selector is added to a media query within styles passed to `<Global />`. While each of the concepts are common, it's possible this didn't show up in tests because it requires a certain combination of use cases. But this *does* seem to be a regression.

Note that if you use `&` for the pseudo, this error does not show up:

```js
<Global
  styles={css`
    @media (min-width: 300px) {
      .header {
        &:after {
          content: '';
        }
      }
    }
  `}
/>
```

/cc @Andarist

**Comment by Andarist** [comment] 2020-12-10 08:48
Thank you for the repro case - I will take care of this 🔜 

I've created a simpler sandbox for myself here: https://codesandbox.io/s/floral-rain-x5s4n?file=/src/App.js

**Comment by alessbell** [comment] 2020-12-11 02:36
Saw this as well while upgrading my Gatsby app and created a minimal reproduction of the issue as I encountered it: https://codesandbox.io/s/lingering-dust-7urbt?file=/src/App.tsx:356-431

**Comment by Andarist** [comment] 2020-12-20 09:42
Fix is on the way https://github.com/emotion-js/emotion/pull/2180

**Closed** 2020-12-20 23:19 UTC
Labels: bug, needs triage

**Comment by gabrandalisse** [comment] 2020-12-21 20:47
My problem was solved on the update of the gatsby plugin, thanks!
