### ISSUE TITLE
Ability to insert styles at a specific position in <head>

### ISSUE THREAD

**Issue by jdb8** [emotion-js/emotion#2037] opened 2020-10-08 07:00 UTC
**The problem**

I see that `@emotion/cache` [provides a `container` option](https://emotion.sh/docs/@emotion/cache#container), which seems like it's useful for having some control over the DOM element that emotion inserts its `<style>` nodes into. Unfortunately, I can't find a way to use this for my purpose, which is to control the position of the inserted nodes *in the document head*.

The reason I need this is to have more fine-grained control over rule ordering in a page that has existing styles (which are sadly often composed with the newer Emotion-generated classnames). I'd like Emotion (both on the server and client) to insert all of its `<styles>` (both those initially on the page as well as those dynamically inserted later on) at a specific position in the `<head>`.

Initially I thought I could use the `container` option, but that seems to have two problems here:

* it deals only with nesting *inside* a container, not adjacent to, and...
* it doesn't seem like there are any compatible container elements that accept `<style>` children in the `<head>`

Together, these two issues make it hard to find a way to do what I want here with any existing Emotion apis.

**Proposed solution**

Webpack's `style-loader` [provides an `insert` option](https://webpack.js.org/loaders/style-loader/#insert) which can be given a function to be run in order to determine the position of any inserted styles. Something like this might work here too.

**Alternative solutions**

Another option might be to introduce a more flexible version of `container` - not a full function like `style-loader`, but an `insertAdjacentTo`, `replaceCommentWith` or something similar to allow for more control over the placement?

**Additional context**

Also, based on my problem statement - if there's any existing way to do what I want in Emotion 10, it goes without saying that I'd be very grateful to hear so :)

**Comment by Andarist** [comment] 2020-10-08 08:53
> it doesn't seem like there are any compatible container elements that accept <style> children in the <head>

That's not quite true - probably some validators might yell at you, but all browsers supports div elements within the head. 

> Also, based on my problem statement - if there's any existing way to do what I want in Emotion 10, it goes without saying that I'd be very grateful to hear so :)

It's not possible with Emotion 10 and we do not plan to introduce such an option. However, Emotion 11 - which is just around the corner - has a new `prepend` option that should fix your problem. Yes - it's a boolean so either your styles are appended or prepended to the container but I don't think much more control is needed over this.

**Comment by jdb8** [comment] 2020-10-08 20:38
>That's not quite true - probably some validators might yell at you, but all browsers supports div elements within the head.

I had tried with a `<div>` in the head but saw some weird-looking behaviour where Chrome would show all subsequent `<head>` elements as if they were in the `<body>` (when looking at the elements tab in dev tools) - it was unclear if this was just a quirk of devtools or would actually change behaviour for browsers loading the page (or other scripts making assumptions about where elements are located in the page). After posting this issue, I did start playing around with using a `meta` tag as a container (!) and sure enough it seems to work in the browsers I tested, without the same quirk (but feels even weirder given that `meta` is a [void element](https://html.spec.whatwg.org/multipage/syntax.html#void-elements) in the spec 😱 

I'll probably stick with the meta approach - at least until I run into any insurmountable issues - since it seems to work and lets me hydrate to that container, but it's good to hear that Emotion 11 will offer a bit more control. I suppose your suggestion with the Emotion 11 `prepend` boolean would be to stick with `document.head` but choose to `prepend`, which would ensure that all emotion tags would end up at the start of `<head>` - am I understanding that correctly?

**Comment by Andarist** [comment] 2020-10-08 20:41
> I suppose your suggestion with the Emotion 11 prepend boolean would be to stick with document.head but choose to prepend, which would ensure that all emotion tags would end up at the start of <head> - am I understanding that correctly?

Yes, pretty much that 😃

**Comment by gregjacobs** [comment] 2020-10-31 18:09
I have another use case for this where we need Emotion's CSS classes to have lower specificity than a user's own CSS classes. We're building a library using Emotion where we want a user's CSS classes to be able to override the styles of our library components.

I noticed that the `StyleSheet` class (inside `@emotion/sheet`) has a `before` property, initially assigned to `null`, that could easily be provided as an option to the constructor instead. 

One could provide `head.firstElementChild` as the `before` option in this case to prepend Emotion's `<style>` tag inside the `<head>`. This new option would also give the flexibility to place Emotion's `<style>` tag anywhere in the `<head>` too relative to another element. Thinking that the interface could be as simple as:

```ts
import { createEmotion } from '@emotion/create-emotion';

const emotion = createEmotion({
    container: document.head,
    insertBefore: document.head.firstElementChild
});
```

Is this a possible change to make in v10? If so, I'd be happy to submit a PR.

**Comment by Andarist** [comment] 2020-10-31 18:59
> Is this a possible change to make in v10? If so, I'd be happy to submit a PR.

We do not plan to introduce this to v10. As mentioned - v11 has the `prepend` option that solves this problem and I plan to release v11 as stable on 11.11.2020, so 🔜

**Comment by gregjacobs** [comment] 2020-10-31 20:09
@Andarist kk, thx, good to know that v11 is close then. 

Quick question if you happen to know the answer: are there any performance issues in browsers caused by prepending a `<style>` element and rules in front of existing `<style>` or `<link rel="stylesheet">` elements? (as opposed to appending the rules like the current behavior of Emotion?) 

```html
<html>
    <head>
        <style data-emotion="css"></style>        <!-- exists second -->
        <link rel="stylesheet" href="sheet.css">  <!-- exists first -->
    </head>
    <body>
        ...
    </body>
</html>
```

Do you know of any performance issues either during initial page load, or at a later time by dynamically prepending rules in front of maybe a few thousand existing rules?

**Comment by Andarist** [comment] 2020-10-31 20:32
I don't know about any perf issues regarding that but I haven't really ever thought about this. My intuition would be that there shouldn't be much of a difference between appending & prepending but I might be wrong.

**Comment by gregjacobs** [comment] 2020-10-31 21:35
Ah ok, no worries, I'll try to do some testing and will let you know if I find anything

**Comment by gregjacobs** [comment] 2020-11-10 16:29
@Andarist Did some testing and didn't find any difference in re-render performance in Chrome with prepending, at least in the case that styles are prepended after initial page load. Still need to do a test for initial page load with regular stylesheets + prepending, and in other browsers.

**Comment by gregjacobs** [comment] 2020-11-24 19:28
Does the new `prepend` option in v11 cover this use case?

**Comment by Andarist** [comment] 2020-11-24 19:43
I believe it does - we dont intend to introduce more control over insertion point than what is already provided in v11

**Closed by Andarist** 2020-11-24 19:43 UTC
Labels: feature request

**Comment by oliviertassinari** [comment] 2021-05-31 22:20
@Andarist is the motivation for rejecting the feature in https://github.com/emotion-js/emotion/issues/2037#issuecomment-733193543 lack of bandwidth or concern about the extra complexity involved?

**Comment by Andarist** [comment] 2021-06-01 12:04
@oliviertassinari mainly about the added complexity. We can reconsider this though - the new API (option?) would have to replace `prepend` (it would be deprecated) because maintaining multiple options for a very similar thing is not something that I'd like to do. If you care about this then please start a new issue with the initial proposal for the feature.

**Comment by oliviertassinari** [comment] 2021-06-01 12:27
OK. We might POC around to explore the feasibility of bringing this with a PR. 

At this point, MUI v5 has about 1% of adoption, so we will hear more about the need for this feature as more developers migrate. We have recently seen an interesting use case with Tailwind, where the TW CSS reset needs to apply before MUI but the TW classes after MUI. Sure we could say that, nop don't use TW with MUI but I don't think that it would be the best strategical direction. Better embrace the alternatives options and make the ones you propose more appealing.

**Comment by DominikSerafin** [comment] 2021-12-02 12:55
@Andarist @oliviertassinari, I'm migrating to MUI v5 and this became a bit of a problem for me. My styles insertion order should be like this:

1. Custom reset styles (**not** MUI CSS Baseline)
2. MUI/emotion styles
3. Custom styles (that include overwrites for MUI styles)

Now, this is fairly straightforward during SSR, since I can control where the styles from emotion cache are inserted. However, during CSR there's no way to control where the styles are inserted inside the `<head>` (other than `prepend` option, which doesn't help here).

My workaround was to move styles into `<body>` and use `<div>` `container` for emotion styles, but I'd prefer to keep them in `<head>`.

**Comment by Andarist** [comment] 2021-12-02 13:18
> However, during CSR there's no way to control where the styles are inserted inside the <head> (other than prepend option, which doesn't help here).

Since [this](https://github.com/emotion-js/emotion/pull/2521) got merged in and shipped this statement is no longer true. I'm not sure if this option has been exposed in MUI though - you'd have to look there for an answer to that.

**Comment by DominikSerafin** [comment] 2021-12-02 14:32
@Andarist, I'm using `@emotion/cache@11.6.0` directly (as per [MUI docs](https://mui.com/guides/server-rendering/)), and the `insertionPoint` option works great, thank you!. Although, it seems neither [docs](https://emotion.sh/docs/@emotion/cache) nor [README](https://github.com/emotion-js/emotion/tree/main/packages/cache) have it documented.

---

<details><summary>There's also another somewhat related issue, which probably warrants a new issue in MUI repo (but I don't currently have time to properly submit it with minimal repro, etc.), but just FYI:</summary>
 
Some animations (seems to be from MUI LinearProgress) are still appended at the end of `<head>`, regardless if `prepend`, `container` or `insertionPoint` is configured.

![image](https://user-images.githubusercontent.com/7447244/144439586-b7d3ae42-7ee7-48e7-9018-c370843bd560.png)

@oliviertassinari
</details>

**Comment by Andarist** [comment] 2021-12-02 21:59
Interesting - would love to get a repro case for that, I could then investigate this quickly.
