### ISSUE TITLE
Typescript@beta moduleResolution nodenext strategy breaks @emotion

### ISSUE THREAD

**Issue by noahehall** [emotion-js/emotion#2742] opened 2022-04-30 17:26 UTC
**Current behavior:**
- setting tsconfig.json.moduleResolution = node: everything is fine
- setting tsconfig.json.moduleResolution = nodenext: throws error

```sh
./src/app.tsx 13:2-15:21
[tsl] ERROR in /somedir/nirv/src/app.tsx(13,3)
      TS2307: Cannot find module '@emotion/react/jsx-runtime' or its corresponding type declarations.
```

**Expected behavior:**

- [@emotion works with typescript@beta nodenext moduleResolution strategy](https://www.typescriptlang.org/tsconfig#moduleResolution)

**Environment information:**

- `react` version:18.1
- `@emotion/react` version:18.1
- typescript: beta
- tsc: Version 4.7.0-dev.20220430
- pnpm: 6.32.9

** tsconfig **

```json

{
  "include": ["src"], 
  "exclude": ["src/**/*.test.ts"],
  "compileOnSave": false,
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "alwaysStrict": true,
    "baseUrl": "./", 
    "checkJs": false,
    "esModuleInterop": true,
    "exactOptionalPropertyTypes": false,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "jsx": "react-jsx",
    "jsxImportSource": "@emotion/react",
    "lib": ["dom", "dom.iterable", "esnext"],
    "module": "esnext", 
    "moduleResolution": "nodenext", <-------- breaks @emotion 
    "noFallthroughCasesInSwitch": false,
    "noImplicitAny": true,
    "noImplicitOverride": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noPropertyAccessFromIndexSignature": false,
    "outDir": "dist",
    "paths": {},
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "strict": true,
    "target": "es2017", 
    "typeRoots": ["./src/@types", "./node_modules/@types"]
  }
}
```

**Comment by srmagura** [comment] 2022-05-01 14:43
Thanks for the report, I can confirm this is an issue. Minimal repro: https://github.com/srmagura/emotion-nodenext-repro

**Comment by Andarist** [comment] 2022-05-01 15:01
So the way to fix this would be to add the appropriate `package.json#exports`. This is, sort of, worked on here: https://github.com/preconstruct/preconstruct/pull/435

**Comment by noahehall** [comment] 2022-05-01 18:54
thank you guys! will try the fix shortly

**Comment by srmagura** [comment] 2022-07-11 13:43
This should be fixed by https://github.com/emotion-js/emotion/pull/2819. Will test this once against that PR once it is finalized. [Test repo](https://github.com/srmagura/emotion-2785-test)

**Comment by koistya** [comment] 2022-07-31 21:53
Getting the following error with Emotion `11.10.0` and TypeScript `4.7.4` with `moduleResolutin = NodeNext`:

```
'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.ts(2686)
```

**Comment by koistya** [comment] 2022-07-31 22:47
Testing Emotion.js 11.10.0 with TypeScript 4.7.4 and moduleResolution = NodeNext.
It seems to be working as expected (in [`react-starter-kit`](https://github.com/kriasoft-starter-kit)).

**Comment by Andarist** [comment] 2022-08-01 07:48
Thank you for reporting back about this 🎉

**Closed by Andarist** 2022-08-01 07:48 UTC
Labels: bug
