### ISSUE TITLE
Using emotion 9 and 10 in the same window

### ISSUE THREAD

**Issue by psachs21** [emotion-js/emotion#1347] opened 2019-05-14 21:26 UTC
- `emotion` version: 9.2.12 AND 10.0.10
- `react` version: 16.8.6

**What you did:**

Trying to use an emotion 9 lib within storybook v5.

**What happened:**

Error is thrown on load:

```
Uncaught TypeError: Cannot read property 'length' of undefined
    at serializeStyles (main.3173126555acebfe0d1a.bundle.js:445)
    at css (vendors~main.ad7bd95803918bf0d539.bundle.js:643)
    at Module.keyframes (vendors~main.ad7bd95803918bf0d539.bundle.js:504)
    at Object../node_modules/@storybook/theming/dist/animation.js (vendors~main.ad7bd95803918bf0d539.bundle.js:7687)
    at __webpack_require__ (runtime~main.7b4918090cfe19b7778a.bundle.js:79)
    at Object../node_modules/@storybook/theming/dist/create.js (vendors~main.ad7bd95803918bf0d539.bundle.js:7845)
    at __webpack_require__ (runtime~main.7b4918090cfe19b7778a.bundle.js:79)
    at Object../node_modules/@storybook/theming/dist/index.js (vendors~main.ad7bd95803918bf0d539.bundle.js:8126)
    at __webpack_require__ (runtime~main.7b4918090cfe19b7778a.bundle.js:79)
    at Object../node_modules/@storybook/router/dist/visibility.js (vendors~main.ad7bd95803918bf0d539.bundle.js:7643)
```

See for a little additional detail:

https://github.com/storybooks/storybook/issues/6337

**Expectation:**

Two different webpacks (one with 10.x and one for 9) should behave properly on the same window.

**Comment by FezVrasta** [comment] 2019-05-15 10:26
Would you be able to provide a reproducible example? Possibly on CodeSandbox

**Comment by psachs21** [comment] 2019-05-15 11:51
I'll try to make up an example repo. Unfortunately code sandbox doesn't
support storybook.

**Comment by FezVrasta** [comment] 2019-05-15 11:57
You should be able to use CodeSanbox Containers:
https://hackernoon.com/codesandbox-containers-5864a8f26715

I also found this CodeSandbox that runs Storybook:
https://codesandbox.io/s/github/libetl/storybook-to-codesandbox-test

**Comment by psachs21** [comment] 2019-05-15 12:19
Oh cool. I found an issue for adding support for storybook to codesandbox
so I stopped there. I'll give it a shot.

**Comment by IsenrichO** [comment] 2019-05-15 22:34
I ran into a similar issue recently. Are you using yarn workspaces too by chance?

**Comment by psachs21** [comment] 2019-05-15 23:24
Yep

**Comment by IsenrichO** [comment] 2019-05-16 00:20
Workspaces hoists your dependencies and then leads to an issue because of different major versions of emotion. I had to upgrade to emotion v10 and storybook v5 together unfortunately. Would also be curious if there's a better approach though.

**Comment by qoalu** [comment] 2019-06-05 12:15
Not using workspaces and having the issue as well

**Comment by Andarist** [comment] 2019-10-28 22:10
Closing this because we have not received enough information for a long time to be able to look at this.

**Closed by Andarist** 2019-10-28 22:10 UTC
Labels: needs more information
