### ISSUE TITLE
Can't load font with injectGlobal

### ISSUE THREAD

**Issue by anton-g** [emotion-js/emotion#984] opened 2018-11-02 09:44 UTC
I'm trying to inject global styling so that font faces are available everywhere, but the imported path doesn't seem to be resolved in emotion.

This is what I've attempted so far:
```javascript
import { injectGlobal } from 'emotion';
import MyFont from '../static/fonts/MyFont.eot'

injectGlobal`
  @font-face {
    font-family: MyFont;
    src: url('${MyFont}') format('embedded-opentype');
  }
`
```

Webpack loader:
```json
{
    test: /\.(eot|ttf|woff|woff2)$/,
    exclude: /node_modules/,
    loader: "file-loader"
}
```

This is inserted into the bundle:
```
var data = _taggedTemplateLiteral(["\n  @font-face {\n    font-family: MyFont;\n    src: url(", ") format('embedded-opentype');\n  }\n"]);
```

I would assume that the `src` would point to the font loaded by webpack.
Is this something that isn't supported by emotion or am I doing something wrong? It seems like it would work if I were using `styled-components` instead according to [this issue](https://github.com/styled-components/styled-components/issues/233).

- `emotion` version: 9.2.12
- `react` version: 16.5.2

**Comment by lauchlanc** [comment] 2019-05-03 13:35
You can use the Global component as outlined here: https://emotion.sh/docs/globals

I used it like this:
```
import { Global, css } from "@emotion/core";
import MyFont from "<path/to/font.woff>";

...

const App = () => {
  const styles = css`
    @font-face {
      font-family: "MyFontName";
      src: url(${MyFont}) format("woff"),
    }  
  `;

  ...

  return (
    <>
      ...
      <Global styles={styles} />
      ...
    </>
  )
}
```

As long as your Global component is mounted, the font-face will be available globally.

**Comment by FezVrasta** [comment] 2019-05-03 15:26
Thanks for the help @lauchlanc! I'll close this issue, @anton-g feel free to continue here if more help is needed

**Closed by FezVrasta** 2019-05-03 15:26 UTC

**Comment by mbruggenwirth** [comment] 2019-07-05 21:14
@lauchlanc I found that when you import the like you did `import MyFont from "<path/to/font.woff>";` the font can get distored.
I use Axiforma with your approach and the capital J had a distortion.
When using the regular expression the font was without distortion
`font-family: "MyFontName";
      src: url('<path/to/font.woff>') format("woff"),`

**Comment by lauchlanc** [comment] 2019-07-06 01:19
Fonts can be a bit tricky, are you comparing the font to a photoshop file? If so you might find this useful: https://medium.com/better-programming/improving-font-rendering-with-css-3383fc358cbc.
Overall I can’t see the method used to import the font-face distorting the font inherently, but I might be wrong. Let me know if the link above helps.

**Comment by rishi-cure-fit** [comment] 2019-07-09 08:39
@lauchlanc will this work with create react app project?

**Comment by lauchlanc** [comment] 2019-07-09 12:18
> @lauchlanc will this work with create react app project?

@rishi-cure-fit Emotion works great with CRA. You can check out how to use it here: https://emotion.sh/docs/install

The `<Global />` component also works in CRA, and if you want to import the font file, just remember that it must be within the ./src directory.

Here's the CRA doc for importing fonts: https://facebook.github.io/create-react-app/docs/adding-images-fonts-and-files

**Comment by kanishk-anand-oyo** [comment] 2020-01-16 14:40
Is there a way to make font-face work with` injectGlobal` ? I cannot use` <Global /> ` since we use `emotion` instead of `@emotion/core`

I am trying to include font-face using injectGlobal and it won't download the font-files.

**Comment by lauchness** [comment] 2020-01-16 16:03
There's a link here: https://emotion.sh/docs/emotion#global-styles with an example that injects a custom font. Maybe the issue is in the `src` you're providing?

**Comment by kanishk-anand-oyo** [comment] 2020-01-16 17:32
This is the code snippet

``` 
injectGlobal`
  @font-face {
    font-family: 'Open Sans';
    font-style: normal;
    font-weight: 400;
    src: local('Open Sans Regular'), local('OpenSans-Regular'),
      url(https://fonts.gstatic.com/s/opensans/v15/mem8YaGs126MiZpBA-UFW50bf8pkAp6a.woff2) 
      format('woff2');
  }`
}
```

**Comment by lauchness** [comment] 2020-01-16 18:31
I made a codesandbox and used your snippet. It seems to be working, can you confirm this is what you'd expect?
https://codesandbox.io/embed/dreamy-dawn-uxy1t?fontsize=14&hidenavigation=1&theme=dark

**Comment by balibebas** [comment] 2020-05-28 01:58
> I made a codesandbox and used your snippet. It seems to be working, can you confirm this is what you'd expect?

![Screen Capture_chromium_20200528095550](https://user-images.githubusercontent.com/65664227/83089737-a37d7400-a0c9-11ea-9182-bc70aafc1763.png)

That doesn't look like Open Sans to me...
