### ISSUE TITLE
'css' prop add "styles" attribute to element's class definition

### ISSUE THREAD

**Issue by ScottAgirs** [emotion-js/emotion#1783] opened 2020-03-03 00:59 UTC
After a migration process to V10, `css` prop doesn't behave as expected.

**Current behavior:**
After adding `css` prop the class that is populated adds `styles` attribute to the class styles
![image](https://user-images.githubusercontent.com/11737572/75732338-3cb20f80-5cc0-11ea-9a47-523a2f3c1d82.png)

With `css` added to div like so
![image](https://user-images.githubusercontent.com/11737572/75732196-c7463f00-5cbf-11ea-8290-57cd8a1ac3df.png)

This happens on all elements and it's always the first attribute
**Expected behavior:**

**Environment information:**
```
    "@emotion/babel-preset-css-prop": "^10.0.27",
    "@emotion/core": "^10.0.28",
    "@emotion/styled": "^10.0.27",
    "react": "^16.9.0",
    "next": "^9.2.2",
```

**Comment by ScottAgirs** [comment] 2020-03-03 02:22
Also getting a bunch of `undefined`_s_ in the DOM
![image](https://user-images.githubusercontent.com/11737572/75735962-f82b7180-5cc9-11ea-90d4-7112c996977d.png)

**Comment by Andarist** [comment] 2020-03-13 20:06
Could you prepare a repro case? I suspect that you use our APIs in a wrong way, but can't confirm until I see a runnable repro case.

**Comment by justdanallen** [comment] 2020-03-20 18:49
This isn't helpful, but I'm also seeing this on a project. Need to try to reproduce.

**Comment by Andarist** [comment] 2020-06-12 21:12
Closing this as a runnable repro case has not been provided since March so there is nothing I can do to help here. If you ever prepare a repro case I will gladly take a look at it.

**Closed by Andarist** 2020-06-12 21:12 UTC
Labels: bug
