### ISSUE TITLE
TypeError: stylis.middleware is not a function

### ISSUE THREAD

**Issue by EvgenBabenko** [emotion-js/emotion#2138] opened 2020-11-26 11:52 UTC
**Current behavior:**

After migrate to emotion 11, we have failed tests, please note, that error occurs in v11, in v10 - it's OK.
We use create-react-app, so under the hood cra uses jest for tests
![Screenshot_1](https://user-images.githubusercontent.com/29785853/100347097-8892aa80-2fed-11eb-81b1-0a1a77737b64.jpg)

**Expected behavior:**

Error does't appears

**Environment information:**

- `react` version: 16.13.1
- `@emotion/react` version: 11.0.0
- `@emotion/styled`: "11.0.0"
- `typescript`: "4.0.5",

**Comment by Andarist** [comment] 2020-11-26 19:36
duplicate of https://github.com/emotion-js/emotion/issues/2103

**Closed by Andarist** 2020-11-26 19:36 UTC
Labels: bug, needs triage

**Comment by Andarist** [comment] 2020-12-01 15:24
The fix for this issue has just been released in `stylis@4.0.4`
