### ISSUE TITLE
Please move `emotion-theming` to `@emotion/theming`

### ISSUE THREAD

**Issue by cschroeter** [emotion-js/emotion#1568] opened 2019-10-24 19:37 UTC
```json
 "@emotion/core": "10.0.22",
 "@emotion/styled": "10.0.22",
 "emotion-theming": "10.0.19"
```

This triggers me...

```json
 "@emotion/core": "10.0.22",
 "@emotion/styled": "10.0.22",
 "@emotion/theming": "10.0.19"
```

This is so much better - Please guys change this

**Comment by Andarist** [comment] 2019-10-24 22:15
We might change it in the future, but definitely not right now. It's a super minor thing and doesn't cause any actual problems - we also have other unscoped packages.

Closing this for now as this is not a bug or anything like that and we try to cleanup the issue tracker to actually see what we need to handle sooner than later. Hope you understand.

**Closed by Andarist** 2019-10-24 22:15 UTC
