### ISSUE TITLE
Demo Sandbox link throws `pragma and pragmaFrag cannot be set when runtime is automatic.` error

### ISSUE THREAD

**Issue by Dentrax** [emotion-js/emotion#2670] opened 2022-03-01 20:23 UTC
**Current behavior:**

![Screen Shot 2022-03-01 at 23 22 57](https://user-images.githubusercontent.com/16493751/156243141-0b963833-12cb-4f79-8ff9-9097957615ea.png)

```
SyntaxError
/index.js: pragma and pragmaFrag cannot be set when runtime is automatic.
> 1 | /** @jsx jsx */
    | ^
  2 | import { jsx, css, Global } from "@emotion/react";
  3 | import Title from "./Title";
  4 | import ReactDOM from "react-dom";
ot
[https://codesandbox.io/static/js/sandbox.7e4129f10.js:1:182679]()
./src/sandbox/compile.ts/value/<
[https://codesandbox.io/static/js/sandbox.7e4129f10.js:1:187406]()
value
[https://codesandbox.io/static/js/sandbox.7e4129f10.js:1:187525]()
value
[https://codesandbox.io/static/js/sandbox.7e4129f10.js:1:185777]()
./src/sandbox/compile.ts/e/</<
[https://codesandbox.io/static/js/sandbox.7e4129f10.js:1:186385]()
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.
This error overlay is powered by `react-error-overlay` used in `create-react-app`.
```

**To reproduce:**

1. Visit https://github.com/emotion-js/emotion#demo-sandbox (https://codesandbox.io/s/pk1qjqpw67)
2. See the error

**Expected behavior:**

It should work?

**Environment information:**

macOS 12, Firefox 97.0.1

**Comment by srmagura** [comment] 2022-03-01 20:35
Duplicate of #2637. New sandbox here: https://codesandbox.io/s/emotion-ox3ms2   🙂

**Closed by srmagura** 2022-03-01 20:35 UTC
Labels: bug, needs triage
