### ISSUE TITLE
nest a class selector using the class generated with `css` in Emotion 10

### ISSUE THREAD

**Issue by albertstill** [emotion-js/emotion#1216] opened 2019-02-08 05:22 UTC
In Emotion@9 the below code makes the anchor underlined:

```js
import React from "react";
import { css } from "emotion";

const link = css`
  color: hotpink;
`;

const paragraph = css`
  color: gray;

  .${link} {
    border-bottom: 1px solid currentColor;
  }
`;

export default class App extends React.Component {
  render() {
    return (
      <div>
        <p className={paragraph}>
          Some text with a<a className={link}> link</a>.
        </p>
      </div>
    );
  }
}
```

I appreciate this would work without any code your side because `css` returns a class string. However in Emotion@10 it seems the `css` function does not handle this:

```js
/** @jsx jsx */
import React from "react";
import { css, jsx } from "@emotion/core";

const link = css`
  color: hotpink;
`;

const paragraph = css`
  color: gray;

  .${link} {
    border-bottom: 1px solid currentColor;
  }
`;

export default class App extends React.Component {
  render() {
    return (
      <div>
        <p css={paragraph}>
          Some text with a<a css={link}> link</a>.
        </p>
      </div>
    );
  }
}
```

In Emotion@10 I'd have to walk into the object returned by `css` and assume the `css-` prefix.

```js
const paragraph = css`
  color: gray;

  .css-${link.name} {
    border-bottom: 1px solid currentColor;
  }
`;
```
I appreciate you are encouraging users not to do this sort of [thing](https://5bb1495273f2cf57a2cf39cc--emotion.netlify.com/docs/nested) in Emotion 9, but would I be right in thinking there would be nothing to lose in supporting this in Emotion 10's tagged template function?

This problem arose for me because I'm working on a [`sass-to-emotion`](https://github.com/DomainGroupOSS/sass-to-emotion) codemod, and because it's something that is supported in Sass there exits prod CSS that operates like above.

**Comment by albertstill** [comment] 2019-02-12 23:37
Just to clarify something, I appreciate the selectors are unique in emotion due to the hash and don't need to be nested for specificity reasons. A use case would be that we have conditional classes higher up the DOM tree that change styles of nested elements. For example:

```css
.is-small-agent {
   .agent-photo {
     height: 30px;
   }
}

.agent-photo {
   height: 50px;
 }
```

**Comment by konstantin24121** [comment] 2019-03-14 15:09
We also had this problem because we use nesting to change inner nodes styles in complicated components. This is very strange that SerializedStyles.name return only name without css- prefix

**Comment by pleunv** [comment] 2019-05-15 10:10
If I'm not mistaken `SerializedStyles.name` is not dependable because as soon as it gets combined with an additional style you'll end up with a new className.

**Comment by FezVrasta** [comment] 2019-05-15 10:27
I'm going to close this as dupe of #1217, please continue there.

**Closed by FezVrasta** 2019-05-15 10:27 UTC
Labels: question

**Comment by tiye** [comment] 2023-10-11 07:20
very curious why this feature was deprecated after emotion 9, it's handy in many cases.
