### ISSUE TITLE
Cannot read property '__emotion_real' of undefined

### ISSUE THREAD

**Issue by mjcampagna** [emotion-js/emotion#2284] opened 2021-03-11 22:16 UTC
So, we're seeing this issue occasionally logged from Emotion. The component in question is defined as follows, where `motion.div` is a framer-motion animated element:

```js
const StyledDiv = styled(motion.div)`
  backface-visibility: hidden;
  bottom: 0;
  ...
```

My best guess is that Emotion is trying to do business before framer-motion has made the element available. I don't know whether it would be possible to suppress this noise ... ?

**Comment by Andarist** [comment] 2021-03-11 22:19
Well, it's not really a noise but rather a runtime error - a somewhat serious problem from your perspective.

I can't really know what's happening unless you provide a runnable repro case that I could investigate.

**Comment by mjcampagna** [comment] 2021-03-11 23:01
Unfortunately, it's a private repo for an enterprise application, and it's not consistently reproducible.

**Comment by mjcampagna** [comment] 2021-03-11 23:03
The stack trace on the issue is this: 

```
TypeError: Cannot read property '__emotion_real' of undefined
1
File "webpack:///./node_modules/@emotion/styled/base/dist/emotion-styled-base.browser.esm.js", line 46 col 16 in createStyled
var isReal = tag.__emotion_real === tag;
2
File "webpack:///./app/assets/javascripts/styles/components/Modals/components/Wrapper.tsx", line 10 col 19 in [anonymous]
const StyledDiv = styled(motion.div)`
```

**Comment by mjcampagna** [comment] 2021-03-11 23:12
My best guess at suppressing the error would be:
```
var isReal = tag && tag.__emotion_real === tag
```

Just making sure the tag exists before attempting to access the __emotion_real property?

**Comment by Andarist** [comment] 2021-03-11 23:24
The problem is that you really shouldn't call `styled` on the undefined argument - it's a type error (and thus a runtime error if you break the type contract). So suppressing the error is not really a viable option from my point of view.

**Comment by mjcampagna** [comment] 2021-03-11 23:29
I understand that point of view. But in this case, whether or not `motion.div` is undefined is out of our hands. Is there an improvement to be made here for compatibility with animation libraries such as framer-motion? Or should we simply not use the two libraries on the same element?

**Comment by Andarist** [comment] 2021-03-11 23:40
I suspect that the problem is not really about Emotion but about Frame Motion using Proxy which ain't available in all environments:
https://github.com/framer/motion/blob/ed7ea8783f850b44d08d95c9996bae3cb8f35f28/src/render/dom/motion-proxy.ts#L77

Do you have any data regarding in what browsers do you experience this error?

**Comment by mjcampagna** [comment] 2021-03-11 23:46
Yes. Occurrences include:

Chrome 29 / Win (this one is really no surprise; Chrome 29?!)
Chrome 84 / Win
Chrome 85 / Mac 10.15
Chrome 83 / Win
Chrome 73 / Win
Chrome 23 / Win

And so on ...

**Comment by Andarist** [comment] 2021-03-11 23:53
Heh, given Chrome 80+ pops up here this doesn't sound like a Proxy-problem (or at least there has to be something else to it). There are a lot of things that can happen on the web though - including external browser extensions messing up with stuff, so I wouldn't really be concerned much about it until you receive a real user report about this.

**Comment by mjcampagna** [comment] 2021-03-12 00:02
I mostly agree. Hence my referring to it as "noise" in my original post. I'm likely going to mute the issue in our error logging, as I don't see anything I can do about it in the application layer, apart from using straight up `style` on the component instead of Emotion. Insofar as I can tell, I haven't seen any user impact.

**Comment by Andarist** [comment] 2021-03-12 12:02
Going to close this then - if you ever get a repro case for this then let me know. I'm quite curious regarding what is actually happening there.

**Closed by Andarist** 2021-03-12 12:02 UTC
Labels: bug, needs triage
