### ISSUE TITLE
Nextjs SSR sometimes not rendering styles

### ISSUE THREAD

**Issue by SimplyComplexable** [emotion-js/emotion#1285] opened 2019-03-26 21:11 UTC
- `emotion` 10.0.7:
- `react` 16.8.0:

**Relevant code:**
All the project styles are `styled` components. 
```
export const Span = styled.span`
  color: white;
  background: black;
`;
```

**What you did:**
Server-side rendered the project, including styles.

**What happened:**
Eventually the SSR stops returning any styles, causing a whole-page FOUC. 

**Reproduction:**
 This is a minimal reproduction of the codebase: https://codesandbox.io/s/5xx25mvv1p

**Problem description:**
At first everything works fine. Style tags are rendered inline, as siblings, on the server and then moved to the head on client-side re-render. The problem is that eventually the SSR stops returning any styles, causing whole-page FOUC. 
Unfortunately, the code-base I provided does not replicate this issue, because I can't consistently get it to happen, and haven't been able to track down any specific contributing factor. 
We have several projects, structured this same way, and since the update to emotion 10, all are having this FOUC issue at various points. However Next and React were also updated around the same time so these could definitely be factors or even the cause.
One note is the global styles seem to be consistently returning, just not the styled components.

**Suggested solution:**
The styles consistently return.

**Comment by SimplyComplexable** [comment] 2019-03-26 22:13
<img width="689" alt="Screen Shot 2019-03-26 at 4 10 55 PM" src="https://user-images.githubusercontent.com/8563846/55037007-ed5c5d00-4fe1-11e9-8f60-c7544ae22a32.png">
This is what the SSR html looks like.

**Comment by mountwill** [comment] 2019-03-28 23:04
I'm also experiencing this issue on a SSR production React app, which doesn't use Next.js.

**Comment by jsfowles** [comment] 2019-04-01 15:10
I'm having the same issues as @SimplyComplexable. I'm using:

- `emotion` 10.0.7:
- `react` 16.8.1:

**Comment by hangwoo** [comment] 2019-04-09 01:24
I experienced that issue when first, App render serverErrorPage and next render normalPage

This issue related cache management

I solve this problem using emotion, emotion-server ssr => https://emotion.sh/docs/ssr#using-emotion-10-with-the-old-ssr-apis

**Comment by webberwang** [comment] 2019-05-22 00:50
`styled-components` has a `"ssr": true` option in babel, does emotion have something similar?

**Comment by SimplyComplexable** [comment] 2019-05-22 16:30
I have since switched to `styled-components` due to the lack of response on this thread and inability to figure out a solution on my end.
@webberwang `emotion` 10 is `ssr` by default. Also the project was set up using that guide, but it doesn't work. Thanks for the suggestions though!

**Comment by grrowl** [comment] 2019-06-12 04:06
I was having this problem with `next@8.1.0` (`props.theme` was always `{}` in server render, but fine in-browser). Downgraded to `next@8.0.4` and it works again, full theme is available in `props.theme`.

I believe that `require('emotion-theming')` was resolving to a different module id depending on the environment, as described in this issue https://github.com/zeit/next.js/issues/7109, so essentially `Consumer` wasn't from the exact same module as `Provider`, so it fell back to the default `{}` theme. May be because `emotion-theming` builds as both `cjs` and `mjs` versions. FWIW my problem is also fixed on the latest `@next` version which was `next@8.1.1-canary.51` at time of writing

**Comment by ssolanki** [comment] 2019-08-13 14:53
Any update on it?

**Comment by Andarist** [comment] 2019-10-29 23:41
I'd love to help with fixing your problem - but no exact repro case was given and without such, I cannot do much.

**Comment by grrowl** [comment] 2019-10-30 00:22
I believe this isn't a `emotion` problem specifically but an issue with some SSR stacks resolving the React Context to two different modules depending on whether it's a client or server build

**Comment by Andarist** [comment] 2019-10-31 10:31
I'm going to close this then - assuming the issue could already have been fixed by OP. If not - please share repro steps, if you do that I will take a look at your problem shortly.

**Closed by Andarist** 2019-10-31 10:31 UTC

**Comment by piotrblasiak** [comment] 2020-03-21 09:30
I am also having this problem in a brand new project. In my old project it works and I can not figure out why it's not working in this new one. I have created a test that shows the problem:

https://github.com/attendium/emotion-ssr-test

Just clone, npm install and npm run test

**Comment by Andarist** [comment] 2020-03-21 09:36
@piotrblasiak thank you for the repro - i will take a look at it soon

**Comment by Andarist** [comment] 2020-03-21 21:23
@piotrblasiak the problem is that you are running this test in jest which by default runs in a browser-like environment (using JSDOM). So emotion thinks it's used in a browser env and injects its styles into JSDOM's `document.head`.

If you add `/** @jest-environment node */` to this file then your returned `html` will be equal to what you expect it to:
```html
<style data-emotion-css="b5zacb-html">.css-b5zacb-html{color:red;}</style><div class="css-b5zacb-html">test</div>
```

**Comment by piotrblasiak** [comment] 2020-03-21 21:25
@Andarist Ahh, got it! Dziekuje serdecznie!
