### ISSUE TITLE
@emotion/jest: Unstable order over different systems (docker vs native)

### ISSUE THREAD

**Issue by KayVollers** [emotion-js/emotion#2163] opened 2020-12-08 15:33 UTC
**Current behavior:**

The order of interactive styles like `:hover`, `:focus` etc. is not stable in some cases. They are "jumping" around the "main class".
If multiple interactive styles exists they also mixing up themselves (e.g in some cases `:hover` is before `:focus` and in some it comes after).

The problem seems to occur only on docker vs native execution. As i get the same (stable) order on two different macs, running it on two different docker i also get the same (stable) order, but the order differ from the mac ones.

The screenshot shows the diff between running native (origin) and running on docker (the changes) after:
<img width="756" alt="Bildschirmfoto 2020-12-08 um 07 01 47" src="https://user-images.githubusercontent.com/8023579/101451819-0ed3b880-392d-11eb-9b9f-a0328ce599d2.png">

**To reproduce:**

1. Create a component like a button and add some styles including `:hover`, `:focus` and `:disabled` to it.
2. Create a `jest` test for using `toMatchSnapshot`
3. Run the test native with npm
4. Run the test with docker

**Expected behavior:**

The order of emotion styles should be the same independently from the environment it running on.

**Environment information:**

- `react` version: 16.14.0
- `@emotion/jest` version: 11.1.0
- `@testing-library/react` version: 11.2.2

**Comment by Andarist** [comment] 2020-12-08 17:16
This is quite weird because there shouldn't be any env-dependant code there. I'm afraid I won't be able to debug this myself but I'm happy to provide guidance on how you could do it so we could get to the bottom of it and provide a fix for this.

I would first check if the result is the same here:
https://github.com/emotion-js/emotion/blob/90bc7c1279c69fe481e3552a08404503ffa55a0e/packages/jest/src/create-serializer.js#L193
and later compare the results here:
https://github.com/emotion-js/emotion/blob/90bc7c1279c69fe481e3552a08404503ffa55a0e/packages/jest/src/utils.js#L191
and the last thing to check for the initial phase of the investigation would be to compare results before & after this sorting:
https://github.com/emotion-js/emotion/blob/90bc7c1279c69fe481e3552a08404503ffa55a0e/packages/jest/src/utils.js#L209-L212

**Comment by KayVollers** [comment] 2020-12-11 06:12
Thanks for the quick reply and the hints.

Indeed the diff comes up at your third spot `emotion/packages/jest/src/utils.js:209` (`.sort()`). But against my first expectation that this is a problem of the ordering (all classes with the same "mainclass" like .css-1au8nfi-StyledButton, .css-1au8nfi-StyledButton:hover, .css-1au8nfi-StyledButton:active have the same `classNameIndex`) it actually is a problem of the `.sort()` function itself.

Turned out that our docker image still used the older Node v10 while native we use a newer one 😅 . As `.sort()` got stable beginning with Node v11 an upgrade to a newer Node version on docker fixed the problem.

Thanks for your patience.

The Ticket can be closed now.

**Comment by Andarist** [comment] 2020-12-11 08:25
Cool! We could probably tweak the comparator function to handle this but I'm not sure if it's worth at this point in time. If we get more reports about this then I will consider handling it but for now, I consider the issue to be closed. I'm glad that updating a node version was an option for you.

**Closed by Andarist** 2020-12-11 08:25 UTC
Labels: bug

**Comment by thisismana** [comment] 2021-12-08 16:00
@Andarist since you requested more reports about this — we got one. Its basically the same issue as above, css gets mixed up in certain parts which leads to unstable `ETag`.

we're running a `node:14.18-alpine` docker image; but the markup/etag differs between multiple instances of our app. It seems every instance has its own free will and does things differently (in a non-deterministic way) :)
When observing a single instance the response is stable.

Not sure if it matters, we're using AWS/fargate so the task definitions and configurations should be identical for all the instances.

this can also be observed when starting the docker image multiple times locally

**Comment by Andarist** [comment] 2021-12-08 16:14
How the ETag relates to Jest? Are we sure this is a related problem? It seems that potentially you are having production issues with the SSRed output or something.

**Comment by thisismana** [comment] 2021-12-08 17:13
sorry, I'm the ops guy looking at this issue from another angle. This is about the part of the critical css created with emotion that is inlilned into the intial html doc itself and randomized order of css classes results in different etag/md5 hashes for those docs. Making it harder/less efficient to cache or re-validate.
So not at all Jest related but if I understood your [explaination](https://github.com/emotion-js/emotion/issues/2163#issuecomment-740774541) correctly due to the same mechanism mentioned here.

**Comment by Andarist** [comment] 2021-12-08 17:16
@thisismana could you create a new issue about this? one thing that I would check on your end is if you are creating a cache per SSR request - if not that is the first thing to be fixed.

**Comment by bobaaaaa** [comment] 2021-12-09 08:37
Hi @Andarist, one of the frontend person of @thisismana here ;). Thx for the fantastic tip about creating an emotion cache per SSR request 🎉. We are using nextjs that means each page now has its own cache. I could not find any hints about this in the docs. Maybe it's worth to highlight this.

For everyone who needs some tips how to reproduce with nextjs:
- we have multiple pages with some shared + individual styles. Let's call them `dashboard` & `blogpost` here.
- we are using a mix of `@emotion/css` and `@emotion/react` (`styled`)
- create a production build of your nextjs app
- run this app two times on different ports. E.g. `:3000` & `:4000`
- all caches are cold now
- request on `localhost:3000/dashboard`. Not on both apps. This is very important.
- requests to the other page route of both apps: `localhost:3000/blogpost` & `localhost:4000/blogpost`
- in our case, both requests respond with different `etag` http header

**Comment by Andarist** [comment] 2021-12-09 09:01
> I could not find any hints about this in the docs. Maybe it's worth highlighting this.

It's mentioned here: https://emotion.sh/docs/ssr#extractcritical . If you think there is a better place to highlight this - let us know. Unless your problem was not related to `extractCritical`?

Just to confirm, were you able to resolve your problem using an Emotion cache per SSR request?

**Comment by bobaaaaa** [comment] 2021-12-09 09:18
> It's mentioned here: https://emotion.sh/docs/ssr#extractcritical . If you think there is a better place to highlight this - let us know. Unless your problem was not related to `extractCritical`?

Ah, I see. I guess this is ok. The mix of emotion and nextjs is sometimes hard to find the "best" solution. Even the nextjs-examples look a bit different in our case. But that's a different story.

> Just to confirm, were you able to resolve your problem using an Emotion cache per SSR request?

Yes. Thank you very much for your help. ❤️
