### ISSUE TITLE
Speedy/Production mode fails in shadow dom

### ISSUE THREAD

**Issue by puema** [emotion-js/emotion#2053] opened 2020-10-21 07:57 UTC
**Current behavior:**

When attaching the emotion container into a shadow dom, it works great in dev mode, but when enabling the opinion `speedy` or building with NODE_ENV=production inserting styles via `insertRule` is failing.

**To reproduce:**

https://codesandbox.io/s/emotion-shadow-dom-v38tf?file=/src/my-element.js

1. In `src/emotion` option `speedy` is breaking it. If you omit this it works.

**Expected behavior:**

The styles should also be available with turned on `speedy` option.

**Environment information:**

- `react` version: no React in use
- `emotion` version: 10.0.27

**Comment by Andarist** [comment] 2020-10-21 09:13
You can't use `speedy` with detached containers - the `.sheet` property is just unavailable for them (it's `null`) so at the time of rule insertion this throws:
https://github.com/emotion-js/emotion/blob/c85378a204613885a356eaba1480c5151838c458/packages/sheet/src/index.js#L111
The best we can do is to add a runtime error/warning for such a scenario.

Note: reparenting of the style elements also doesn't work as Chrome clears all the contained rules.

**Comment by puema** [comment] 2020-10-21 09:31
Hey @Andarist,
Got it, thanks for the clarification! If using shadow dom, I have to move the container to the `shadowRoot` at some point. Otherwise, the styles in the head won't affect anything...
If Chrome clears all rules when moving the container around, is there any other way to use emotion in `speedy` mode in shadow dom that I'm not aware of?

**Comment by Andarist** [comment] 2020-10-21 10:30
I'm not sure why do you want to use `<template>` so not sure if my advice is going to be applicable for your use case - but I would just recommend creating things lazily, probably within `connectedCallback`, rather than upfront. This would allow you to keep things fairly the same:
https://codesandbox.io/s/emotion-shadow-dom-forked-nnk49?file=/src/my-element.js

**Comment by puema** [comment] 2020-10-21 13:24
Thanks for the suggestion and the effort of updating the sandbox, really appreciate this. The use case is the following: I want to provide a custom element with a shadow dom as an entry point and then internally there are multiple preact components where I want to have the styles per component.
```
export const SomeWhereDeepDownInMyWebComponent = () => (
  <div className={wrapper}>
    <p className={inner}>Text</p>
  </div>
);

const wrapper = css`
  // Some set of styles that I don't want the JSX to populate with
`;

const inner = css`
  // Some other styles
`;

```
The lazy creation would actually be helping indeed, although I'm finding it a bit cumbersome and uncommon having to do something like:
```
//...
<div className={createWrapper()}>
//...
const createWrapper = () => css`
`;
```

**Comment by Andarist** [comment] 2020-10-21 14:29
In such a case it's best to wrap things in a Preact's context:
https://codesandbox.io/s/hungry-vaughan-ze5k0?file=/src/my-element.js

**Comment by puema** [comment] 2020-10-23 09:54
Ah, yes. That's also a possible approach. Another way I found out works without changing anything in the components:
```typescript
const moveEmotionContainer = (container: HTMLElement, rootNode: ShadowRoot) => {
  const styleTags: NodeListOf<HTMLStyleElement> = container.querySelectorAll(
    'style[data-emotion="css"]'
  );
  /*
   * When re-parenting a node, the style rules are erased.
   * Therefore we copy the rules before attaching it to the shadow dom and insert them afterward again.
   */
  const cssRules: (CSSRuleList | undefined)[] = [];
  styleTags.forEach((styleTag) => cssRules.push(styleTag.sheet?.cssRules));
  rootNode.prepend(emotionContainer);
  styleTags.forEach((styleTag, index) => {
    const currentCssRules = cssRules[index];
    if (!currentCssRules) return;
    for (let i = 0; i < currentCssRules.length; i++) {
      styleTag.sheet?.insertRule(currentCssRules[i].cssText, i);
    }
  });
};
```
For a few styles, this is an additional effort of 1 ms on average. I'm going to monitor the performance impact 😉 
Shall I close the issue since this is more a consumer-related issue?

**Comment by Andarist** [comment] 2020-10-23 09:57
> Shall I close the issue since this is more a consumer-related issue?

Yea, gonna close this as it's not much that we can do on our side to automate things like this.

**Closed by Andarist** 2020-10-23 09:57 UTC
Labels: bug

**Comment by jordankoschei-okta** [comment] 2024-06-30 17:47
Checking in 4 years later — is `speedy` still failing when used with the shadow DOM?

**Comment by Andarist** [comment] 2024-06-30 18:13
According to the previous comments here, it's the fault of the browser API. We can't make it work if the browsers don't allow it.

**Comment by KevinGhadyani-Okta** [comment] 2024-08-30 18:18
That sucks. So we're stuck trying to work around this issue because browsers aren't allowing something in the `ShadowRoot` context that they allow in the regular `Window` context?

Is there a way to set `speedy: true` and have a workaround, or it's this functionality that browsers aren't allowing, so we're stuck with "slowy" rendering mode?

Is this something that would be solved by using vanilla CSS instead of Emotion?

**Comment by tlaziuk** [comment] 2026-01-28 12:14
guys, please I spent way too much time debugging this problem on my end before finding this issue, could you add a note somewhere that the `speedy` mode has such an effect?

**Comment by KevinGhadyani-Okta** [comment] 2026-01-28 17:52
> guys, please I spent way too much time debugging this problem on my end before finding this issue, could you add a note somewhere that the `speedy` mode has such an effect?

I believe this was fixed as I have `speedy` working now with Shadow DOM. Are you still having the issue on the latest Emotion version?

**Comment by tlaziuk** [comment] 2026-01-28 22:35
> I believe this was fixed as I have `speedy` working now with Shadow DOM. Are you still having the issue on the latest Emotion version?

As far as I know the issue occurs only on Safari desktop (tested on the latest version, 26.0), the app uses emotion ~11.11.0, but when I tried to upgrade to ~11.14.0 the issue was still there.

And I found it quite unpredictable to happen: I mean - I don't know what really triggers it, once it occurs it's reproducible, but I don't know how to intentionally introduce this issue - but [this comment](https://github.com/emotion-js/emotion/issues/2053#issuecomment-713429122) mentions detached nodes, and my app uses the View Transition API to transition between the screens, it does some "magic" with DOM, so maybe it's that?

I can't exactly show you the code, as the company I'm working in has reserved rights to it, but I'll try to prepare a MRE, given if I'll have some time.
