### ISSUE TITLE
@emotion/styled throwing error - Type Error: Cannot read property 'registered' of undefined at node modules emotion-styled-base.cjs.prod.js:131:53

### ISSUE THREAD

**Issue by sharanyam123** [emotion-js/emotion#2989] opened 2023-02-13 06:51 UTC
**Current behavior:**

I have nx monorepo project with nextJS + React and I am using @emotion/react and @emotion/styled in project. Earlier it was working fine but all of a sudden while building the project in argo workflow It is throwing the error related to emotion/styled for all the pages.

Note: In local, build is successful but while building in argo workflow I am facing this issue

```
Error occurred prerendering page "/page-name". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read property 'registered' of undefined
    at /project-directory/node_modules/@emotion/styled/base/dist/emotion-styled-base.cjs.prod.js:131:53
    at Styled(svg) (/project-directory/node_modules/@emotion/react/dist/emotion-element-20108edd.cjs.prod.js:62:16)
    at d (/project-directory/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
    at bb (/project-directory/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/project-directory/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/project-directory/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at Object.exports.renderToString (/project-directory/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
    at Object.renderPage (/project-directory/node_modules/next/dist/server/render.js:686:46)
    at Object.defaultGetInitialProps (/project-directory/node_modules/next/dist/server/render.js:316:51)
    at Function.getInitialProps (/project-directory/dist/apps/ui/.next/server/pages/_document.js:514:20)
```

```
Docker file: 
FROM node:14.21.0-alpine3.16

ARG ENV="${ENV}"

RUN apk --no-cache add git

RUN git clone --single-branch --branch master 

WORKDIR /project-directory

RUN npm config set user 0

RUN node --version

RUN npm --version

RUN npm cache clean --force

RUN npm install --force

RUN npm i @nx-tools/nx-docker

RUN npm install -g node-modules

RUN npm install -g @nrwl/cli

RUN npm run build:${ENV} -----> error at this step

CMD npx nx run ui:serve --configuration=production
```

**Expected behavior:**

It should build successfully without throwing any error.

**Environment information:**

- `react` version: 17.0.2
- `next` version: 12.0.7
- `nx` version: 13.6.1
- `@emotion/react` version: 11.10.5

**Comment by Andarist** [comment] 2023-02-13 07:55
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by sharanyam123** [comment] 2023-02-13 08:14
If it is in local I could have created a demo repo but the issue I am facing while building in argo workflow.  But if helps, I can share the file contents that the issue is pointing. 

**emotion-styled-base.cjs.prod.js** 

'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

var _extends = require('@babel/runtime/helpers/extends');
var React = require('react');
var isPropValid = require('@emotion/is-prop-valid');
var react = require('@emotion/react');
var utils = require('@emotion/utils');
var serialize = require('@emotion/serialize');
var useInsertionEffectWithFallbacks = require('@emotion/use-insertion-effect-with-fallbacks');

function _interopDefault (e) { return e && e.__esModule ? e : { 'default': e }; }

var isPropValid__default = /*#__PURE__*/_interopDefault(isPropValid);

var testOmitPropsOnStringTag = isPropValid__default['default'];

var testOmitPropsOnComponent = function testOmitPropsOnComponent(key) {
  return key !== 'theme';
};

var getDefaultShouldForwardProp = function getDefaultShouldForwardProp(tag) {
  return typeof tag === 'string' && // 96 is one less than the char code
  // for "a" so this is checking that
  // it's a lowercase character
  tag.charCodeAt(0) > 96 ? testOmitPropsOnStringTag : testOmitPropsOnComponent;
};
var composeShouldForwardProps = function composeShouldForwardProps(tag, options, isReal) {
  var shouldForwardProp;

  if (options) {
    var optionsShouldForwardProp = options.shouldForwardProp;
    shouldForwardProp = tag.__emotion_forwardProp && optionsShouldForwardProp ? function (propName) {
      return tag.__emotion_forwardProp(propName) && optionsShouldForwardProp(propName);
    } : optionsShouldForwardProp;
  }

  if (typeof shouldForwardProp !== 'function' && isReal) {
    shouldForwardProp = tag.__emotion_forwardProp;
  }

  return shouldForwardProp;
};

var isBrowser = typeof document !== 'undefined';

var Insertion = function Insertion(_ref) {
  var cache = _ref.cache,
      serialized = _ref.serialized,
      isStringTag = _ref.isStringTag;
  utils.registerStyles(cache, serialized, isStringTag);
  var rules = useInsertionEffectWithFallbacks.useInsertionEffectAlwaysWithSyncFallback(function () {
    return utils.insertStyles(cache, serialized, isStringTag);
  });

  if (!isBrowser && rules !== undefined) {
    var _ref2;
    var serializedNames = serialized.name;
    var next = serialized.next;
    while (next !== undefined) {
      serializedNames += ' ' + next.name;
      next = next.next;
    }
    return /*#__PURE__*/React.createElement("style", (_ref2 = {}, _ref2["data-emotion"] = cache.key + " " + serializedNames, _ref2.dangerouslySetInnerHTML = {
      __html: rules
    }, _ref2.nonce = cache.sheet.nonce, _ref2));
  }
  return null;
};

var createStyled = function createStyled(tag, options) {

  var isReal = tag.__emotion_real === tag;
  var baseTag = isReal && tag.__emotion_base || tag;
  var identifierName;
  var targetClassName;
  if (options !== undefined) {
    identifierName = options.label;
    targetClassName = options.target;
  }
  var shouldForwardProp = composeShouldForwardProps(tag, options, isReal);
  var defaultShouldForwardProp = shouldForwardProp || getDefaultShouldForwardProp(baseTag);
  var shouldUseAs = !defaultShouldForwardProp('as');
  return function () {
    var args = arguments;
    var styles = isReal && tag.__emotion_styles !== undefined ? tag.__emotion_styles.slice(0) : [];
    if (identifierName !== undefined) {
      styles.push("label:" + identifierName + ";");
    }
    if (args[0] == null || args[0].raw === undefined) {
      styles.push.apply(styles, args);
    } else {
      styles.push(args[0][0]);
      var len = args.length;
      var i = 1;
      for (; i < len; i++) {
        styles.push(args[i], args[0][i]);
      }
    } // $FlowFixMe: we need to cast StatelessFunctionalComponent to our PrivateStyledComponent class
    var Styled = react.withEmotionCache(function (props, cache, ref) {
      var FinalTag = shouldUseAs && props.as || baseTag;
      var className = '';
      var classInterpolations = [];
      var mergedProps = props;
      if (props.theme == null) {
        mergedProps = {};
        for (var key in props) {
          mergedProps[key] = props[key];
        }
        mergedProps.theme = React.useContext(react.ThemeContext);
      }
      if (typeof props.className === 'string') {
        

> **className = utils.getRegisteredStyles(cache.registered, classInterpolations, props.className);**  --> **_Error is at this point_**
      } else if (props.className != null) {
        className = props.className + " ";
      }
      var serialized = serialize.serializeStyles(styles.concat(classInterpolations), cache.registered, mergedProps);
      className += cache.key + "-" + serialized.name;
      if (targetClassName !== undefined) {
        className += " " + targetClassName;
      }
      var finalShouldForwardProp = shouldUseAs && shouldForwardProp === undefined ? getDefaultShouldForwardProp(FinalTag) : defaultShouldForwardProp;
      var newProps = {};
      for (var _key in props) {
        if (shouldUseAs && _key === 'as') continue;
        if ( // $FlowFixMe
        finalShouldForwardProp(_key)) {
          newProps[_key] = props[_key];
        }
      }
      newProps.className = className;
      newProps.ref = ref;
      return /*#__PURE__*/React.createElement(React.Fragment, null, /*#__PURE__*/React.createElement(Insertion, {
        cache: cache,
        serialized: serialized,
        isStringTag: typeof FinalTag === 'string'
      }), /*#__PURE__*/React.createElement(FinalTag, newProps));
    });
    Styled.displayName = identifierName !== undefined ? identifierName : "Styled(" + (typeof baseTag === 'string' ? baseTag : baseTag.displayName || baseTag.name || 'Component') + ")";
    Styled.defaultProps = tag.defaultProps;
    Styled.__emotion_real = Styled;
    Styled.__emotion_base = baseTag;
    Styled.__emotion_styles = styles;
    Styled.__emotion_forwardProp = shouldForwardProp;
    Object.defineProperty(Styled, 'toString', {
      value: function value() {
        if (targetClassName === undefined &&         "production" !== 'production') {
          return 'NO_COMPONENT_SELECTOR';
        } // $FlowFixMe: coerce undefined to string
        return "." + targetClassName;
      }
    });
    Styled.withComponent = function (nextTag, nextOptions) {
      return createStyled(nextTag, _extends({}, options, nextOptions, {
        shouldForwardProp: composeShouldForwardProps(Styled, nextOptions, true)
      })).apply(void 0, styles);
    };
    return Styled;
  };
};

exports.default = createStyled;

**Comment by Andarist** [comment] 2023-02-13 08:34
This doesn't help. The only thing that can help is creating a repro case that could be executed with a single command and tested out.

I suspect that you have multiple copies of `@emotion/react` in your project and that you should ensure that you are using only a single one.

**Comment by sharanyam123** [comment] 2023-02-13 09:33
> This doesn't help. The only thing that can help is creating a repro case that could be executed with a single command and tested out.
> 
> I suspect that you have multiple copies of `@emotion/react` in your project and that you should ensure that you are using only a single one.

I dont think so.. I just have one @emotion/react in my package.json

```
{
  "name": "project-workspace",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "start": "nx serve",
    "build": "nx build",
    "build:development": "cp apps/ui/env/.env.development apps/ui/.env && nx build",
    "build:production": "cp apps/ui/env/.env.production apps/ui/.env && nx build",
    "build:staging": "cp apps/ui/env/.env.staging apps/ui/.env && nx build",
    "test": "nx test",
    "test:all": "nx affected:test --all --codeCoverage --skip-nx-cache"
  },
  "private": true,
  "dependencies": {
    "@emotion/react": "^11.10.5",
    "@emotion/styled": "^11.10.5",
    "@hookform/resolvers": "^2.8.8",
    "@material-ui/core": "^4.12.3",
    "@monaco-editor/react": "^4.4.5",
    "@mui/icons-material": "^5.4.1",
    "@mui/lab": "^5.0.0-alpha.72",
    "@mui/material": "^5.4.1",
    "@nrwl/next": "13.7.0",
    "@peculiar/webcrypto": "^1.4.1",
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/user-event": "^13.5.0",
    "axios": "^0.27.2",
    "jest-next-dynamic": "^1.0.1",
    "keycloak-js": "^19.0.1",
    "leaflet": "^1.7.1",
    "leaflet-defaulticon-compatibility": "^0.1.1",
    "moment": "^2.29.3",
    "next": "12.0.7",
    "node-sass": "^6.0.1",
    "nx": "^13.6.1",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-dropzone": "^14.2.1",
    "react-graph-vis": "^1.0.7",
    "react-hook-form": "^7.28.0",
    "react-icons": "^4.3.1",
    "react-leaflet": "^3.2.5",
    "react-typical": "^0.1.3",
    "swr": "^1.2.0",
    "vis-network": "^9.1.2",
    "yaml": "^2.1.1",
    "yup": "^0.32.11"
  },
  "devDependencies": {
    "@nrwl/cli": "13.7.0",
    "@nrwl/eslint-plugin-nx": "13.7.0",
    "@nrwl/jest": "13.7.0",
    "@nrwl/linter": "13.7.0",
    "@nrwl/nx-cloud": "13.1.6",
    "@nrwl/react": "13.7.0",
    "@nrwl/tao": "13.6.1",
    "@nrwl/web": "13.7.0",
    "@nrwl/workspace": "13.7.0",
    "@nxrocks/nx-spring-boot": "^3.0.0",
    "@testing-library/react": "12.1.2",
    "@testing-library/react-hooks": "7.0.2",
    "@testing-library/user-event": "^13.5.0",
    "@types/enzyme": "^3.10.12",
    "@types/jest": "27.0.2",
    "@types/leaflet": "^1.7.9",
    "@types/react": "18.0.1",
    "@types/react-dom": "18.0.1",
    "@types/react-leaflet": "^2.8.2",
    "@typescript-eslint/eslint-plugin": "5.10.2",
    "@typescript-eslint/parser": "5.10.2",
    "@wojtekmaj/enzyme-adapter-react-17": "^0.6.6",
    "babel-jest": "27.2.3",
    "enzyme": "^3.11.0",
    "eslint": "8.7.0",
    "eslint-config-next": "12.0.7",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-import": "2.25.2",
    "eslint-plugin-jsx-a11y": "6.5.1",
    "eslint-plugin-react": "7.27.0",
    "eslint-plugin-react-hooks": "4.3.0",
    "jest": "27.2.3",
    "jest-canvas-mock": "^2.4.0",
    "jest-fetch-mock": "^3.0.3",
    "next-router-mock": "^0.6.8",
    "prettier": "^2.5.1",
    "react-test-renderer": "17.0.2",
    "sass": "1.43.2",
    "ts-jest": "27.0.5",
    "typescript": "~4.4.3"
  },
  "overrides": {
    "json-schema": "^0.4.0",
    "minimist": "^1.2.6",
    "ansi-regex": "^4.1.1",
    "qs": "^1.0.0",
    "tar": "^6.0.2",
    "node-fetch": "^2.6.7",
    "scss-tokenizer": "~0.4.3",
    "minimatch": "3.0.5",
    "mime": "^1.4.1",
    "path-parse": "^1.0.7",
    "request": ">=2.68.0"
  },
  "engines": {
    "node": ">=14.17.2 <=16.14.0"
  }
}
```

**Comment by Andarist** [comment] 2023-02-13 09:49
Please investigate your lock file and node_modules, not just the `package.json` file

**Comment by igor-smolkov** [comment] 2023-02-13 15:01
**Same problem.**
Same build error.

Compiled successfully
Generating static pages (0/37)

```
Error occurred prerendering page "/en/project/17". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of undefined (reading 'registered')
    at D:\project\front\node_modules\@emotion\styled\base\dist\emotion-styled-base.cjs.prod.js:131:53
    at D:\project\front\node_modules\@emotion\react\dist\emotion-element-20108edd.cjs.prod.js:62:16
    at d (D:\project\front\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:33:498)
    at bb (D:\project\front\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:36:16)
...
```

And so on, for all pages.

Two months ago the project was building without problems.
Today the project was building without problems. But when I reinstalled the dependencies this problem appeared.

Installing old versions of `@emotion/react` and `@emotion/styled` packages does not work. (11.9.3 - 8 months ago)

The old version of my project, which worked without problems, now does not work either! (Same problem)
This is weird.

I delete the lock file and the node_modules folder when reinstalling.
I don't have duplicate of emotion packages in package.json.

Package versions:
```
"@emotion/react": "11.10.5"
"@emotion/styled": "11.10.5"
"next": "12.1.5"
"react": "^17.0.2"
```

**Comment by sharanyam123** [comment] 2023-02-14 05:11
> **Same problem.** Same build error.
> 
> Compiled successfully Generating static pages (0/37)
> 
> ```
> Error occurred prerendering page "/en/project/17". Read more: https://nextjs.org/docs/messages/prerender-error
> TypeError: Cannot read properties of undefined (reading 'registered')
>     at D:\project\front\node_modules\@emotion\styled\base\dist\emotion-styled-base.cjs.prod.js:131:53
>     at D:\project\front\node_modules\@emotion\react\dist\emotion-element-20108edd.cjs.prod.js:62:16
>     at d (D:\project\front\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:33:498)
>     at bb (D:\project\front\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:36:16)
> ...
> ```
> 
> And so on, for all pages.
> 
> Two months ago the project was building without problems. Today the project was building without problems. But when I reinstalled the dependencies this problem appeared.
> 
> Installing old versions of `@emotion/react` and `@emotion/styled` packages does not work. (11.9.3 - 8 months ago)
> 
> The old version of my project, which worked without problems, now does not work either! (Same problem) This is weird.
> 
> I delete the lock file and the node_modules folder when reinstalling. I don't have duplicate of emotion packages in package.json.
> 
> Package versions:
> 
> ```
> "@emotion/react": "11.10.5"
> "@emotion/styled": "11.10.5"
> "next": "12.1.5"
> "react": "^17.0.2"
> ```

Earlier build was successful in local and the issue is in argo. But I tried deleting node modules and lock file and reinstalled dependencies. Now I am getting this issue in local as well. 

Any idea how to fix it?

**Comment by Andarist** [comment] 2023-02-14 09:13
It's hard to tell without seeing the repro case for this. If you manage to create one I will try to look into it.

**Comment by sharanyam123** [comment] 2023-02-14 11:22
The issue I am facing is because of @mui/material, I think the issue will get resolved once their PR will get merged 
[https://github.com/mui/material-ui/issues/36096](url)
PR: [https://github.com/mui/material-ui/pull/36162](url)

**Closed** 2023-02-23 06:11 UTC
Labels: bug, needs triage

**Comment by rubanzasilva** [comment] 2023-06-08 11:21
@sharanyam123 how did you finally get to fix this

**Comment by sharanyam123** [comment] 2023-06-08 12:19
> @sharanyam123 how did you finally get to fix this

At that issue was with @material/mui. so they fixed it.

> The issue I am facing is because of @mui/material, I think the issue will get resolved once their PR will get merged [https://github.com/mui/material-ui/issues/36096](url) PR: [https://github.com/mui/material-ui/pull/36162](url)

I didn't fix it. Issue was with @material/mui. so they resolved it

**Comment by rubanzasilva** [comment] 2023-06-08 13:53
Ohh I get it, thanks

I think what caused my issue was different.
<img width="959" alt="image" src="https://github.com/emotion-js/emotion/assets/27724348/5d565552-2dc5-4864-a835-35f85d593084">

But I solved it by replacing **npm ci** with **npm install** in the node.js.yml file

**Comment by jamesopti** [comment] 2024-02-18 19:55
I encountered this issue and realized it is easily reproducible by using JSDOM to patch the SSR global `document`, which is required for my SSR use case.

This wasn't an issue with NextJS pages directory but is now with the app directory.

Any thoughts?


```ts
  const jsdom = require('jsdom')
  const html = `<!DOCTYPE html><html><body></body></html>`
  console.log('PATCHING JSDOM')
  const { window } = new jsdom.JSDOM(html)
  global.window = window
  global.document = window.document
```


```ts
X ../../node_modules/@emotion/styled/base/dist/emotion-styled-base.esm.js (140:38) @ eval
X Internal error: TypeError: Cannot read properties of null (reading 'registered')
   at eval (../../node_modules/@emotion/styled/base/dist/emotion-styled-base.esm.js:152:134)
   at eval (../../node_modules/@emotion/react/dist/emotion-element-3838ba9e.esm.js:60:12)
   at Bi (/Users/james/app/packages/client/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:1:248560)
   at /Users/james/app/packages/client/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:1:256817
   at rs (/Users/james/app/packages/client/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:1:256864)
   at as (/Users/james/app/packages/client/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:1:261055)
   at os (/Users/james/app/packages/client/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:1:260774)
   at ts (/Users/james/app/packages/client/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:1:249948)
   at /Users/james/app/packages/client/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:1:256808
```

**Comment by deniapps** [comment] 2024-06-20 13:14
Got this error when using the following code provided by ChatGPT:
```
    <CacheProvider cache={cache}>
      <div>
        <h1>Hello Emotion</h1>
        <MyButton>Click Me</MyButton>
      </div>
    </CacheProvider>
```
Finally, I figured out that there is no prop named "cache". Renaming it to "value" fixed the issue.

**Comment by izhar360** [comment] 2024-07-09 08:33
> > **Current behavior:**
> > I have nx monorepo project with nextJS + React and I am using @emotion/react and @emotion/styled in project. Earlier it was working fine but all of a sudden while building the project in argo workflow It is throwing the error related to emotion/styled for all the pages.
> > Note: In local, build is successful but while building in argo workflow I am facing this issue
> > ```
> > Error occurred prerendering page "/page-name". Read more: https://nextjs.org/docs/messages/prerender-error
> > TypeError: Cannot read property 'registered' of undefined
> >     at /project-directory/node_modules/@emotion/styled/base/dist/emotion-styled-base.cjs.prod.js:131:53
> >     at Styled(svg) (/project-directory/node_modules/@emotion/react/dist/emotion-element-20108edd.cjs.prod.js:62:16)
> >     at d (/project-directory/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
> >     at bb (/project-directory/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
> >     at a.b.render (/project-directory/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
> >     at a.b.read (/project-directory/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
> >     at Object.exports.renderToString (/project-directory/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
> >     at Object.renderPage (/project-directory/node_modules/next/dist/server/render.js:686:46)
> >     at Object.defaultGetInitialProps (/project-directory/node_modules/next/dist/server/render.js:316:51)
> >     at Function.getInitialProps (/project-directory/dist/apps/ui/.next/server/pages/_document.js:514:20)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > Docker file: 
> > FROM node:14.21.0-alpine3.16
> > 
> > ARG ENV="${ENV}"
> > 
> > RUN apk --no-cache add git
> > 
> > RUN git clone --single-branch --branch master 
> > 
> > WORKDIR /project-directory
> > 
> > RUN npm config set user 0
> > 
> > RUN node --version
> > 
> > RUN npm --version
> > 
> > RUN npm cache clean --force
> > 
> > RUN npm install --force
> > 
> > RUN npm i @nx-tools/nx-docker
> > 
> > RUN npm install -g node-modules
> > 
> > RUN npm install -g @nrwl/cli
> > 
> > RUN npm run build:${ENV} -----> error at this step
> > 
> > CMD npx nx run ui:serve --configuration=production
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Expected behavior:**
> > It should build successfully without throwing any error.
> > **Environment information:**
> > 
> > * `react` version: 17.0.2
> > * `next` version: 12.0.7
> > * `nx` version: 13.6.1
> > * `@emotion/react` version: 11.10.5
> 
> I was having the same error. In my case I was testing some React components with **Mocha** + **Chai** and **RTL** when I tried to render the component to test anything of it so this problem came out, and as it looks in you error your problem is within the render as well. Following the **MUI** librarie dependencies I saw they were using **@emotion/react** for some rendering processes, it looks like a problem with **MUI v5** where they change the cache object and accidentally remove the cache object provided by **@emotion/react**, this leads to the `TypeError: Cannot read property 'registered' of undefined` cause they are not adding the `cache.registered` in the new cache.
> 
> Solution: I solved the issue just by wrapping my component in @emotion/react provider (`<CacheProvider>{my component}</CacheProvider>`). You can try following this example provided by @emotion.react: https://emotion.sh/docs/cache-provider

hi, are you passing any props to <CacheProvider>?
