### ISSUE TITLE
Styled Components Using Props Exhibit Incorrect Styles (@emotion/styled)

### ISSUE THREAD

**Issue by XxX-MLGNoob-XxX** [emotion-js/emotion#1772] opened 2020-02-19 02:31 UTC
**Current behavior:**
The styling of components created with `@emotion/styled`'s `styled` utility behaves incorrectly when props are used to impact the styling. That is, there's a possibility that the styling you define with the props won't show up correctly at all. Additionally, styling with selectors may be corrupted when props-based styling is introduced.

**To reproduce:**
Please visit [this github repo](https://github.com/XxX-MLGNoob-XxX/styled-issues) for an example of the issue. The steps are simple:

1. Create a styled component that uses props in some way for styling.
2. Render the component.
3. You should see that the styling does not behave correctly. If this isn't the case, perhaps you chose a bad styling property. The example repo makes sure you can at least see the bug in action.

**Expected behavior:**
The styling should behave normally when the styles are influenced by props. This should hold true regardless of where I place my props-based styles.

**Environment information:**
- `react` version: 16.12.0
- `@emotion/core` version: 10.0.27
- `@emotion/styled` version: 10.0.27

**Misc:**
Included in the repo are inexplicable work-arounds for the bug. One involves separating the base styles, and another involves placing all props-based styles at the end of the definition. (These solutions might be one and the same).

Please excuse the extraneous inclusion of the `styled-components` library. Both `@emotion/styled` and `styled-components` seem to be encountering the same issue. So sharing a single repo simplifies things for me.

I spent like a week trying to tunnel in on a possible root cause before posting so some help would be appreciated. xD

**Comment by Andarist** [comment] 2020-02-19 08:14
The problem is that you are missing a semicolon after your interpolated width and for some reason, this breaks our parser (stylis) in this context. 

I'm afraid that we won't be fixing this right now because current stylis code is quite complex. It's also being reworked right now (so it should become much more maintainable) and we hope to include its rewrite in the upcoming v11. Keep in mind that it's always better to use explicit semicolons in your styles.

**Comment by XxX-MLGNoob-XxX** [comment] 2020-02-19 11:26
I see! I haven't seen semicolons used with interpolated styles before, so I didn't know. My apologies.

Should I close this issue?

**Comment by Andarist** [comment] 2020-03-13 21:36
No problem, I'm glad that I could help you.

**Closed** 2020-03-13 21:36 UTC
Labels: bug
