### ISSUE TITLE
Interpolation of numbers in @emotion/native

### ISSUE THREAD

**Issue by toboid** [emotion-js/emotion#1333] opened 2019-04-29 18:00 UTC
- `emotion` version: 10.0.10
- `react` version: 16.8.6

**Relevant code:**

```javascript
    expect(
      css`
        opacity: ${0.5};
      `
    ).toEqual({ opacity: 0.5 })

// Actual is empty object - {}

```

**What you did:**
Attempting to interpolate number into an @emotion/native css prop.

This is useful for example when sharing CSS values for re-use across multiple components.

**What happened:**
@emotion/native will not process this style definition correctly and the style will not be applied.

**Reproduction:**
See [here](https://github.com/toboid/emotion/blob/bug/number-interpolation/packages/native/test/native-css.test.js#L8) for a failing test that I have added to the existing test suite for demo purposes.

**Problem description:**
@emotion/native CSS interpolation does not correctly handle CSS rules where the interpolated value is a number.

**Suggested solution:**
Looks like a change is required [here](https://github.com/emotion-js/emotion/blob/master/packages/primitives-core/src/css.js). I might be able to help with some guidance.

**Comment by Slapbox** [comment] 2019-07-09 22:41
Anyone have any thoughts on this? @Andarist?

I'm really surprised this doesn't work and I've seen multiple people on the web (and even in the issue tracker) suggest that it does, but sadly it doesn't.

Is there an intentional reason it doesn't work, or would the team be open to a PR?

**Comment by Slapbox** [comment] 2019-07-09 22:48
Converting numbers to strings works nicely, but it would be great to have it built into Emotion.

It seems like we could just run a `toString()` on any input of `type === 'number'` but I'm unsure what these two lines do and what `isRnStyle` means:

https://github.com/emotion-js/emotion/blob/master/packages/primitives-core/src/css.js#L46-L47

**Comment by Andarist** [comment] 2019-10-28 22:30
I know this issue is older, but there is some additional context in https://github.com/emotion-js/emotion/issues/1543 which is a duplicate of this issue. I'm closing in favor of the other one. 

While we have those native flavors of emotion, we don't have capacity to handle all issues for them (there are not many though 😉 ). As you seem to be interested in those packages - we would highly appreciate your help in fixing problems like this.

**Closed by Andarist** 2019-10-28 22:30 UTC
