### ISSUE TITLE
Incorrect TypeScript errors about a missing css prop

### ISSUE THREAD

**Issue by TejasQ** [emotion-js/emotion#1431] opened 2019-07-10 08:58 UTC
**Current Behavior:**

The error we're seeing is this:

![image](https://user-images.githubusercontent.com/9947422/60955543-594ca200-a301-11e9-8356-90d4ca5b6f86.png)

This _may be_ a duplicate of https://github.com/emotion-js/emotion/issues/693 but I'm not yet convinced because we're on newer versions of all of these:

https://github.com/contiamo/operational-ui/blob/7f3a10e1e24ff04b90a54940644d3c9340ebaa1c/package.json#L158

https://github.com/contiamo/operational-ui/blob/7f3a10e1e24ff04b90a54940644d3c9340ebaa1c/package.json#L75

https://github.com/contiamo/operational-ui/blob/7f3a10e1e24ff04b90a54940644d3c9340ebaa1c/package.json#L76

and we still see this odd error in TypeScript.

I'm not entirely sure why.

**To Reproduce**
Click **View Code** [here](https://deploy-preview-1105--operational-ui.netlify.com/#/Typography/FinePrint)

The component's source code is:
https://github.com/contiamo/operational-ui/blob/7f3a10e1e24ff04b90a54940644d3c9340ebaa1c/src/Typography/FinePrint/index.tsx#L3-L13

**Expected behavior:**
Clean compilation.

**Environment information:**

- `react` version:
https://github.com/contiamo/operational-ui/blob/7f3a10e1e24ff04b90a54940644d3c9340ebaa1c/package.json#L86

- `emotion` version:
https://github.com/contiamo/operational-ui/blob/7f3a10e1e24ff04b90a54940644d3c9340ebaa1c/package.json#L75

**Comment by Andarist** [comment] 2019-07-11 21:10
Have you experienced this problem before with emotion@10 or have you just upgraded to version 10 and it has popped up?

**Comment by TejasQ** [comment] 2019-07-11 22:44
It started after moving to emotion 10.

**Comment by pete-redmond-cko** [comment] 2019-07-12 10:30
I am also getting this error when using `@emotion/styled@^10.0.14` with Typescript

```jsx
const ClickableElement = styled.button`
  padding: 0;
  border: none;
  font: inherit;
  color: inherit;
  background-color: transparent;
  cursor: pointer;

  &:focus {
    outline: 2px solid rgba(42, 171, 130, 0.5);
  }
`;
```

```jsx
<ClickableElement onClick={onClose}>
  Click here
</ClickableElement>
```

And the TS issue I get is

```
Property 'css' is missing in type '{ children: Element; onClick: any; }' but required in type 'Pick<DetailedHTMLProps<ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>, "color" | "hidden" | "style" | "disabled" | "defaultChecked" | "defaultValue" | "suppressContentEditableWarning" | ... 257 more ... | "formTarget">'.ts(2741)
```

**Comment by Andarist** [comment] 2019-07-12 12:51
Could you prepare an isolated repository with the issue reproduced? I'm trying to reproduce this in our repo and can't do it, also `css` prop is defined everywhere as optional - so not sure how this could happen.

**Comment by danieldelcore** [comment] 2019-07-29 02:17
I'm also bumping into this issue.
Not entirely sure about the cause, but i _think_ it can be replicated when using a `Pick` or `Omit` (which depends on `Pick`). 

In my case, I have some code doing the following: 

```typescript
export interface OnlyButtonProps {
  children?: React.ReactNode;
}

export type ButtonProps = OnlyButtonProps & Omit<React.HTMLProps<HTMLButtonElement>, 'ref'>;
```

For me the error only appears when i build, not sure why 🤷‍♂ 

I'll try and get a rerpo

**Comment by niekert** [comment] 2019-09-09 11:31
I ran into the same issue today while I was working on a package where I was importing components from another package that were created (and typed) as `styled()` components from `@emotion/styled`, all on version `10.0.17`. 

The issue went away after adding a `import '@emotion/core'` to the `index.ts` file of my package. I think the problem resided in the fact that the [type definitions to support the `css` prop](https://github.com/emotion-js/emotion/blob/master/packages/core/types/index.d.ts#L82) would otherwise not be properly resolved by TypeScript somehow.

**Comment by Andarist** [comment] 2019-10-27 12:25
Typings are currently getting a serious makeover in https://github.com/emotion-js/emotion/pull/1501 and we plan to rethink how the theme can be typed. Closing this to clear up the issue tracker, but if you are interested in this please follow that PR, give your feedback if necessary and stay tuned for upcoming changes!

**Closed by Andarist** 2019-10-27 12:25 UTC
Labels: bug, needs triage
