### ISSUE TITLE
New Chrome version causes components to lose styles

### ISSUE THREAD

**Issue by tylerzey** [emotion-js/emotion#3256] opened 2024-09-21 16:55 UTC
Hi there!

After upgrading Chrome to 129 this last week, our Next application styled with MUI started having styles not applied.

The css class would be on the element, but the styles were not in the dom.  We were able to resolve it for now lowering one of our apps `@emotion/cache` from 11.13.1 to 11.12.0. And raising another apps `@emotion/cache` to 11.12.0.

The issue only arrises in production (not in dev mode), for us. 

There might be an [issue with chromium](https://issues.chromium.org/issues/367758074) and [this issue](https://issues.chromium.org/issues/363189653).

Related Issue open in MUI:
https://github.com/mui/material-ui/issues/43823

Our installed MUI versions:
```
"@mui/icons-material": "5.16.7",
"@mui/material": "5.15.12",
"@mui/utils": "5.16.6",
"@mui/x-charts": "7.13.0",
"@mui/x-data-grid": "7.13.0",
"@mui/x-date-pickers": "7.13.0",
```

Next version:
```
"next": "14.2.12",
```

I have been unable to create a minimal repro in codesanbox, yet.

**Comment by Andarist** [comment] 2024-09-21 17:01
The second one may be related. 

If this is a Chrome issue... I don't know what we can do to work around it 🤷‍♂️ You could use `speedy: false` in prod temporarily to overcome this

**Comment by tylerzey** [comment] 2024-09-21 17:04
Disabling speedy does resolve the issue in 11.13.1. We tested and confirmed that. 

However, 11.12.0 works without disabling speedy. Quite odd.

**Comment by aemonm** [comment] 2024-09-21 18:27
@tylerzey could you post your exact dependency tree that solves this issue for you? Setting `@emotion/react` and `@emotion/styled` to `11.12.0` is not fixing it for me.

**Comment by tylerzey** [comment] 2024-09-21 19:36
@aemonm - locking `@emotion/cache` at `11.12.0` fixed it for us in 2 separate repos.

One repo, we upgraded to `11.12.0`. And one repo, we dowgraded to `11.12.0`

```
"@emotion/cache": "11.12.0",
"@emotion/react": "11.12.0",
"@emotion/styled": "11.12.0",
```

**Comment by Andarist** [comment] 2024-09-22 18:14
Are you saying that this bug only manifests in some Emotion versions?

**Comment by tylerzey** [comment] 2024-09-22 19:40
Yes.

Emotion/mui styles that were working in 128 Chrome (and all other browsers) broke in Chrome 129. 

We were able to resolve the issue in Chrome 129 by using emotion 11.12.0. 

(One app we downgraded to 11.12.0. One app we upgraded to 11.12.0)

@aemonm - did defining emotion/cache at 11.12.0 fix it for your app?

**Comment by elawad** [comment] 2024-09-22 22:38
Just noticed the same issue. Pinning to 11.12.0 did not resolve the issue during a local build test.
Tested on latest Chrome `129.0.6668.59 (arm64)` on macOS.
Even deleted node_modules + lock file for a fresh install. Still same issue.
```
"@emotion/cache": "11.12.0",
"@emotion/react": "11.12.0",
"@emotion/styled": "11.12.0",
"@mui/icons-material": "5.16.17",
"@mui/material": "5.16.17",
"@mui/styles": "5.16.17",
"@mui/x-data-grid-pro": "7.18.0",
```

**Comment by aemonm** [comment] 2024-09-22 23:56
@tylerzey No, locking the `@emotion/*` packages didn't resolve it for us unforunately. Still looking for a fix.

**Comment by yuhr** [comment] 2024-09-24 09:14
In our case the culprit was comments in the template strings for `@emotion/styled`. If we have

```typescript
const MyDiv = styled.div`
	...
	/* some comment */
	...
`
```

then the properties only after the comment was not rendered in production, so removing such comments fixed the issue for us.

**Comment by Andarist** [comment] 2024-09-24 09:32
That's unexpected as comments are stripped down by Emotion anyway before passing styles to the browser.

**Comment by itsjohncs** [comment] 2024-09-24 16:38
This issue was consistently reproducible on latest Chromium-based browsers for us, even though we're on an old version of Emotion (11.9.3). Disabling `speedy` fixed the problem.

I suggest that anyone using Emotion disables `speedy` for a few months until a fix for Chromium comes out and the broken browser versions are mostly out of circulation.

**Comment by tylerzey** [comment] 2024-09-24 20:01
_Cross posting from the MUI thread._ [see here](https://github.com/mui/material-ui/issues/43823#issuecomment-2372246864)

This seems fixed in the new patch version of chrome `129.0.6668.71`. It was broken in `129.0.6668.59`

[Chromium code revert](https://chromium-review.googlesource.com/c/v8/v8/+/5887185)

**Comment by karol-f** [comment] 2024-09-24 20:13
Do we know when it will be released?

**Comment by marwanKettleCom** [comment] 2024-09-24 20:15
> Do we know when it will be released?

Already release.  Get the latest stable install.

**Comment by Andarist** [comment] 2024-09-25 08:11
@tylerzey thanks for staying on top of it. I think it's fair to close this issue then since it got fixed upstream

**Closed by Andarist** 2024-09-25 08:11 UTC
Labels: bug, needs triage
