### ISSUE TITLE
Cannot turn off "potentially unsafe when doing server-side rendering" noise

### ISSUE THREAD

**Issue by RoystonS** [emotion-js/emotion#1105] opened 2018-12-13 11:07 UTC
Emotion 10 is emitting a series of console warnings along the lines of:

```
The pseudo class ":first-child" is potentially unsafe when doing server-side rendering. Try changing it to "first-of-type"
The pseudo class ":nth-child" is potentially unsafe when doing server-side rendering. Try changing it to "nth-of-type"
```

- `emotion` version: 10.0.4
- `react` version: 16.7.0-alpha2

**Problem description:**

1. I'm not using server-side rendering so these warnings aren't useful for me and are just console noise that means real problems will be masked.  Apart from running in a production build, I can't see any way to turn these warnings off right now.
1. The error message doesn't help me understand why these pseudo classes are a problem; I can't find them mentioned in the Emotion docs, or references on the Internet as to why these might be a problem.

**Suggested solution:**

1. Provide a way to turn off these warnings if users don't want them.
1. Provide a link, or some documentation, as to why these pseudos are problematic.

**Comment by Andarist** [comment] 2018-12-13 13:05
Leaving this here - https://github.com/emotion-js/emotion/issues/1059#issuecomment-444566635 as this issue is dedicated to this problem.

**Comment by vajkri** [comment] 2019-01-08 09:20
We are getting the warnings too using SSR. 
The styles targeting with `:nth-child()`, `:first-child` or `:last-child` don't even get applied server-side, so this causes elements to "jump" on page load when these styles get applied client-side.

**Comment by brentertz** [comment] 2019-01-24 16:22
Hi Folks,

The inability to disable these console messages is a blocker for us being able to ship the [Emotion 10 update to our component library](https://github.com/mineral-ui/mineral-ui/pull/816). As a library, these messages are also visible to all of our downstream consumers.

We do not wish to update the selector usage in our library as we do not believe Emotion's current SSR strategy to be a valid trade-off for breaking numerous commonly used CSS selectors, hence #1178. We are hopeful that an alternate approach can be found there as well, but in the mean time, simply would like to disable these console messages.

Is there anything that can be done here to move things forward?  We are willing to do the work, or collaborate, if you can provide some insight into the direction that you would like to take.

__Possible Solutions__

* Simply remove logging; instead improve and rely on SSR documentation
* Conditionally remove logging, e.g. ENV var or other opt out mechanism
* Only log when server side rendering
* Only log message once per page load
    * Unsure if this would avoid excess logging during unit tests though
* Remove the Stylis “linting” plugins from the default cache implementation and make them opt-in
* Use linter/stylelint instead
    * Rules then become user configurable as ignored, warning, or error
    * Create and document a stylelint-config-emotion package

__Additional Considerations__

* Our product is an open-source component library, as opposed to an application, so preferably any solution will not place an additional configuration burden on downstream consumers.

_Lastly, thank you for all of your efforts in creating and maintaining this project, which solves a lot of our problems!_

**Comment by brentertz** [comment] 2019-01-28 15:47
@Andarist Do you have any thoughts on my comments [above](https://github.com/emotion-js/emotion/issues/1105#issuecomment-457259458)?

**Comment by brentertz** [comment] 2019-02-01 13:43
Hi @Andarist Thank you for your attention.

I am aware of [that issue](https://github.com/emotion-js/emotion/issues/1178) and even link to it in my [comments above](https://github.com/emotion-js/emotion/issues/1105#issuecomment-457259458). I'd be happy to comment on it further following this message.  _For full transparency, @kylegach and I work together._  

Whilst Emotion's SSR implementation is certainly at the heart of this issue, I would imagine that is a bigger issue to resolve and I did not want to presume that you would be open to making changes in that area.

In the mean time, I believe that finding a way to resolve this issue would provide immediate value to many Emotion users.  I understand not wanting to put a lot of work into it if changing the underlying implementation could just make this issue go away, but what if it could be resolved with minimal effort and minimal impact?

I recently added another possible solution to the list in my [comment above](https://github.com/emotion-js/emotion/issues/1105#issuecomment-457259458), which feels pretty lightweight. I'll reiterate it here.  
* Adjust the Stylis "linting" plugin to support a special style property that allows the message to be suppressed. [See example gist](https://gist.github.com/kylegach/88aa7c189b90bb2c999e6484be5fa57d/revisions)

**Comment by Andarist** [comment] 2019-02-02 20:12
Unfortunately this is tightly coupled to SSR concerns - especially for your use case. From what I understand you develop a UI library which uses emotion and ideally your consumers shouldn't be aware of emotion and they should be able to do SSR without suffering the FOUC.

**Comment by RoystonS** [comment] 2019-03-12 16:29
Whilst #1209 is a 'minimal' change to emotion, it's not a 'minimal' change for a user: it requires _each use_ of a `:first-child` selector to be flagged with a really long "emotion-disable-server-rendering-unsafe-selector-warning-please-do-not-use-this-the-warning-exists-for-a-reason" string.  (This would bloat my output bundles in a rather unpleasant way.)

Isn't it the environment (SSR or not) that determines whether those selector usages are safe or not, rather than the individual uses? e.g. I'm using this in an environment that goes nowhere near SSR, so I'd much rather just tell emotion/stylis/cache/whatever _once_ (not _once per use_) that it's safe to use these selectors.

**Comment by brentertz** [comment] 2019-03-12 17:49
@RoystonS I agree with you.  We had to work within the constraints of what the maintainers would allow.  IMHO, #1209 is a workaround and the real way to solve this issue is to not break standard CSS.

FWIW, you can always [assign the string to a variable](https://github.com/mineral-ui/mineral-ui/blob/80cb8860fdacbe14a0eba09d53a26e9bc4ac4e3d/src/library/Button/styled.js#L45). Also, the obnoxiously long comment is stripped from the build, so it should not affect your bundle size at all.

**Comment by RoystonS** [comment] 2019-03-12 19:09
Yeah, I started putting it into a var, but then realised it was simpler just to adjust our build process to patch `@emotion/cache` (before we run webpack) to remove the warning.  Not really an option for library authors, of course...

You mentioned the comment being stripped from the build - what would do that?  It's a comment inside a string, so a minifier wouldn't know it can be removed... (And there's another copy inside `@emotion/cache` itself. :-( so my hack-the-package before build wins on both counts. :-) )

**Comment by brentertz** [comment] 2019-03-12 22:11
@RoystonS My mistake, it feels like ages since I worked on this issue. The strings do remain in the bundle, though the effect could likely be minimized using process.env.NODE_ENV.  It sounds like you are using a better solution for non-library authors anyway. :)

**Comment by ahutchings** [comment] 2019-03-27 14:41
> You mentioned the comment being stripped from the build - what would do that? It's a comment inside a string, so a minifier wouldn't know it can be removed...

My team is running into this issue. babel-plugin-emotion auto-minifies emotion CSS, stripping comments in the process. There doesn't appear to be an option to disable stripping comments, so unfortunately the comments to suppress the "unsafe selector" noise only work when not using the babel plugin (likely only in development). My team is using the babel plugin in tests for autolabeling and source maps, so we're seeing the warnings and there is no apparent way to suppress them. Until the larger issue is resolved (#1178), there are a few ways to mitigate this:

1. Only check for and warn about unsafe selectors in development (some sort of flag/option for @emotion/cache, environment variable, etc).  Maybe less code could be shipped to prod this way?
2. Add an option to babel-plugin-emotion to disable stripping all comments.
3. Update babel-plugin-emotion to be aware of the "unsafe selector" comment and leave it in place automatically.

@mitchellhamilton @kylegach Do either of you have any thoughts around this?

**Comment by kylegach** [comment] 2019-03-27 14:58
@ahutchings — The [code](https://github.com/emotion-js/emotion/blob/master/packages/cache/src/index.js#L201-L230), both to check and to warn, is wrapped in a not-prod check ([line 174](https://github.com/emotion-js/emotion/blob/master/packages/cache/src/index.js#L174)), so (1) is already the case.

I'll let Mitchell weigh in on the other points.

For clarification, I slightly misinterpreted Royston's comment earlier. I meant to say that the suppress comment is stripped in the _output CSS_; he is correct that it is still in the bundle itself (unless running babel-plugin-emotion, as you've discovered).

**Comment by ahutchings** [comment] 2019-03-27 15:19
@kylegach Thanks, I missed that check at the top. Do you have a suggestion for how we can use the suppression comment when running unit tests in Jest (along with the babel plugin), where NODE_ENV is set to "test" automatically by the runner?

We're also developing a component library, and would like for our users to be able to take advantage of emotion source maps (provided by the babel plugin) in development without seeing the unsafe selector errors, but I suppose that is more the larger issue that needs to be resolved (#1178).

**Comment by kylegach** [comment] 2019-03-27 15:31
@ahutchings — I don't, and I'm fairly sure a fix would require a code change in either the babel plugin or (somehow) the cache package. We don't run the plugin in our tests, so we missed this issue. Sorry about that.

Agreed that addressing the larger issue of having unreliable selectors at all would be a better long-term solution.

**Comment by kylegach** [comment] 2019-03-27 17:50
@ahutchings — I think this may be more nuanced than we've discussed so far. Here's a [codesandbox](https://codesandbox.io/s/yp5xm09zm9) running our components, which have multiple unreliable selectors (e.g. [in Button](https://github.com/mineral-ui/mineral-ui/blob/master/src/library/Button/styled.js#L45)) and are using the plugin ([via babel-preset-css-prop](https://github.com/mineral-ui/mineral-ui/blob/master/babel.config.js#L71-L76), which includes babel-plugin-emotion). If you open the console, you can see that it's not running in production mode, but there are no selector warnings logged.

I think this means it's at least possible to get the desired behavior in a test environment, but I'm not sure what about your setup is causing the issue to be sure.

**Comment by ahutchings** [comment] 2019-03-27 19:44
@kylegach Thanks for your prompt responses and for looking into it further. The "ignore" comments are still in place in the version of mineral-ui pulled down in the sandbox, so the warning is not logged. The babel plugin may be leaving the "ignore" comments in place due to the way the comments are defined in mineral-ui source (object-based styles with a computed property + reference to the ignore string).

`js
 _objectSpread2['& [role="img"]:first-child' + _emotion.ignoreSsrWarning]
`

We are using the tagged-template-literal-based method of defining styles in our components library, and the comments are stripped out whether we define them inline or using a reference to the "ignoreSsrWarning" variable like mineral-ui does.

**Comment by kylegach** [comment] 2019-03-28 02:35
@ahutchings — Ahh, the meaningful difference is the object styles vs. tagged template literal styles. I'm unsure how to proceed from here, but I suggest starting with a new, dedicated issue to keep the conversation focused going forward. It still seems to me like the plugin code would need changed for the fix. I know stylis, which emotion uses to parse styles, already strips comments before outputting CSS, so it's redundant (and problematic) for the plugin to do the same.

**Comment by nelsonlaquet** [comment] 2019-05-10 14:15
This is a pretty serious limitation. I understand it has to do with <style> elements being added inline in the DOM when doing SSR; is it at all possible for emotion to... not do that?

I've been using emotion for a whole of a week and have ran into this issue multiple times, where using :first-of-type isn't a valid substitute. To get around this issue I've had to add superfluous <div> elements, which clutter the DOM unnecessarily, and complicate the use of my components.

**Comment by antoinerousseau** [comment] 2019-07-03 09:19
Anyone knows if this happens using styled-components too? Or is it emotion-specific?

**Comment by Andarist** [comment] 2019-07-03 09:25
@antoinerousseau AFAIK styled-components may suffer from the same FOUC as emotion when using React's stream rendering, but they don't warn you about it.

**Comment by Andarist** [comment] 2019-10-25 10:30
You can disable currently this by using comment in your styled:
```js
css`
  :first-child /* emotion-disable-server-rendering-unsafe-selector-warning-please-do-not-use-this- 
 the-warning-exists-for-a-reason */ {
    color: hotpink;
  }  
`
```

**Closed by Andarist** 2019-10-25 10:30 UTC

**Comment by vdh** [comment] 2019-10-29 04:07
For anyone else who's like me and has been saddled with this opinionated log spam just because you decided to use a dependent like Storybook (e.g. Did not choose Emotion directly and have no current desires to combine Emotion with anything server-side), here's a (very hacky) workaround via a Webpack loader:
```
{
  test: /node_modules\/@emotion\/cache\/(src|dist)/,
  loader: "string-replace-loader",
  options: {
    search: "if (unsafePseudoClasses",
    replace: "if (false && unsafePseudoClasses",
  },
}
```
It's rather irritating though that I have to resort to monkey patching something that could have easily been a config flag…

**Comment by bradleyayers** [comment] 2019-11-15 03:50
@Andarist I've tried using the comment but it silently breaks the CSS in some cases, e.g.

```js
const Wrapper = styled.div({
  display: "grid",
  gridGap: "0",
  gridTemplateColumns: "1fr",
  margin: "0 -32px",
  maxWidth: `calc(100% + 96px)`,
  "& > *": {
    padding: "32px",
  },
  [`&& > :nth-child(n+2) ${IGNORE_SSR_FLAG}`]: {
    borderTop: `1px solid ${BORDER_COLOR}`,
  },
  [`@media (min-width: ${BREAKPOINT_PHABLET}px)`]: {
    gridTemplateColumns: "1fr 1fr",
    "& > *": {
      borderTop: `1px solid ${BORDER_COLOR}`,
      borderLeft: `1px solid ${BORDER_COLOR}`,
    },
    "&& > :nth-child(-n+2)": {
      borderTop: "none",
    },
    "&& > :nth-child(odd)": {
      borderLeft: "none",
    },
  },
  [`@media (min-width: ${BREAKPOINT_TABLET}px)`]: {
    gridTemplateColumns: "1fr 1fr 1fr",
    "& > *": {
      borderTop: `1px solid ${BORDER_COLOR}`,
      borderLeft: `1px solid ${BORDER_COLOR}`,
    },
    "&& > :nth-child(-n + 2)": {
      borderTop: `1px solid ${BORDER_COLOR}`,
    },
    [`&& > :nth-child(odd) /* emotion-disable-server-rendering-unsafe-selector-warning-please-do-not-use-this- 
 the-warning-exists-for-a-reason */`]: {    <---------- this ignore
      borderLeft: `1px solid ${BORDER_COLOR}`,
    },
    "&& > :nth-child(-n + 3)": {
      borderTop: "none",
    },
    "&& > :first-child, && > :nth-child(3n + 1)": {   <---- this rule escapes the @media
      borderLeft: "none",
    },
  },
});
```

**Comment by Andarist** [comment] 2019-11-15 12:37
@bradleyayers this is a bug in the parser we are using, I've reported it there https://github.com/thysultan/stylis.js/issues/152

**Comment by frankdilo** [comment] 2019-11-22 04:00
any update on this?

**Comment by Andarist** [comment] 2019-11-22 09:23
@frankdilo 

are you asking about this?
> Cannot turn off "potentially unsafe when doing server-side rendering" noise

If yes - then you can either use suppressing comment or wrap your application within a CacheProvider from emotion package (or just a custom cache created with `@emotion/cache` with a `compat` flag set on it).

**Comment by frankdilo** [comment] 2019-11-22 09:39
@Andarist yeah was referring to that, having an hard time figuring out how to do what you suggested

**Comment by Andarist** [comment] 2019-11-22 23:05
Option 1
```js
css`
  :first-child /* emotion-disable-server-rendering-unsafe-selector-warning-please-do-not-use-this-the-warning-exists-for-a-reason */ {
    color: hotpink;
  }
`
```
Option 2
```js
import { CacheProvider } from '@emotion/core'
import createCache from '@emotion/cache'

const myCache = createCache()
myCache.compat = true

<CacheProvider value={myCache}>
  <App/>
</CacheProvider>
```
Option 3
```js
import { cache } from 'emotion'

<CacheProvider value={cache}>
  <App/>
</CacheProvider>
```

**Comment by frankdilo** [comment] 2019-11-23 00:57
Thanks, this did not work for me because I am using emotion inside a library, but hinted me in the right direction. What would be the best approach to silence those warnings for a library?

**Comment by Andarist** [comment] 2019-11-23 07:34
Are u a library author or its consumer?

**Comment by frankdilo** [comment] 2019-11-23 09:11
Author (it’s a private library only user for client side rendering)

**Comment by Andarist** [comment] 2019-11-23 09:14
Then I would go with option 1 as it allows for a low-level control over this for library authors.

**Comment by frankdilo** [comment] 2019-11-23 12:32
That’s what we did in the end. Thanks.

I suggest to change that comment flag name (it’s too verbose and annoying to use if you have multiple instances of first-child).

**Comment by billyvg** [comment] 2020-01-02 19:24
Option 2 fails for us:

```
TypeError: cache.insert is not a function
    at insertStyles (utils.browser.esm.js?b750:33)
    at eval (styled-base.browser.esm.js?5220:108)
    at updateContextConsumer (react-dom.development.js:15197)
    at beginWork (react-dom.development.js:15363)
    at performUnitOfWork (react-dom.development.js:18150)
    at workLoop (react-dom.development.js:18190)
    at renderRoot (react-dom.development.js:18276)
    at performWorkOnRoot (react-dom.development.js:19165)
```

Options 2 and 3 would not work well for our tests, would require changes to ignore a warning that does not affect us since we do not use server-side rendering.

**Comment by Andarist** [comment] 2020-01-02 21:46
@billyvg could you prepare a repro case? Hard to tell what's wrong from the given information.

**Comment by robinmetral** [comment] 2020-01-07 11:05
Option 2 fixed it for me, I was having these warnings when running Jest+RTL tests and adding a test wrapper with a `CacheProvider` fixed it:

```js
import { CacheProvider } from '@emotion/core'
import createCache from '@emotion/cache'

const emotionCache = createCache()
emotionCache.compat = true

<CacheProvider value={emotionCache}>
  /* run tests here */
</CacheProvider>
```

@Andarist could you provide more insight on what `emotionCache.compat = true` does? I haven't found docs for this in the [Emotion cache docs](https://emotion.sh/docs/@emotion/cache).

**Comment by billyvg** [comment] 2020-01-10 23:51
@Andarist So, the issue is we are turning `speedy` off via

```
  const sheet = require('emotion').sheet; // eslint-disable-line emotion/no-vanilla
  sheet.speedy(false);
```

Is there an updated method to turn speedy off?

**Comment by viridia** [comment] 2020-02-13 20:34
Recently one of my developers encountered this warning, and not knowing any better proceeded to follow the recommendation, replacing 'first-child' with 'first-of-type'. As you might expect, this completely broke our app's layout (because first-of-type is in no way a substitute for first-child) and wasted a lot of people's time.

I mention this because I want folks to understand the kind of damage a carelessly worded warning message can cause.

**Comment by viridia** [comment] 2020-05-02 22:14
Is there not a simple way to disable this in jest tests? I have no interest in server-side rendering, first-child is an extremely useful feature (and first-of-type is no substitute, the advice in the error message is bad).

I've tried some of the recipes mentioned in the thread but they don't work since the package structure of emotion is different now (e.g. there's no require('emotion') any more.) Other engineers on my team have been complaining about this for 6 months now, and I keep coming back to this thread. :(

**Comment by Andarist** [comment] 2020-05-02 22:19
@viridia you can set `cache.compat = true` (you would have to create it first and provide it to emotion through CacheProvider) or provide emotion's cache as described here: https://emotion.sh/docs/migrating-to-emotion-10#manual-steps

**Comment by viridia** [comment] 2020-05-02 23:47
@Andarist I'm running component unit tests in Jest, there is no app - where does the CacheProvider go?

**Comment by Andarist** [comment] 2020-05-03 06:13
Just wrap your tested component with it

**Comment by viridia** [comment] 2020-05-03 18:16
@Andarist OK that worked - or rather, I wrote a wrapper around react-testing-library's 'render' function that added the CacheProvider. Thanks!

**Comment by boycce** [comment] 2020-07-09 19:58
Any update on this?

**Comment by amcsi** [comment] 2020-10-02 09:33
So what am I expected to do then if I want to make child components have gaps (every non-first child should have a margin-left) when some child components may optionally be `<a>` rather than `<div>` tags?

Either the emotion compiler will yell at me if I don't use `:first-of-type` rather than `:first-child`, or ESLint yells at me for a11y violations if I make all divs wrapped in an `<a>` tag so all children would be the same type.

**Comment by rdjpalmer** [comment] 2020-10-02 16:16
@amcsi Rather than wrapping the div in an anchor, have you tried inverting that logic, so that all children are divs, e.g.:

```
<div />
<div><a /></div>
<div>
```

On the styling side, if you apply the same styling to each, you can do the following instead:

```
& + & {
  margin-left: 1rem;
}
```

**Comment by Andarist** [comment] 2020-12-11 16:18
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by Dajust** [comment] 2020-12-11 23:49
@sebastianfast is right, `createCache`  function in v11 requires some cache-key configuration that must be lower case alphabetical. 

![image](https://user-images.githubusercontent.com/8015514/101962921-9d865500-3c0d-11eb-8054-3f77db8d133b.png)

![image](https://user-images.githubusercontent.com/8015514/101962986-d8888880-3c0d-11eb-92a2-25a30af00676.png)

And using the cache from `@emotion/css`  kinda fixes that. Looking at  [the docs](https://emotion.sh/docs/@emotion/cache#key), this config should have been optional.

However, because mixing `@emotion/css` with v11's `@emotion/react` doesn't just feel right to me, I decided to simply pass to `createCache` function a random key config value like so:

```
const emotionCache = createCache({ key: 'my-lower-case-alphabetical-cache-key' });
emotionCache.compat = true;
```

And that worked for me.

**Comment by seafoam6** [comment] 2021-07-22 15:34
Hey everyone, I just figured out a dirty way of getting rid of this irritating warning. 

```js
export const disableEmotionWarnings = () => {
  if (!process.env.NODE_ENV === "development") {
    return;
  }
  /* eslint-disable no-console */
  const log = console.error.bind(console);
  console.error = (...args) => {
    /* eslint-enable no-console */
    if (
      args.indexOf("The pseudo class") &&
      args.indexOf(
        "is potentially unsafe when doing server-side rendering. Try changing it to"
      )
    ) {
      return;
    }
    log(...args);
  };
};
```

**Comment by codephunk** [comment] 2021-07-31 14:25
> Hey everyone, I just figured out a dirty way of getting rid of this irritating warning.
> 
> ```js
> export const disableEmotionWarnings = () => {
>   if (!process.env.NODE_ENV === "development") {
>     return;
>   }
>   /* eslint-disable no-console */
>   const log = console.error.bind(console);
>   console.error = (...args) => {
>     /* eslint-enable no-console */
>     if (
>       args.indexOf("The pseudo class") &&
>       args.indexOf(
>         "is potentially unsafe when doing server-side rendering. Try changing it to"
>       )
>     ) {
>       return;
>     }
>     log(...args);
>   };
> };
> ```

Thank you! Works like a charm.
But i think the first if should look like this, otherwise the result will always be false.
```js
if (process.env.NODE_ENV !== "development") {
```

**Comment by roeycohen** [comment] 2021-08-30 06:07
hi @seafoam6, the string check should be args[0]

**Comment by coolassassin** [comment] 2022-02-04 11:54
> Hey everyone, I just figured out a dirty way of getting rid of this irritating warning.

Hello, I have tried this code and it breaks all `console.error` calls.
And I can explain you why.
The argument `args` is an array, but you work with it like with string.
Also using indexOf as is, it is a potential bug, which we can see here.
If something not matching the case we have -1 in both cases and `!!(-1 && -1) === true`

So I see comments bellow about your mistakes, but you didn't fix them.
So, that is the right one to avoid mistakes for guys like me:
```javascript
export const disableEmotionWarnings = () => {
  if (!process.env.NODE_ENV !== 'development') {
    return;
  }
  const log = console.error.bind(console);
  console.error = (...args) => {
  if (
    args[0] &&
    args[0].includes('The pseudo class') &&
    args[0].includes('is potentially unsafe when doing server-side rendering. Try changing it to')
  ) {
    return;
  }
  log(...args);
  };
};
```

**Comment by Andarist** [comment] 2022-03-03 16:21
You can also disable those warnings by setting `.compat = true` on a cache.

**Comment by caedney** [comment] 2022-05-13 12:54
For anyone still experiencing this problem, I was able to work around this issue by essentially recreating `:first-child` with `:first-of-type` :

```
& > :first-of-type:not(style):not(:first-of-type + *),
& > style + * {
    margin-top: 0;
}
```

Hope this helps.

**Comment by Slapbox** [comment] 2022-06-29 23:29
@Andarist is there no way to disable this without the need for a custom cache? It's rather onerous.

**Comment by Slapbox** [comment] 2022-07-01 21:16
Fyi @caedney that style rule is going to be quite taxing on the CPU compared to `:first-child`.

I think that a simpler way to disable this should be a goal for Emotion 12.

**Comment by Schnueggel** [comment] 2022-08-09 08:50
Its really funny that after all this years there is no real solution to this.

**Comment by kinoli** [comment] 2022-08-27 14:50
You can check if you are in Jest and only include the pseudo code if you are not in jest. This works for me.

``` 
${!process.env.JEST_WORKER_ID
      ? css`
          *:first-child {
            margin-top: 0;
          }

          *:last-child {
            margin-bottom: 0;
          }
        `
      : null}
```

**Comment by Hideman85** [comment] 2023-06-23 17:04
Do we have a solution for this really really annoying log? We are not concerned at all about SSR today and we are annoyed all the time with this "Warning" that is even an error 🤦‍

Please can I mute this at the source? Thanks 🙏

**Comment by allpro** [comment] 2023-09-17 17:26
I appreciate the emotion library and the developers who put so much work into it. However, it is time all library authors learn that **it is up to developers to decide their project's coding practices**. It is arrogant for a 'library' to presume it knows best for every use-cases. This is a trend that needs to stop. The many complaints in this thread, over a 5 year period, illustrate how highly annoying this is.

Such 'hints' are useful, but there should be easy-to-use options. The ideal scenario is granular control, such as eslint-style rules, so that developers get to decide which warnings are appropriate and which are not. Ideally the severity (warning vs error) could also be configured. The message in this thread notes that it is only "potentially unsafe", yet it still _shouts_ at devs as a console 'warning'. _At a minimum_ this should only be a 'warning'.

This non-applicable error caused some of my devs to change the _accurate and superior_ use of `:first-child` with `:first-of-type`. This made the CSS less clear, and in at one case created a bug. Teaching the developers in my team how to write CSS is my job, not this library's.

Again, thanks to all the maintainers of this library. However as the years of feedback above indicates, a more refined approach to such messaging would be a great improvement. I'm glad I found the `compat` option here, but this seems like a sledgehammer solution to a nuanced problem. It also seems this is _still_ too hard to find for many users.

**Comment by christiaanwesterbeek** [comment] 2024-01-10 15:17
If I understand correctly I need to create an EmotionCacheProvider and wrap my app with it. I am afraid the app will end up with 2 caches. This one and some internal one by MUI. Since I have no idea what the Emotion Cache is and I don't want to dive into it, I add the following to my app which silences the error also.

```
const consoleError = console.error;

console.error = function filterErrors(msg, ...args) {
    if (/server-side rendering/.test(msg)) {
        return;
    }
    consoleError(msg, ...args);
};
```

Copied from here https://github.com/oliviertassinari/react-swipeable-views/issues/534#issuecomment-1396138110 and adjusted...

**Comment by dvegap95** [comment] 2024-10-21 12:17
About the :first-of-type approach, I have a button that can have an Icon beside text, I use [role='figure']:first-child so if it appears at the begining gets a different margin on the left, I cannot do this with :first-of-type, cuz I would still have the appended icon with a margin left applied, since it would be the first image within the button. :first-child is the way to go here, I don't use SSR, why should it even mention SSR without any context?

**Comment by phiter** [comment] 2024-11-14 20:12
I don't understand why this is still a thing. We don't use SSR and yet this error is still present.

**Comment by yaindrop** [comment] 2024-11-26 02:00
Continuing the discussion from the previous comments I figured out that this modification of `console.error` is more considerate. By using `useEffect` clean-up function it will prevent unnecessary multiple wraps around the original `console.error` if the function is executed multiple times, for reasons like the live-reloading of the dev server.

```typescript
function filterConsoleError(): (() => void) | undefined {
  if (process.env.NODE_ENV !== 'development') {
    return
  }
  const consoleError = console.error.bind(console)
  console.error = (...args: string[]) => {
    const emotionErrorUnsafeSsr = /The pseudo class "[^"]+" is potentially unsafe when doing server-side rendering/g
    if (emotionErrorUnsafeSsr.test(args[0])) {
      return
    }
  }
  return () => {
    console.error = consoleError
  }
}

function App() {
  useEffect(() => {
    return filterConsoleError()
  }, [])
  ...
}
```

Again, although I do appreciate the work of this library's authors, it's really a shame that we are ending up discussing hacky modification of the `console.error` for this trivial issue. The [recommended options](https://github.com/emotion-js/emotion/issues/1105#issuecomment-557726922) are clearly inappropriate when it's not in a SSR use case, as [frankdilo](https://github.com/emotion-js/emotion/issues/1105#issuecomment-557794163) and [allpro](https://github.com/emotion-js/emotion/issues/1105#issuecomment-1722524968) have persuasively pointed out.

**Comment by andreashouben** [comment] 2025-02-14 06:20
To whom it may concern, [this blog article](https://ermakovich.ru/posts/2024-02-28-nth-child-is-potentially-unsafe/) pointed me to the solution that you can replace `:nth-child` with `:nth-of-type` which (at least in my case) works as well but doesn't produce the error.

Maybe that helps someone :)

**Comment by Nantris** [comment] 2025-02-15 03:50
> you can replace :nth-child with :nth-of-type

It's literally in the warning text.

**Comment by amcsi** [comment] 2025-02-15 06:53
> > you can replace :nth-child with :nth-of-type
> 
> It's literally in the warning text.

Not if you're using mixed elements.
