### ISSUE TITLE
css Prop on Web Components

### ISSUE THREAD

**Issue by trisys3** [emotion-js/emotion#1071] opened 2018-12-04 15:40 UTC
- `emotion` version: @emotion/core version 10.0.0.2
- `react` version: 16.6.3

Relevant code.

```javascript
/** @jsx jsx */
import {jsx} from @emotion/core;

const myStyles = {
    color: 'blue',
};

function MyElement() {
    return <div css={myStyles}>
        {'I get styles applied.'}
    </div>
}

function MyWebComponent() {
    return <my-element css={myStyles}>
        {'I don't get styles applied.'}
    </my-element>;
}
```

What you did:

I tried to use the `css` prop on a custom, non-react HTML element.

What happened:
The styles detailed in the `css` prop aren't applied. I'm pretty sure `emotion` doesn't even look at the `css` prop.

No error messages, as nothing is technically wrong. The styles are just not applied.

Reproduction:

https://codesandbox.io/s/522r51qrr4

Problem description:

Using the `css` prop on web components, as above, doesn't seem to apply the styles, whereas the same prop on, for example, `div`s and `span`s, does apply the styles.

I was thinking maybe this is a similar situation to how web components need `class` whereas `div`s need `className`, but I don't think so, as the reason for `className` being needed was because "class" is a restricted word. I'm still not entirely clear on why `class` is used on web components, or how `react` gets around the restricted syntax issue. Regardless, "css" is not a restricted word in JavaScript, at least not yet.

I think I can use `style`, but I'm not sure what sorts of transformations are done specifically for the `css` attribute.

Suggested solution:

Treat the `css` prop the same way on web components as on "regular" elements like `div`, `span`, `svg`, etc.

**Comment by Andarist** [comment] 2018-12-04 16:40
Codesandbox with the issue would be really helpful - we could get to fixing the issue right away

**Comment by trisys3** [comment] 2018-12-04 17:01
I added a sandbox.

**Comment by Andarist** [comment] 2018-12-04 19:44
Thank you! I’ve found the issue but still investigating how to fix it.

**Comment by Andarist** [comment] 2018-12-05 08:14
Working demo with bare emotion - https://codesandbox.io/s/z2zlpvl99m

I understand that this might be not what you are looking for - but I'm not yet sure how to solve this properly. 

The problem is that for custom elements (web components) we have to use `class` prop instead of the `className` - that's how React works (in short - this [predicate function](https://github.com/facebook/react/blob/c954efa70f44a44be9c33c60c57f87bea6f40a10/packages/react-dom/src/shared/isCustomComponent.js) tells React if it should consider an element as web component or not). 

We can replicate the React's logic - but our `jsx` can't know what is the real underlaying tag name without a user hint. What I mean - we can detect this for:
```js
<my-element css={{color: 'blue'}}/>
```
but cant quite do it for
```js
const Foo = (props) => <my-element {...props}/>

<Foo css={{color: 'blue'}} />
```

cc @mitchellhamilton

**Comment by trisys3** [comment] 2018-12-05 11:35
Thanks. I personally haven't ever used `...props`, but I can see how it would be useful.

**Comment by Andarist** [comment] 2018-12-05 12:00
This is a bummer, that both primitive types have to be treated differently 🤔 a good thing is that there is some chance that React Fire will resolve this by switching over to `class` (from `className`) for builtin elements. This is a song of the future though so it would be good to find a temporary solution. We can always do the right thing when possible and recommend manual `className` to `class` conversion when we can't detect it automatically, so it would look like this:
```js
const Foo = ({ className, ...props }) => <my-element {...props} class={className}/>

<Foo css={{color: 'blue'}} />
```

**Comment by trisys3** [comment] 2018-12-05 15:17
I'm still not quite sure I understand. Is passing down the `css` attribute via props possible, even for a custom element? Will `emotion` still add the styles? I don't personally care about `class` vs. `className` for this plugin, I can handle that myself. Sorry if my mention of `className` in the question confused you, that wasn't part of this bug.

**Comment by Andarist** [comment] 2018-12-05 15:46
It doesnt handle it right now because u try to render custom element directly with jsx. We can handle this case in jsx though.

Right now u can wrap ur custom element in a wrapper component, render it and translate className props on ur own. Smth like:

const Wrapper = ({ className, ...props }) => <my-element {...props } class={className} />

<Wrapper css={{color: ‚blue’}} />

Im going to work on a fix for this some time later

**Comment by trisys3** [comment] 2018-12-05 16:44
Thanks, this is what I wanted. I don't personally care about `class` vs. `className`, and tbh I'm not sure if that logic should be in `emotion`, although that obviously isn't up to me.

I'll eagerly await your update :smile:

**Comment by Andarist** [comment] 2018-12-09 10:30
We've decided no to pursue fixing this at the moment ( https://github.com/emotion-js/emotion/pull/1089#issuecomment-445506886 ). Especially that we just can't cover all use cases on our side. 

The best what you can do to support it at the moment is the `Wrapper` compat layer like above.

**Closed by Andarist** 2018-12-09 10:30 UTC

**Comment by trisys3** [comment] 2018-12-09 23:56
Sorry I got all confused when asking this question, you can tell I know pretty much nothing about `emotion`'s internals.

One last thing - I used `@emotion/core` in my example, with its `jsx` function and the `css` attribute, but I noticed in your counter-example, when you used the `class` & `className` attributes and the `css` function, you needed regular `emotion`. When I was experimenting, the `css` function from `@emotion/core` indeed didn't work, even with `jsx`. Why? Why aren't the 2 `css` functions the same?

Also, is this another, supported way to get class names, without using the `ClassNames` component? What I mean by "supported" is, is it not deprecated, and is it recommended? The `ClassNames` component is kind of a hassle.

I can ask this as another issue, it's just that it's so tied to this issue.

**Comment by Andarist** [comment] 2018-12-10 09:48
https://emotion.sh/docs/migrating-to-emotion-10#thinking .

I've used bare emotion just because I was experimenting with className/class thing. You can look at full example using `@emotion/core` here https://codesandbox.io/s/6y1xw19l7n

> Also, is this another, supported way to get class names, without using the ClassNames component? What I mean by "supported" is, is it not deprecated, and is it recommended? The ClassNames component is kind of a hassle.

Not quite - you shouldnt use `ClassNames` that often though. Most of your app should be written using single styling solution (emotion in this case) and `ClassNames` is intended only as bridge component when you need to integrate with non-emotion world.

**Comment by jooj123** [comment] 2019-05-14 10:52
> Most of your app should be written using single styling solution (emotion in this case) and ClassNames is intended only as bridge component when you need to integrate with non-emotion world.

There is alot of scenarios you need to integrate with non emotion 3rd party react components, so I wouldnt exactly call it a bridge component - often its a necessity and there isnt another elegant work around :(

**Comment by hedgepigdaniel** [comment] 2019-09-12 07:18
Would be great if this was revisited at some point.

My use case is large old web app where a common way we have scoped styles to react components is by using a element name selector around all the styles

```scss
my-component-name {
  // These styles don't leak out and affect other components

  // ... styles
}
```

This issue makes it significantly more difficult to start using emotion in these components.
