### ISSUE TITLE
"Advanced approach" SSR with Next broken with `react-dom` 18

### ISSUE THREAD

**Issue by garronej** [emotion-js/emotion#2725] opened 2022-04-16 00:44 UTC
Hi,  
Again, thank you for your work on Emotion, it's a fantastic library.  

UPDATE: Scroll down to [this message](https://github.com/emotion-js/emotion/issues/2725#issuecomment-1100983035), it better describe the issue.

**Comment by srmagura** [comment] 2022-04-16 01:19
Emotion inserts styles differently in React 18 to be compatible with React's new SSR streaming capabilities.

Could you explain what the _expected behavior_ vs. _actual behavior_ is for **Emotion** in the context of React 18? Ideally you would also provide a minimal reproducible example.

BTW, I tried running your project on Windows but could not because of the Unix-specific scripts.

**Comment by garronej** [comment] 2022-04-18 00:36
Hi @srmagura thank you for your answer,  

As I am sure you are aware [MUI](https://mui.com/) is using emotion.  
With MUI, [0-config SSR isn't supported](https://github.com/mui-org/material-ui/issues/24109#issuecomment-780857501), to enable SSR, MUI users are expected to explicitly provide an emotion cache and manually insert the `<style>` tags in the `<head>` as described in the ["advanced approach" section of the emotion documentation](https://emotion.sh/docs/ssr#advanced-approach).  
You can find [here](https://github.com/mui/material-ui/tree/master/examples/nextjs) a canonical setup for MUI + Next.js.  This approach no longer works with react 18.
## Reproduce

I created a minimal repo to exhibit what is no longer working as it used to.  
Code: https://github.com/garronej/ssr-react-18-next  

Fist [**disable JavaScript**](https://www.delftstack.com/howto/javascript/disable-javascript-in-google-chrome-developer-tools/#disable-javascript-in-chrome-via-the-command-menu)

To run it:  
```bash
git clone https://github.com/garronej/ssr-react-18-next
cd ssr-react-18-next
yarn
yarn build
yarn start
#heads over to http://localhost:3000
```

You'll see:  
![image](https://user-images.githubusercontent.com/6702424/163737058-0f611ba0-6ee4-4a37-ad56-a66625d256a1.png)

Now, if you downgrade to `react-dom` `17.0.2` you'll get:  

![image](https://user-images.githubusercontent.com/6702424/163737114-38005849-4725-4fee-a133-e8d40420002f.png)

##  What's happening  

You can see [this `<style>` tag](https://github.com/garronej/ssr-react-18-next/blob/3b6fda6292eb46a8a23dea64d8dac4f151b1bce3/src/pages/_document.tsx#L21) inserted at the end of the `<head>` should take priority over `color: read` generated by `css` [here](https://github.com/garronej/ssr-react-18-next/blob/3b6fda6292eb46a8a23dea64d8dac4f151b1bce3/src/pages/index.tsx#L11).  

![image](https://user-images.githubusercontent.com/6702424/163737440-bb4f9026-0f3c-4613-a586-a1043ce664a7.png)

The red string tag is not generated with `react-dom` 17 and causes the `green` style to be overwritten.  

## My 2 sence  

If you run the app with `yarn dev` the bug happens only **the very first render** but we can see that with `react-dom` 18 unlike with `react-dom` 17 the `_app.tsx` is run twice and the first time it's before `getInitialProps()` of our custom_document.tsx` has been called.  

https://user-images.githubusercontent.com/6702424/163737911-882d47a7-903d-43f5-a7b9-8cf5f847ca3a.mov

In the hope that I solution can be found,  
Best

**Comment by srmagura** [comment] 2022-04-18 18:06
@garronej Thank you so much, that really clears it up.

The ["Advanced Approach"](https://emotion.sh/docs/ssr#advanced-approach) docs seem to be incomplete or incorrect for React 18 at the moment. Someone will need to do some testing with Next and MUI and either fix or add to that section in our docs.

Apart from the aforementioned documentation issue, I don't see anything Emotion is doing that is "wrong". My current feeling is that MUI is not compatible with the new streaming SSR, and that that is the underlying issue.

After reading the relevant code in Emotion (which is quite complex), I _think_ Emotion will always insert `<style>` tags into the `<body>` when using React 18, even if the Advanced Approach is used and SSR streaming is not used. _(I could be reading the code wrong though.)_ In React 17 when using the Advanced Approach, Emotion does not directly insert `<style>`  tags during SSR, but our docs recommend you manually place them in the `<head>`. 

Maybe we need to insert a toggle into Emotion to allow users to revert back to the React 17 behavior even when using React 18? I am thinking of this as a stopgap until MUI can fully support SSR streaming.

A lot of the discussion on https://github.com/mui/material-ui/issues/24109 is likely relevant to this.

**Comment by Andarist** [comment] 2022-04-19 08:24
I've created a Next.js issue about this [here](https://github.com/vercel/next.js/issues/36268).

As a workaround you set `clientSideEmotionCache.compat = true` [here](https://github.com/garronej/ssr-react-18-next/blob/3b6fda6292eb46a8a23dea64d8dac4f151b1bce3/src/pages/_app.tsx#L10). However, I think that the setup used in this repro case is slightly weird - you probably shouldn't use `CacheProvider` in your `MyApp`. When combined with `Document.getInitialProps` this will result in wrapping the whole thing twice with the `CacheProvider` and you don't pass the "outer" cache to the inner `CacheProvider` - I would suspect this leading to some unexpected results.

**Comment by Andarist** [comment] 2022-04-22 08:04
The created issue was closed by [this PR](https://github.com/vercel/next.js/pull/36352) so I will assume that this should get fixed with the next Next release.

**Closed by Andarist** 2022-04-22 08:04 UTC
Labels: bug, needs triage

**Comment by garronej** [comment] 2022-05-03 00:22
Hi,  
Next 12.1.6 just released.  
I confirm that it solves the issue.

**Comment by himadrinath** [comment] 2022-05-12 06:46
looks like the problem arrived again in canary release.
can any one confirm that

**Comment by garronej** [comment] 2022-05-12 23:11
Hi @himadrinath,  

I just tested with the current canary version,  
This specific issues is fixed, there is no regression.

However, there are other issues, see the warning of [tss-react](https://github.com/garronej/tss-react):  

> 🚨 WARNING: Next.js + React 18 -> Broken SSR.  
> This is **not** an issue specific to `tss-react` it affects MUI as a whole.  
> More specifically, there is currently no working configuration for Next.js + React 18 + Emotion [advanced approach](https://emotion.sh/docs/ssr#advanced-approach) (which is the only strategy supported by MUI).  
> Follow the advancement of the related issues on the [Next.js repo](https://github.com/vercel/next.js/issues/36675), on the [MUI repo](https://github.com/mui/material-ui/issues/32051) and on the [TSS repo](https://github.com/garronej/tss-react/issues/82).
