### ISSUE TITLE
Hangs on chrome dev tools performance timeline recording

### ISSUE THREAD

**Issue by stevemarksd** [emotion-js/emotion#1838] opened 2020-04-09 03:53 UTC
**Current behavior:**

Hangs on chrome dev tools performance timeline recording :

![image](https://user-images.githubusercontent.com/58653359/78855699-33eaf100-7a57-11ea-8627-751b7bf26e13.png)

Note: if I set `sourceMap` to false all works fine.

**To reproduce:**

1. add babel-plugin-emotion with sourcemaps in webpack ` ['babel-plugin-emotion', {sourceMap: isDevelopmentBuild, autoLabel:isDevelopmentBuild, labelFormat:`[filename]_[local]`}],`
2. Open dev tools
3. Run performance timeline

Babel config in webpack:

```

        {
          test: /\.(j|t)sx?$/,
          exclude: isProductionBuild && isServer ? undefined : /node_modules/,
          use: {
            loader: 'babel-loader',
            options: {
              cacheDirectory: true,
              babelrc: false,
              presets: [
                '@babel/preset-env',
                ['@babel/preset-typescript', {allowNamespaces: true}],
                '@babel/preset-react'
              ],
              plugins: [
                // To have `private` on class properties. `loose:true` to don't add bloat to the code.
                ['@babel/plugin-proposal-class-properties', {loose: true}],
                // Ability to do: `const enum`
                'babel-plugin-const-enum',
                // Ability to use typescript, has to be after 'babel-plugin-const-enum' otherwise will complain
                ['@babel/plugin-transform-typescript', {allowNamespaces: true}],
                ['babel-plugin-emotion', {
                  sourceMap: isDevelopmentBuild,
                  autoLabel: isDevelopmentBuild,
                  labelFormat: `[filename]_[local]`
                }],
                ifIs(isDevelopmentBuild, 'react-hot-loader/babel'),
              ].filter(isNotNullOrUndefined),
            },
          },
        },
```

**Expected behavior:**

To be able to work

**Environment information:**

```
    "babel-plugin-emotion": "^10.0.33",
    "emotion-theming": "^10.0.27",
    "@emotion/core": "^10.0.28",
    "@emotion/styled": "^10.0.27",
    "@babel/core": "^7.8.4",
    "@babel/plugin-proposal-class-properties": "^7.8.3",
    "@babel/plugin-transform-typescript": "^7.8.3",
    "@babel/polyfill": "^7.8.3",
    "@babel/preset-env": "^7.8.4",
    "@babel/preset-react": "^7.8.3",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-hot-loader": "^4.12.19",
```

**Comment by Andarist** [comment] 2020-04-09 10:34
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by davidhewitt** [comment] 2020-04-12 22:57
A repro for me is a media query, e.g. 

```
css`
  @media (min-width: 767px) { width: 100%; }
`
```
is enough to trigger this problem for me unless I disable the source maps.

Was quite a painful debugging session to figure out why profiling was broken!

**Comment by chenders** [comment] 2020-04-19 05:25
I think [this electron issue](https://github.com/electron/electron/issues/17772) is related. I ran into the same problem in storybook (not using electron). When I opened chrome devtools into a separate window, then opened devtools of the devtools (devtoolsception!) I saw this error/stacktrace on load and when attempting a timeline recording:

```
VM1910:1 TypeError: Cannot read property 'Symbol(_frameAttributionSymbol)' of null TypeError: Cannot read property 'Symbol(_frameAttributionSymbol)' of null
    at Function.removeFrameAttribution (://devtools/bundled/bindings/NetworkProject.js:10)
    at SASSSourceMapping._sourceMapDetached (://devtools/bundled/bindings/SASSSourceMapping.js:6)
    at SourceMapManager.dispatchEventToListeners (://devtools/bundled/common/Object.js:12)
    at SourceMapManager.detachSourceMap (://devtools/bundled/sdk/SourceMapManager.js:27)
    at CSSModel._styleSheetRemoved (://devtools/bundled/sdk/CSSModel.js:68)
    at CSSDispatcher.styleSheetRemoved (://devtools/bundled/sdk/CSSModel.js:94)
    at _DispatcherPrototype.dispatch (://devtools/bundled/protocol/InspectorBackend.js:94)
    at SessionRouter._onMessage (://devtools/bundled/protocol/InspectorBackend.js:54)
    at MainConnection._dispatchMessage (://devtools/bundled/sdk/Connections.js:5)
    at ObjectWrapper.dispatchEventToListeners (://devtools/bundled/common/Object.js:12)
```

Changing my babel config for `babel-plugin-emotion` to `sourceMap: false` got rid of the error in the devtools^2 console, and the timeline recording was no longer hanging. (It also seemed to fix the problem I was having that caused me to try to run the timeline recording in the first place - a simple storybook tab was using over 4GB of memory)

**Comment by Andarist** [comment] 2020-06-12 19:39
Well, it really seems like an Electron issue from what you write here, so I have really nothing else to do rather than closing this issue as non-actionable on our part.

**Closed by Andarist** 2020-06-12 19:39 UTC
Labels: bug, needs triage

**Comment by davidhewitt** [comment] 2020-06-12 20:34
@Andarist both OP and myself reproduced this in chrome (not electron). But it's possible it was a chrome bug since resolved.

**Comment by Andarist** [comment] 2020-06-13 07:30
Oh, sorry for misunderstanding the issue then - I thought this was purely about Electron.

Either way, I don't think this is actionable on our side. I have no idea what could we to in Emotion itself to improve the situation here 😕
