### ISSUE TITLE
CSS prop incompatible with typescript

### ISSUE THREAD

**Issue by cdock1029** [emotion-js/emotion#693] opened 2018-05-29 20:11 UTC
- `emotion` version: `9.1.3`
- `react` version: `16.4.0`
- `react-emotion`: `9.1.3`
- `react-app-rewire-emotion`: `4.0.0`
- `babel-plugin-emotion`: `9.1.2`
- `@types/react`: `16.3.4`
- `@types/react-dom`: `16.0.5`

Relevant code.

```javascript
class App extends Component {
  render() {
    return (
      <div
        className="App"
        css={`
          color: pink;
        `}
      >
        <p>hello world</p>
      </div>
    )
  }
}
```

**What you did:** 

try to compile `App.tsx`

**What happened:**  

Compilation error:
```
TS2339: Property 'css' does not exist on type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.
No lint errors found
Version: typescript 2.8.3, tslint 5.10.0
```

**Problem description:**

Typescript doesn't understand `css` prop.

**Comment by Ailrun** [comment] 2018-06-08 05:48
@cdock1029 Is this still relavant with 9.2.2?

**Comment by cdock1029** [comment] 2018-06-11 17:06
No this seems to be resolved with current version, thanks.

**Comment by Ailrun** [comment] 2018-06-11 17:20
Close this based on https://github.com/emotion-js/emotion/issues/693#issuecomment-396315083

**Closed by Ailrun** 2018-06-11 17:20 UTC
Labels: TypeScript

**Comment by aaronjensen** [comment] 2018-06-17 06:38
@Ailrun afaict this seems to not work w/ preact-emotion (thanks for typing that btw!)

**Comment by Ailrun** [comment] 2018-06-17 06:41
@aaronjensen Oh, really? I need to check Preact typing again.

**Comment by emattias** [comment] 2018-09-14 14:16
I had to add `react-emotion` to the `types` array in my `tsconfig.json`: (it works with `emotion` and `create-emotion` aswell)

```
"types": ["node", "react-emotion"]
```

for the addition of the `css` prop/attribute to the `HTMLAttributes` interface to be included: https://github.com/emotion-js/emotion/blob/v9.2.8/packages/create-emotion/types/index.d.ts#L94-L98

**Comment by karol-majewski** [comment] 2018-12-17 03:13
This definition now lives in the core package — so the entry in `tsconfig.json` should say ` "@emotion/core"` instead of `"react-emotion"`.

https://github.com/emotion-js/emotion/blob/34031439e084d68fa610b8491163618352fa9b97/packages/core/types/index.d.ts#L84-L88

**Comment by Kovensky** [comment] 2018-12-18 03:41
You're augmenting the wrong thing (rather, the compiler's JSX support is weird in _a lot_ of ways).

The augmentation you are looking for is `'react'`'s `Attributes`.

```ts
declare module 'react' {
  interface Attributes {
    css?: InterpolationWithTheme<any>
  }
}
```

**Comment by kentcdodds** [comment] 2018-12-18 03:43
Thanks @Kovensky! So you're saying that [this](https://github.com/emotion-js/emotion/blob/b966abd80cc4817cd27f2e4e6c7994cb2faf9043/packages/core/types/index.d.ts) should be `Attributes` not `DOMAttributes`?

I'll double check locally then I can make a PR for that. Thank you!

**Comment by Kovensky** [comment] 2018-12-18 03:44
Yeah, and you can leave the `namespace JSX` alone.

This is how I did it for `styled-components`, where we made the `css` prop's type opt-in:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/styled-components/cssprop.d.ts#L4-L19

**Comment by kentcdodds** [comment] 2018-12-18 03:47
Hmmm... That doesn't seem to be working for me. I'm trying to make the change to my local `node_modules` and it's still giving me the same error.

**Comment by BarryThePenguin** [comment] 2018-12-18 03:48
Do you need to specify the emotion jsx factory to use the `css` prop in emotion@10?

This compiles when I run `npx tsc`

```tsx
/** @jsx jsx */
import * as React from 'react'
import { jsx } from '@emotion/core'

export default () => (
  <React.Fragment>
    <div style={{marginTop: 10}}>style works</div>
    <div css={{marginTop: 10}}>css does not</div>
  </React.Fragment>
)
```

**Comment by Kovensky** [comment] 2018-12-18 03:51
@kentcdodds Right, `'react'` is only augmented if `'@emotion/core'` is imported at all. (Which is technically incorrect for emotion as you also need to use the pragma, but it's not currently possible to represent that in typescript.)

**Comment by kentcdodds** [comment] 2018-12-18 03:51
Thanks @BarryThePenguin! That does work but:

1. I have a babel plugin configuration which allows me to not have to import emotion's `jsx` function/specify the pragma
2. I'd prefer to be able to use the `<></>` fragment syntax.

Is there any way we can make this work while maintaining those two?

**Comment by kentcdodds** [comment] 2018-12-18 03:52
Thanks for the help friends :)

> Right, 'react' is only augmented if '@emotion/core' is imported at all.

I thought that we could force these typings to be included if we add the `types` configuration as I have in the the `tsconfig.json`. I'm pretty new to TS, so I may be misunderstanding something. Could I make custom global definitions for my project that are included to do this?

**Comment by Kovensky** [comment] 2018-12-18 03:53
@kentcdodds Oh, I just realized, your `"types"` are in the wrong object. It's not top-level, it should be inside `"compilerOptions"`.

**Comment by kentcdodds** [comment] 2018-12-18 03:56
Fantastic, thank you so much @Kovensky! That solved it for me <3

So I'm a bit put off by this solution because of this note in [the docs](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html):

> This tsconfig.json file will only include ./node_modules/@types/node, ./node_modules/@types/lodash and ./node_modules/@types/express. Other packages under node_modules/@types/* will not be included.

I feel like it would be nice to not have to keep this list updated and just auto-include all the `node_modules/@types` definitions. Am I unnecessarily concerned?

**Comment by Kovensky** [comment] 2018-12-18 03:59
That would automatically make any `@types` package you install (directly or indirectly) that has global declarations make them available to your code.

I personally avoid it (even giving `types: []` on some packages) but if you want to keep the behavior, then you can remove the `types` array and just add a `/// <reference types="@emotion/core"/>` or `import {} from '@emotion/core'` anywhere in your project. TypeScript elides `import {} from` as being a type-only import (as in, you made no use of any concrete values from the import).

**Comment by kentcdodds** [comment] 2018-12-18 04:02
Interesting. Thank you for sharing that @Kovensky! You've been very helpful to me tonight (both here and on twitter! 🙏)

**Comment by tkh44** [comment] 2018-12-18 04:52
Thanks for helping out @Kovensky 👍

**Comment by ralexand56** [comment] 2018-12-19 22:46
> Yeah, and you can leave the `namespace JSX` alone.
> 
> This is how I did it for `styled-components`, where we made the `css` prop's declaration opt-in:
> 
> https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/styled-components/cssprop.d.ts#L4-L19

I don't understand. This doesn't work with styled components either. What do you mean by opt in?

**Comment by felixjung** [comment] 2018-12-30 11:54
If anyone is having trouble with getting this to work, nuking `node_modules` and my `yarn.lock` resolved all my issues with the `css` prop. Found this here: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/21242.

Not ideal, but it does the job.

**Comment by barry4dev** [comment] 2019-07-03 12:27
To add to @felixjung 's case, I was trying to figure out this issue in relation to a simple app created with https://github.com/zeit/next.js (awesome package btw!)

After much fumbling it seemed somehow to a separate install of @types/react under @types/next/node_modules.  Since @types/react was already under my <main>/node_modules, I didn't feel adding it was required.

So by doing
```
yarn add @types/react
```
it fixed the problem, seemingly so that @types/next could just point to the version already installed by @types/react in package.json (educated guess), so it didn't add any additional install

Couldn't reproduce after this, but hope this helps someone ;)

**Comment by ricsam** [comment] 2019-07-14 07:38
As of writing, for create react app adding the following to the project index.tsx was the only that worked for all scenarios: 
`import * as types from 'styled-components/cssprop'`

source:
https://github.com/jacobwgillespie/styled-icons/issues/644#issuecomment-469012113
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/31245#issuecomment-463640878

**Comment by kripod** [comment] 2019-10-20 23:00
The TypeScript workflow could be simplified by providing a `@types/emotion-core` package through DefinitelyTyped, containing [type augmentations](https://github.com/emotion-js/emotion/blob/c673e200afbb89b8689775d305b55961ae31dfca/packages/core/types/index.d.ts#L82-L99) without having to override `types` in `tsconfig.json`. `@emotion/core` could add `@types/emotion-core` as a dependency for fluid, zero-config developer experience.

**Comment by radihuq** [comment] 2020-02-14 17:53
I'm working with a monorepo built using `yerna` and @barrymay 's answer was the solution for me

**Comment by mavlikwowa** [comment] 2021-01-02 20:43
If you have the error with types "type" and "as" you should redefine this types before intert these in styled components

```
/* Button component */
const Button: React.FC<ButtonProps> = ({
  isLoading,
  children,
  // REDEFINE THIS TYPE
  type = 'button',
 // REDEFINE THIS TYPE
  as = undefined,
  ...props
}: ButtonProps, ...others) => {
  return (
    <StyledButton {...props} {...others}>
      {isLoading ? 'Loading...' : children}
    </StyledButton>
  );
};

export default Button;
```

**Comment by DominicTobias** [comment] 2021-01-15 12:56
For those poor travellers using Emotion 11 the answer is here: https://github.com/emotion-js/emotion/issues/1249#issuecomment-727590944

**Comment by Andarist** [comment] 2021-01-15 13:51
If you are already on TS 4.1 you should follow the first recommendation here: https://emotion.sh/docs/typescript#css-prop

It's all in the docs...

**Comment by DominicTobias** [comment] 2021-01-15 13:57
> If you are already on TS 4.1 you should follow the first recommendation here: https://emotion.sh/docs/typescript#css-prop
> 
> It's all in the docs...

Thanks I tried that and it didn't work, but now I realise it requires a VSCode restart to take effect there.

**Comment by saulpalv** [comment] 2021-03-25 04:39
just add the following line to react-app-env.d.ts as stated in https://emotion.sh/docs/emotion-11
`/// <reference types="@emotion/react/types/css-prop" /> `

and import with

```
/** @jsxImportSource @emotion/react */
import { css } from '@emotion/react'
```

in tsconfig.json make shure to have  `"jsx": "react-jsx"`

**Comment by neaumusic** [comment] 2022-04-06 19:26
I had a similar issue spreading the rest of my props from `HTMLAttributes<HTMLDivElement>`, and I realized the issue was actually that there's a `css` prop passed in by default, not sure if it's from the theme or a global, but casting that as `cssProps` or an unused `_cssProps` seems to have solved the issue. I'm not sure how to spread `cssProps` back into the custom `css` attribute of the div, but if you have a theme setup this may be easy to test.

```
export interface MyComponentProps extends React.HTMLAttributes<HTMLDivElement> {
    someProp: string;
};

export const MyComponent: React.FC<MyComponentProps> = ({
  css: cssProp,
  someProp,
}) => (
  <div
    css={css`
      background-color: "black",
      ...cssProp // not sure about this line
    `}
  />
);
```

**Comment by srmagura** [comment] 2022-04-06 19:45
@neaumusic `css` prop is passed down to the component as a `className`, so `MyComponent` will never have access to the `css` prop directly. I think this would work:

```tsx
export interface MyComponentProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'css'> {
    someProp: string;
};

export const MyComponent: React.FC<MyComponentProps> = ({
  someProp,
}) => (
  <div
    css={css`
      background-color: "black"
    `}
  />
);
```
