### ISSUE TITLE
&:focus not working

### ISSUE THREAD

**Issue by SeanDez** [emotion-js/emotion#1114] opened 2018-12-16 14:44 UTC
- `emotion` version:
- `react` version:

    "emotion": "^9.2.12",
    "react": "^16.6.3",

**Relevant code:**

```javascript
const cardElementStyle = css`
  border: .2px solid rgba(120,144,149,0.41);
  color: rgba(120,144,149,0.41);
  height: 35px;
  padding-top: 10px;
  padding-bottom: 10px;
  margin-bottom: 20px;
  &:focus {
    background-color: red !important; // doesn't work
    border: 1px solid rgb(26, 141, 181); // also doesn't work
  }
  &:hover {
    //background-color: red; // works
  }
`;
```

```
// inside render()
<CardElement
                className={cardElementStyle} />
```

**What you did:**
Assigned a background color of red to a Stripe.js CardElement.

**What happened:**

Nothing happened with the focus pseudoclass. Added !important; no effect either.

It worked as espected with the hover pseudoclass though. 

Focus and Hover were tested one at a time to avoid conflicts.

**Suggested solution:**
See what is wrong with :focus in particular.

**Comment by Andarist** [comment] 2018-12-16 19:18
Could u prepare a codesandbox with the issue reproduced?

**Comment by FezVrasta** [comment] 2019-11-03 14:21
I'm going ahead and closing the issue since OP didn't provide a repro after a year

**Closed by FezVrasta** 2019-11-03 14:21 UTC

**Comment by alex-drocks** [comment] 2022-04-11 18:06
Try focus-within:

```js
"&:focus-within": {
    borderColor: "red"
}
```

**Comment by rosanzheng** [comment] 2024-12-20 01:08
For anyone who may still be struggling with this one:
focus-visible was the issue for me. I solved it by writing "resetting" the outline property:

```
:focus {
    outline: none;
    border: 1px solid red;
}
```
