### ISSUE TITLE
Styles broken in CRA Production Build but work fine in development mode

### ISSUE THREAD

**Issue by n8sabes** [emotion-js/emotion#2221] opened 2021-01-21 00:20 UTC
My CRA-based PWA application with emotion styles works perfectly during development `yarn start`, however when built for production `yarn build` and served, the styles are missing when inspected in the browser. The HTML is correctly formed with references to style names (same as dev build), but the style object does not exist in the execution environment context.

I do not (yet) have a pared-down example to reproduce but will work toward that. I am posting this as inquiry to see if anybody else has come across this issue for potential pointers as to causes and/or resolution. I've read potential issues with importing .css files so tried removing all those, but get the same results. I do not see any errors emitted to the console/log.

- `@emotion/react` version: 11.1.4
- `@emotion/styled` version: 11.0.0
- `react` version: 17.0.1
- `react-scripts` version: 4.0.1
- `typescript` version: ^4.1.3

**Comment by n8sabes** [comment] 2021-01-22 20:08
While I've not yet determined the true root cause, I have isolated lazy loading of a functional component within a useMemo/useCallback to be the catalyst for style objects being, or becoming, undefined.

**Comment by Andarist** [comment] 2021-01-22 22:22
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by n8sabes** [comment] 2021-01-23 00:30
@Andarist, the scale+complexity of my project is still far too broad but narrow into an example repo.

As of now, it seems using ` css`` ` from @emotion/css within a hook of a lazy loaded component may be the culprit.

**Comment by n8sabes** [comment] 2021-01-23 08:29
It seems first use of ` css`` ` from `@emotion/css` in a lazy loaded component wipes out styles created by the parent context using `@emotion/react`. This happens in a CRA production build (`yarn build` and serve), but not in a dev build (`yarn start`).

The workaround is to instantiate both early in the lifecycle, at the root of the app, before any styles are ever generated.

```
import { css, keyframes } from "@emotion/css";
import { css as reactCss, keyframes as reactKeyframes } from "@emotion/react";

css``
reactCss``
keyframes``
reactKeyframes``
```

@Andarist, does this seem like expected behavior?

_Now that I have been able to isolate this issue, I can look at creating a simplified repo._

**Comment by Andarist** [comment] 2021-01-23 10:18
One idea - do you maybe have two versions of `@emotion/cache` installed? If you are mixing both `@emotion/react` and `@emotion/css` packages then it might be best to use `CacheProvider` for your app with a unique `key` configured for your cache. I suspect that the second instance hijacks existing styles here:
https://github.com/emotion-js/emotion/blob/400c6f72905a4676f852b09405421a7ca8d7a3a2/packages/cache/src/index.js#L80

**Comment by n8sabes** [comment] 2021-01-23 17:18
I do not see a specific inclusion of `@emotion/cache`, but using the following which may be:

```
"@emotion/css": "^11.1.3",
"@emotion/react": "^11.1.4",
"@emotion/serialize": "^1.0.0",
"@emotion/styled": "^11.0.0",
"stylis": "^4.0.6",
```

I made a feeble attempt to switch over to `@emotion/react` in that part of my project (non-react component support helper code), but the two libraries produce different results and naming convention, so will need to take a closer look at the documentation. I use the modules listed above based on our conversations in other issues and projects to achieve a live human-editable css + keyframe input/output.

` css`` ` from `@emotion/css` returns a name string for a valid style (e.g. `css-30z5br`).

 Whereas,

` css`` ` from `@emotion/react` returns an object. The object contains a name field that differs from the prior naming convention and does not seem to be a valid style (e.g. `30z5br`).

I do not have an understanding of cache yet, but will look into `CacheProvider` today — thank you.

**Comment by n8sabes** [comment] 2021-01-23 17:38
Wrapping the app in a `CacheProvider` worked! Thank you @Andarist.

Should I close this issue, or is there something to be done to improve the library (e.g. context overwriting, naming convention, etc.)?

**Comment by Andarist** [comment] 2021-01-23 22:33
I'm going to close this for now but I'm going to keep thinking about how this can be improved. This only happens if you have one of the `@emotion/react` or `@emotion/css` completely lazy-loaded after the other one. The problem is that they both share the very same default `key` (`css`) and the second one tries to rehydrate using styles already owned by the first one.

**Closed** 2021-01-23 22:33 UTC
Labels: bug, needs triage

**Comment by FarisMarouane** [comment] 2021-04-22 10:43
@n8sabes @Andarist In my company, we also had a similar bug where a lazy-loaded component that uses the react-select library (which uses emotion) overrode our CSS style.
Using a CacheProvider as you suggested @Andarist worked but we don't understand how/why.

**Comment by zhdanouskikh** [comment] 2022-02-10 13:45
Are there any updates on how to fix this issue?
For me it reproduced only in mobile Safari and I wrapped the app in CacheProvider.

I'm using emotion with mui 5 and tss-react.
