### ISSUE TITLE
Babel plugin doesn't work with v10 (known issue?)

### ISSUE THREAD

**Issue by jfrolich** [emotion-js/emotion#1008] opened 2018-11-12 06:19 UTC
When I add the v10 version of the babel plugin, all the styles are rendered incorrectly. Is this a known issue? In the codebase I don't have legacy v9 code anymore. Let me know if this is expected.

Without the babel plugin it works fine, but I kind of miss the extra things like naming and sourcemaps in development.

If necessary I can provide a repro case.

**Comment by mitchellhamilton** [comment] 2018-11-12 06:41
This isn't expected, a repro would be great.

**Comment by ChristopherBiscardi** [comment] 2018-11-12 07:59
I swapped some code over to v10 (including the babel plugin and all relevant libs to their v10 names) tonight and it's working as expected, so it's at least working for me.

**Comment by jfrolich** [comment] 2018-11-12 08:50
Okay good to know. Some styles work for me but a lot is not working. I'll figure out which pattern is the culprit.

**Comment by jfrolich** [comment] 2018-11-12 14:30
```es6
/** @jsx jsx */
import React from "react";
import ReactDOM from "react-dom";
import { jsx, css } from "@emotion/core";
import styled from "@emotion/styled";

const title = "My Minimal React Webpack Babel Setup";

const Boxy = ({ className }) => (
  <div
    css={[
      css`
        color: blue;
      `,
      className
    ]}
  >
    BLA
  </div>
);
const Box = styled(Boxy)`
  background-color: red;
`;

ReactDOM.render(<Box>{title}</Box>, document.getElementById("app"));

module.hot.accept();
```

**Comment by jfrolich** [comment] 2018-11-12 14:31
This works correctly without the plugin, but not with

**Comment by mitchellhamilton** [comment] 2018-11-12 22:21
It's more of a bug that that works without the babel plugin, I'm gonna change it so that doesn't work at all.

You should be doing something like this instead to get the behavior you're wanting.
```jsx
<div
  className={className}
  css={css`
    color: blue;
  `}
>
  BLA
</div>
```

**Comment by jfrolich** [comment] 2018-11-13 06:52
> It's more of a bug that that works at all, I'm gonna change it so that doesn't work at all.
> 
> You should be doing something like this instead to get the behavior you're wanting.
> 
> ```js-jsx
> <div
>   className={className}
>   css={css`
>     color: blue;
>   `}
> >
>   BLA
> </div>
> ```

Whoops really? That would really break my whole app! (and a lot of work to fix it).

If we have className and css as separate things and we cannot compose these, there is no control on precedence. Often in the real world you'd like to pass styles to a component but add custom styles before or after.

**Comment by jfrolich** [comment] 2018-11-13 06:55
Given that it works now, why not keep it and make it a feature?

**Comment by jfrolich** [comment] 2018-11-13 06:56
I know that with `ClassNames` there is a way to compose classnames, but that is really clunky for such a common use case.

**Comment by mitchellhamilton** [comment] 2018-11-13 07:12
> If we have className and css as separate things and we cannot compose these

They are composed. The class name takes precedence. It's been discussed in the past(#753) and we haven't seen a usecase for having the css prop take precedence over the class name.

**Comment by mitchellhamilton** [comment] 2018-11-13 07:12
> Given that it works now, why not keep it and make it a feature?

It disables lots of build time optimizations.

**Comment by jfrolich** [comment] 2018-11-13 07:52
@mitchellhamilton: Actually went through hundreds of instances in our app and 95% of the time the className as higher precedence makes sense! So I think this API makes sense. But not so great for people migrating.

**Comment by tkh44** [comment] 2018-11-14 05:36
fwiw I updated the css prop docs to document some of this better @jfrolich. Please feel free to leave feedback on that pr if you have any suggestions to improve it.

**Comment by asvetliakov** [comment] 2018-11-16 12:02
This works:
```jsx
import styled from "@emotion/styled";
const A = styled("div")`
  color: green;
`;
```

This doesn't:
```jsx
import styled from "../some_styled_reexport";
const A = styled("div")`
  color: green;
`;
```

**Comment by Andarist** [comment] 2019-10-27 14:16
Seems like the issue has been explained - emotion works as intended. Also, extra documentation around this has been added. Therefore it seems it's appropriate to close this.

**Closed by Andarist** 2019-10-27 14:16 UTC
