### ISSUE TITLE
Styling styled components acts unexpectedly

### ISSUE THREAD

**Issue by rsxdalv** [emotion-js/emotion#2312] opened 2021-03-28 14:13 UTC
**Current behavior:**

Styling information is lost for consecutive styles. I suspect but cannot confirm that it's a regression, because it appears that the code no longer works. Nevertheless, currently it doesn't throw any errors besides not functioning as expected.

**To reproduce:**

1.

```js
import { css } from "@emotion/css";
import styled from "@emotion/styled";

export const ClearButton = styled('button')`
    margin: 0;
    padding: 0;
    border: 0;
    background: transparent;
    font: inherit; 
    /* // Inherit font settings (doesn’t work in IE7-) */
    /* // line-height: normal; // Override line-height to avoid spacing issues */
    line-height: 0; /* // Due to Flexbox issues */
    /* Remove mystery padding in Gecko browsers.
     * See https://bugzilla.mozilla.org/show_bug.cgi?id=140562
     */
    ::-moz-focus-inner {
        padding: 0;
        border: 0;
    }
    cursor: pointer;
    :focus {
        outline: none;
    }
`;

const newstyle = css`
    :hover {
        opacity: 0.7;
    }
    :focus {
        opacity: 0.7;
        outline: none;
    }
`

// Result has no hover activity, however, no error is thrown either.
export const ClearButtonHover_Broken = styled(ClearButton)(newstyle)
export const ClearButtonHover_AlsoBroken = styled(ClearButton)`${newstyle}`
export const ClearButtonHover_Works = styled(ClearButton)`
    :hover {
        opacity: 0.7;
    }
    :focus {
        opacity: 0.7;
        outline: none;
    }
`;
`

export const ClearButtonHover = styled(ClearButton)(newstyle)
```

**Expected behavior:**

Consistent styling or errors if this isn't valid usage of the new API

**Environment information:**

- `react` version: 17.0.1
- `@emotion/react` version: 11.1.5

**Comment by Andarist** [comment] 2021-03-28 14:36
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by mindsers** [comment] 2021-04-02 14:03
Hi! It seems that I have the same issue on a codebase that haven't changed during the last 5 months.

I have those styled components:
<img width="442" alt="Capture d’écran 2021-04-02 à 15 56 33" src="https://user-images.githubusercontent.com/3090112/113422065-68745d00-93cc-11eb-990a-f0e1aa4f4275.png">

They are used this way:
<img width="207" alt="Capture d’écran 2021-04-02 à 15 57 03" src="https://user-images.githubusercontent.com/3090112/113422174-8a6ddf80-93cc-11eb-814a-4942af02e50b.png">

But when I look at the DOM, the 4 elements share the same class selector (which is the class selector of the `FirstTextField`):
<img width="236" alt="Capture d’écran 2021-04-02 à 15 57 27" src="https://user-images.githubusercontent.com/3090112/113422309-bbe6ab00-93cc-11eb-9bf7-bfd4955024b7.png">

Hope it helps!

**Comment by rsxdalv** [comment] 2021-04-02 17:05
Interesting, the pattern of extending styled components is the same as the one I have issues with.

**Comment by Andarist** [comment] 2021-04-03 07:52
@mindsers please share a **runnable** repro case - you can't expect me to re-type this from images.

**Comment by rsxdalv** [comment] 2021-04-14 17:23
Not yet a runnable case but I tested it on the emotion.sh website (paste all in an editable cell https://emotion.sh/docs/styled ), and there the following code works in all 3 cases, despite not working locally. Hence I can definitely say that it's inconsistent. I'll see if I can make an online repro soon.

```tsx
import { css } from "@emotion/css";
import styled from "@emotion/styled";

const ClearButton = styled('button')`
    margin: 0;
    padding: 0;
    border: 0;
    background: transparent;
    font: inherit; 
    /* // Inherit font settings (doesn’t work in IE7-) */
    /* // line-height: normal; // Override line-height to avoid spacing issues */
    line-height: 0; /* // Due to Flexbox issues */
    /* Remove mystery padding in Gecko browsers.
     * See https://bugzilla.mozilla.org/show_bug.cgi?id=140562
     */
    ::-moz-focus-inner {
        padding: 0;
        border: 0;
    }
    cursor: pointer;
    :focus {
        outline: none;
    }
`;

const newstyle = css`
    :hover {
        opacity: 0.7;
    }
    :focus {
        opacity: 0.7;
        outline: none;
    }
`

// Result has no hover activity, however, no error is thrown either.
const ClearButtonHover_Broken = styled(ClearButton)(newstyle)
const ClearButtonHover_AlsoBroken = styled(ClearButton)`${newstyle}`
const ClearButtonHover_Works = styled(ClearButton)`
    :hover {
        opacity: 0.7;
    }
    :focus {
        opacity: 0.7;
        outline: none;
    }
`;


const ClearButtonHover = styled(ClearButton)(newstyle)

render(
<div>
    <ClearButtonHover_Broken>ClearButtonHover_Broken</ClearButtonHover_Broken>
    <ClearButtonHover_AlsoBroken>ClearButtonHover_AlsoBroken</ClearButtonHover_AlsoBroken>
    <ClearButtonHover_Works>ClearButtonHover_Works</ClearButtonHover_Works>
</div>
)
```

**Comment by Andarist** [comment] 2021-04-14 18:33
Ill wait for a runnable repro then 😉 i cant do much about this right now without it

**Comment by artola** [comment] 2021-04-16 23:03
@Andarist I am experiencing the same problem, it seems related to mix `css` from `@emotion/css` and `styled`.
Here a [repo in Codesanbox](https://codesandbox.io/s/emotion-forked-m7kkx?file=/index.js)

By the way, the classes are created and applied to the element but in the wrong order.

Note: if I import `css` from `@emotion/react` then it works (but for TS the typings are wrong). I guess that libraries are connected to different instances of emotion.

The documentation is not clear about this point (see: https://emotion.sh/docs/typescript#emotionreact)

It works for the example, but it does not clarify anything about "specificity" (orden of creation) of the generated classes.

![image](https://user-images.githubusercontent.com/11500763/115091672-72dc3e00-9f18-11eb-9465-0ec8e1eb9a5c.png)

The button should render the text in blue, but it comes out wrongly in black.

```jsx
import React from "react";
import ReactDOM from "react-dom";

import { cx, css } from "@emotion/css";
import styled from "@emotion/styled";

const Button = ({ className, ...rest }) => (
  <button
    className={cx(
      css`
        color: black;
      `,
      className
    )}
    {...rest}
  />
);

const BlueButton = styled(Button)`
  color: blue;
`;

function App() {
  return <BlueButton>This text should be blue!</BlueButton>;
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

**Comment by Andarist** [comment] 2021-04-17 22:13
> By the way, the classes are created and applied to the element but in the wrong order.

The order of class names doesn't matter for the browser. However, if you ever get more than a single Emotion-generated class name on a component it most likely means that you have combined them wrongly for some reason.

> I guess that libraries are connected to different instances of emotion.

Yes, each has its own cache - you can make `@emotion/react` to use the one from `@emotion/css`:
https://codesandbox.io/s/emotion-forked-sd2yc?file=/index.js

> It works for the example, but it does not clarify anything about "specificity" (orden of creation) of the generated classes.

As mentioned before - in what order class names are applied on an element doesn't matter for the browser.

**Comment by artola** [comment] 2021-04-17 22:21
@Andarist I agree, the solution using the `CacheProvider` makes sense.

**Comment by rsxdalv** [comment] 2021-11-12 19:29
Sorry for taking so long; I have verified that using a cache provider makes @emotion/styled and @emotion/css work together properly.
I do see a testable condition though - if there are two separate emotion instances/caches going on, it might be a cause for alarm, especially if they meet on the same element. The simplest test would be - having two emotion class names on a single element throws a warning?

**Comment by Andarist** [comment] 2021-11-13 06:17
> The simplest test would be - having two emotion class names on a single element throws a warning?

Yes, usually I would say that this is a problem **unless** something is styled internally with Emotion, the consumer doesn't know that and they are using Emotion for styling too.

**Comment by awgeorge** [comment] 2022-01-27 11:05
Is Emotion meant to support inherence in the way `styled-components` does? I assumed it should, but this suggests otherwise: https://codesandbox.io/s/trusting-boyd-uvc6x?file=/src/App.js

```js
import React from "react";
import styled from "@emotion/styled";

const Green = ({ children }) => {
  return <StyledGreen>{children}</StyledGreen>;
};

const StyledGreen = styled("section")({
  backgroundColor: "#0f0"
});

const Red = ({ children }) => {
  return <StyledRed>{children}</StyledRed>;
};

const StyledRed = styled(Green)({
  backgroundColor: "#f00"
});

export default function App() {
  return <Red>Should be red</Red>;
}
```

Emotion-react v11.7.1
Emotion-styled v11.6.0

**Comment by awgeorge** [comment] 2022-01-27 11:45
Ha - needed to add props. https://codesandbox.io/s/unruffled-cache-j5o1i?file=/src/App.js

```js
import React from "react";
import styled from "@emotion/styled";

const Green = ({ children, ...props }) => {
  return <StyledGreen {...props}>{children}</StyledGreen>;
};

const StyledGreen = styled("section")({
  backgroundColor: "#0f0"
});

const Red = ({ children, ...props }) => {
  return <StyledRed {...props}>{children}</StyledRed>;
};

const StyledRed = styled(Green)({
  backgroundColor: "#f00"
});

export default function App() {
  return <Red>Should be red</Red>;
}
```

Works as intended now.

**Comment by rsxdalv** [comment] 2022-01-27 12:48
> Ha - needed to add props. https://codesandbox.io/s/unruffled-cache-j5o1i?file=/src/App.js
> 
> ```js
> import React from "react";
> import styled from "@emotion/styled";
> 
> const Green = ({ children, ...props }) => {
>   return <StyledGreen {...props}>{children}</StyledGreen>;
> };
> 
> const StyledGreen = styled("section")({
>   backgroundColor: "#0f0"
> });
> 
> const Red = ({ children, ...props }) => {
>   return <StyledRed {...props}>{children}</StyledRed>;
> };
> 
> const StyledRed = styled(Green)({
>   backgroundColor: "#f00"
> });
> 
> export default function App() {
>   return <Red>Should be red</Red>;
> }
> ```
> 
> Works as intended now.

Not sure if there's any need for Green and Red rather than using the styled component directly.

**Comment by Andarist** [comment] 2022-01-27 20:21
I think there is nothing actionable here for our team so I'm going to close this issue - if you feel like this has no been addressed in full, let us know.

**Closed by Andarist** 2022-01-27 20:21 UTC
Labels: bug, needs triage

**Comment by rsxdalv** [comment] 2022-01-27 20:24
Fair enough, since there's a solution inside this thread that should suffice for now.
I also got a lot busier since making this issue.
