### ISSUE TITLE
React 17 + new JSX transform + JSX pragma/pragmaFrag

### ISSUE THREAD

**Issue by Metroninja** [emotion-js/emotion#2041] opened 2020-10-11 12:36 UTC
**Current behavior:**

I'm currently using a barebones nextJS deployment with React `17.0.0-rc.3` and have added emotion to the project.  I wanted to test out the [new JSX transform](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#how-to-upgrade-to-the-new-jsx-transform) but I'm running into issues, whenever I set
```
/** @jsx jsx */
import { jsx, css } from '@emotion/core';
```
in a component, I run into compilation issues in said file.
`SyntaxError: pragma and pragmaFrag cannot be set when runtime is automatic.`

my `.babelrc` file but is set below, and the issue is obviously with the value of `runtime` being set to automatic.  that said, that's how babel 8 will be set moving forward, and also is what allows the removal of requiring `React` in every file.  
```
    {
      "presets": [
        "next/babel",
        ["@babel/preset-react", {
          "runtime": "automatic"
        }]
      ],
      "plugins": ["emotion"]
    }
```
I'm not sure if here, react, or the babel issues repo was the best to post in but settled here given it's an issue with emotion's setting of the pragma.  I suspect a lot of this issue will be popping up soon once react 17 ships, so I thought i'd raise an issue so people aren't lost on day 1 after ripping out all of the 'import React from "react"` across their app and realizing they just made a huge mistake.

**Environment information:**

- `react` version: 17.0.0-rc.3
- `emotion` version: 10.0.35

**Comment by Andarist** [comment] 2020-10-11 12:51
U have configured globally the automatic runtime and it cannot be mixed with `@jsx` pragma. When React 17 gets published we are going to prepare a special entries compatible with it and u will be able to configure automatic runtime with Emotion or override per file with `@jsxImportSource`

**Comment by n8sabes** [comment] 2020-10-14 07:46
I modified my emotion style components to import the `css` prop manually. A bit of a pain, but got the project working again.

```javascript
const MyComponent = styled.div`
    ${(props: any) => props.css}
`;
```

I had to do the following when inheriting from another component:
```javascript
const MyComponent = styled((props: any) => <MyBaseComponent {...props} />)`
    ${(props: any) => props.css}
`;
```

@Andarist  What is the the recommenced workaround in the interim? I did not have much luck with toolchain / build mods, and certainly don't want to eject the `create-react-app` baseline.

**Comment by Andarist** [comment] 2020-10-14 08:59
@n8sabes just to confirm - you are using a prerelease of CRA 4 and React 17, right? I'm afraid that I don't have a good recommendation for this situation yet. You could create a module like this: https://github.com/emotion-js/emotion/pull/1970#issuecomment-707173919 and use `@jsxImportSource` pragma to point to it, but it ain't a super pleasant experience. We may be forced to recommend that new pragma in combination with CRA once we implement new factories for React 17. It's a shame as it's significantly longer than the current one:
```js
/** @jsx jsx */
```
vs
```js
/** @jsxImportSource @emotion/react */
```

**Comment by n8sabes** [comment] 2020-10-14 09:41
Thanks @Andarist.

```
"react": "17.0.0-rc.2"
"react-scripts": "^4.0.0-next.98"
```

I checked out `@jsxImportSource` #1970. For now, I have my project working with the manual `css` prop injection so I can wait for the preferred solution. I mainly wanted to share a workaround with others, and also ask if you had anything better. So, it seems we have two workarounds, neither of which are super clean but work.

**Comment by geart891** [comment] 2020-10-18 04:23
facebook/react#20045
I am not sure if this totally relates to the emotion babel css presets prop. However I feel it appropriate to report here.

**Comment by sfranc0** [comment] 2020-10-24 09:06
Hi guys, I am new on react. I have the same issue when i adding  **@jsx jsx** . How can i solve this.

`./src/components/UserIcon.tsx
SyntaxError: C:\Net Core Projects\QandA\frontend\src\components\UserIcon.tsx: pragma and pragmaFrag cannot be set when runtime is automatic.
> 1 | import React from 'react';
    | ^
  2 | /** @jsx jsx */
  3 | import { css, jsx } from '@emotion/core';
  4 | import userlogo from '../user.svg';`

**Comment by Andarist** [comment] 2020-10-24 09:46
Im working on fixing this - from both ends. We have a working PR with the support for new automatic runtimes and im working on a Babel PR to allow old pragmas to overwrite the configured runtime.

**Comment by bdpetersen77** [comment] 2020-10-28 04:37
Hey @n8sabes thank you for finding that work around! I'm somewhat new to React and I've heard good stuff about Emotion so I'd love to stick with it. Could you help me by showing how your workaround might work in some basic code, found below? I'm a little confused on how your proposed workaround would fit in. This would be from my main App.tsx file (yes, typescript). 

```
import React from 'react';
import { Header } from './Header';
import { HomePage } from './Homepage';
/** @jsx jsx */
import { css, jsx } from '@emotion/core';
import { fontFamily, fontSize, gray2 } from './Styles';


const App: React.FC = () => {
  return (
    <div
      css={css`
        font-family: ${fontFamily};
        font-size: ${fontSize};
        color: ${gray2};
        align-content: center;
      `}
    >
      <Header />
      <HomePage />
    </div>
  );
};

export default App;
```

**Comment by karlhorky** [comment] 2020-10-28 08:54
@Metroninja I guess this issue title can be edited to be "React 17" instead of "React 17 RC", now that v17 is out...

**Comment by karlhorky** [comment] 2020-10-28 08:54
@Andarist do you have links for those PRs for those interested in following along?

**Comment by Andarist** [comment] 2020-10-28 22:29
The one in Emotion is here: https://github.com/emotion-js/emotion/pull/1970
The discussion in Babel is here: https://github.com/babel/babel/issues/12208

**Comment by karlhorky** [comment] 2020-10-29 17:10
Nice! For anyone who can use the Babel CSS preset instead of pragmas, this option seems to work:

1. Install `@emotion/babel-preset-css-prop`
2. Add a `babel.config.js` file with at least `module.exports = { presets: ['@emotion/babel-preset-css-prop'] };`
3. Remove all of the `/** @jsx jsx */` pragma comments
4. Remove any `/** @jsxFrag React.Fragment */` comments

At least it does with Next.js 10...

More details here: 

https://github.com/vercel/next.js/issues/18461#issuecomment-718788358

**Comment by arganaphangquestian** [comment] 2020-10-30 08:16
> Nice! For anyone who can use the Babel CSS preset instead of pragmas, this option seems to work:
> 
> 1. Install `@emotion/babel-preset-css-prop`
> 2. Add a `babel.config.js` file with at least `module.exports = { presets: ['@emotion/babel-preset-css-prop'] };`
> 3. Remove all of the `/** @jsx jsx */` pragma comments (or similar)
> 4. Remove any `/** @jsxFrag React.Fragment */` comments (or similar)
> 
> At least it works with Next.js 10 + React 17...
> 
> More details here:
> 
> [vercel/next.js#18461 (comment)](https://github.com/vercel/next.js/issues/18461#issuecomment-718788358)

What about Typescript sir?

**Comment by karlhorky** [comment] 2020-10-30 11:54
@arganaphangquestian This is working with TypeScript as well for me (note the files with `.tsx` extensions): https://github.com/upleveled/next-js-example-sep-2020/tree/main/pages

Are you or @PabloSzx having issues?

**Comment by andriyandriyan** [comment] 2020-10-30 15:10
> Nice! For anyone who can use the Babel CSS preset instead of pragmas, this option seems to work:
> 
> 1. Install `@emotion/babel-preset-css-prop`
> 2. Add a `babel.config.js` file with at least `module.exports = { presets: ['@emotion/babel-preset-css-prop'] };`
> 3. Remove all of the `/** @jsx jsx */` pragma comments (or similar)
> 4. Remove any `/** @jsxFrag React.Fragment */` comments (or similar)
> 
> At least it works with Next.js 10 + React 17...
> 
> More details here:
> 
> [vercel/next.js#18461 (comment)](https://github.com/vercel/next.js/issues/18461#issuecomment-718788358)

I've tried with CRA 4 + Typescript but it doesn't work

**Comment by karlhorky** [comment] 2020-10-30 15:17
Yes, it will not work with `create-react-app`, because of the limitation of not being able to change the Babel config. Read more here: https://emotion.sh/docs/css-prop#jsx-pragma

It does not have to do with TypeScript.

For these environments, a fix is required for the pragma (which is being worked on in the two pull requests above, apparently).

**Comment by fobbyal** [comment] 2020-10-30 22:00
I've gotten the following to work. This tells babel to transpile the file using the old way

```javascript 
/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx } from '@emotion/core'
```

**Comment by Andarist** [comment] 2020-10-30 22:17
Yes, this works - but I feel that this is far from ideal and I hope that we can still change the logic for this in Babel, but we'll see.

The better news is that with #1970 you should be able to just use this in this CRA4:
```
/** @jsxImportSource @emotion/core */
```

**Comment by karlhorky** [comment] 2020-10-31 16:37
That sounds great @Andarist :) Cool that #1970 is merged now!

I guess the plan will be to publish `10.x` versions of `@emotion/core` and `@emotion/babel-preset-css-prop` with these changes?

**Comment by Andarist** [comment] 2020-10-31 16:49
Yes, we only need to prepare a docs update that is being worked on here: https://github.com/emotion-js/emotion/pull/2063

**Comment by Andarist** [comment] 2020-11-01 09:27
I'm going to release `@emotion/core@10.1.0` with the support for the new runtimes in a moment so I'm going to close this issue now. If you encounter any problems with this please open new issues.

**Closed by Andarist** 2020-11-01 09:27 UTC
Labels: feature request

**Comment by karlhorky** [comment] 2020-11-01 11:28
Thanks @Andarist !

**Comment by karlhorky** [comment] 2020-11-01 14:34
Seems like the new versions error out with `_jsxs is not defined` when running `next build`. Filed a new bug:

https://github.com/emotion-js/emotion/issues/2064

**Comment by przytrzask** [comment] 2020-11-03 08:20
Hey, Thanks for solving this
Now it `/** @jsxImportSource @emotion/core */` basically works for me in emotion `10.1.1`
However I've got following ts errror on CRA4.0 with typescript
```'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.```
Does anybody have any clue how to solve this?

**Comment by Andarist** [comment] 2020-11-03 11:21
Please take a look at the comments in [this CRA issue](https://github.com/facebook/create-react-app/issues/9847), starting from [this comment](https://github.com/facebook/create-react-app/issues/9847#issuecomment-720099614).

Migration everything at once is a little bit problematic, given different release schedules of various tools etc 😢

**Comment by Robbie-Cook** [comment] 2021-01-14 20:59
Can we please add a note to the docs to let people know that for now, React 17 requires `jsxImportSource`? Can't find anything in the docs

**Comment by akshayr20** [comment] 2021-08-12 03:48
> Hey, Thanks for solving this
> Now it `/** @jsxImportSource @emotion/core */` basically works for me in emotion `10.1.1`
> However I've got following ts errror on CRA4.0 with typescript
> `'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.`
> Does anybody have any clue how to solve this?

import React from 'react';
was no longer required, but with the typescript setting you are using I guess you still have to add above line in your code, else ts starts complaining

**Comment by tianhuil** [comment] 2022-04-05 04:36
It looks like emotion is working as an experimental feature.  You have to `next.config.js` to

```js
const nextConfig = {
  reactStrictMode: true,
  experimental: {
    emotion: true,
  },
}

module.exports = nextConfig
```

I can confirm this works with `next@12.1.4`.  See this [merged PR](https://github.com/vercel/next.js/pull/34687/files#diff-21b741d57995c3ab8b9211b17e2617c26829addf58be9280fdf8112817aab993)
