### ISSUE TITLE
Typescript props with generics and the styled function

### ISSUE THREAD

**Issue by xiavn** [emotion-js/emotion#1290] opened 2019-03-28 16:46 UTC
- `emotion` version: @emotion/styled - 10.0.10
- `react` version: 16.8.3

**Relevant code:**

```javascript
interface A {
  a?: string;
}

interface B<P> {
  b?: P;
}

interface Props extends A, B<string> {}

const UnstyledComponent: ComponentType<Props> = props => (
  <div {...props}>Test</div>
);

const StyledComponent = styled(UnstyledComponent)({
  color: "red"
});
```

**What you did:**

Using @emotion/styled and typescript, I created a react component with some props defined by an interface that extended two other interfaces, all of the defined props are optional. One of the interfaces allows for a generic parameter. I then tried to style the component using the styled function.

**What happened:**

When trying to use the styled component, a typescript error is produced due to the fact the optional prop that was part of the generic interface is no longer optional.

Here is the error message (property b is the property on the interface with a generic, a is on a standard interface): 
Type '{}' is not assignable to type '(IntrinsicAttributes & Props & ClassAttributes<Component<Props, any, any>> & Pick<Pick<(Props & ClassAttributes<Component<Props, any, any>>) | (Props & Attributes), "a" | "b">, "a" | "b"> & { ...; } & { ...; }) | (IntrinsicAttributes & ... 4 more ... & { ...; })'.
  Type '{}' is not assignable to type 'IntrinsicAttributes & Props & Attributes & Pick<Pick<(Props & ClassAttributes<Component<Props, any, any>>) | (Props & Attributes), "a" | "b">, "a" | "b"> & { ...; } & { ...; }'.
    Property 'b' is missing in type '{}' but required in type 'Pick<Pick<(Props & ClassAttributes<Component<Props, any, any>>) | (Props & Attributes), "a" | "b">, "a" | "b">'.

**Reproduction:**

[https://codesandbox.io/s/8z0zkrlqo0](https://codesandbox.io/s/8z0zkrlqo0)

**Problem description:**

I'm not sure if I'm just doing something wrong, or if there is some issue with the emotion typings that is converting this optional parameter to required.

**Comment by aaronjensen** [comment] 2019-05-29 20:49
A possible workaround, which has some limitations (you lose any emotion specific props, though there's probably a way to get those in if it's important):

```ts
const StyledComponent: ComponentType<Props> = styled(UnstyledComponent)({
  color: 'red',
})
```

**Comment by anilanar** [comment] 2019-10-27 11:29
Cannot reproduce, the sandbox seems to work now with TS 3.6.2.

**Comment by Andarist** [comment] 2019-10-27 11:53
@anilanar thank you for checking! Going to close this as it seems that the issue is gone. There is also an ongoing effort to simplify current typings in https://github.com/emotion-js/emotion/pull/1501 and we hope that it will fix most of the issues with TS types.

**Closed by Andarist** 2019-10-27 11:53 UTC
