### ISSUE TITLE
TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by amykapernick** [emotion-js/emotion#1354] opened 2019-05-20 03:55 UTC
- `emotion` version: `10.0.9` (was an issue on 9, upgraded to attempt to troubleshoot
- `react` version: `16.8.6
- `gatsby` version: `2.1.15`

**Relevant code:**
`/src/components/header/style.js`
```javascript

export const Nav = styled('nav')`
	display: flex;
	flex-direction: row;
	justify-content: space-between;
	height: auto;
	overflow-x: scroll;
	-webkit-overflow-scrolling: touch;
	max-width: 100vw;
	z-index: 20;

	&:after {
		animation: ${scrolling} 2s linear infinite;
		color: ${props => props.theme.colours.primary.main};
		/* color: ${props => props.theme.colours.primary.main}; */
		content: '\00BB';
		font-size: 2em;
		position: absolute;
		right: 10px;
		bottom: 13%;
	}

	@media (min-width: ${props => props.theme.values.screens.small}) {
		display: flex;
		flex-direction: row;
		margin-left: auto;
		padding: 0 10px;
		overflow-x: visible;

		&:after {
			content: normal;
		}
	}

	@media (min-width: ${props => props.theme.values.screens.medium}) {
		margin-left: 0;
		margin-top: 3vw;
	}

	@media (min-width: ${props => props.theme.values.screens.large}) {
		margin-top: 1vh;
		padding: 40px 20px 10px;
	}

	/* @media (min-width: ${props => props.theme.values.screens.large}) {
		margin-top: 1vh;
		padding: 40px 20px 10px;
	} */
`

```

**What you did:**
I did nothing, tried to do some work on an existing project and immediately got this error when running `npm start`. Then tried upgrading to `v10` to see if that fixed the issue but still got this error.

Troubleshooting with this file, I commented everything out until it built, then uncommented until I ran into an issue, found the issue was 2 lines.
```color: ${props => props.theme.colours.primary.main};``` and ``` @media (min-width: ${props => props.theme.values.screens.large}) {```

When I tried re-writing the lines it works, but styles after the commented lines don't come through. (eg. on line 107, the colour line I re-wrote is fine, but the rest of it doesn't come through). If I try moving or re-writing those lines it still throws an error.

**What happened:**

```
./src/components/header/style.js
Module build failed (from ./node_modules/gatsby/dist/utils/babel-loader.js):
TypeError: Cannot read property 'value' of undefined
    at C:\Users\amyka\web\aimhigher\node_modules\babel-plugin-emotion\dist\babel-plugin-emotion.cjs.dev.js:154:17
    at Array.filter (<anonymous>)
    at replacePlaceholdersWithExpressions (C:\Users\amyka\web\aimhigher\node_modules\babel-plugin-emotion\dist\babel-plugin-emotion.cjs.dev.js:153:48)
    at getExpressionsFromTemplateLiteral (C:\Users\amyka\web\aimhigher\node_modules\babel-plugin-emotion\dist\babel-plugin-emotion.cjs.dev.js:92:10)
    at transformExpressionWithStyles (C:\Users\amyka\web\aimhigher\node_modules\babel-plugin-emotion\dist\babel-plugin-emotion.cjs.dev.js:430:23)
    at C:\Users\amyka\web\aimhigher\node_modules\babel-plugin-emotion\dist\babel-plugin-emotion.cjs.dev.js:662:39
    at Array.forEach (<anonymous>)
    at C:\Users\amyka\web\aimhigher\node_modules\babel-plugin-emotion\dist\babel-plugin-emotion.cjs.dev.js:638:26
    at Object.macroWrapper [as @emotion/styled] (C:\Users\amyka\web\aimhigher\node_modules\babel-plugin-macros\dist\index.js:44:12)
    at PluginPass.ImportDeclaration (C:\Users\amyka\web\aimhigher\node_modules\babel-plugin-emotion\dist\babel-plugin-emotion.cjs.dev.js:886:45)
    at newFn (C:\Users\amyka\web\aimhigher\node_modules\@babel\traverse\lib\visitors.js:193:21)
    at NodePath._call (C:\Users\amyka\web\aimhigher\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (C:\Users\amyka\web\aimhigher\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at NodePath.visit (C:\Users\amyka\web\aimhigher\node_modules\@babel\traverse\lib\path\context.js:88:12)
    at TraversalContext.visitQueue (C:\Users\amyka\web\aimhigher\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitMultiple (C:\Users\amyka\web\aimhigher\node_modules\@babel\traverse\lib\context.js:85:17)
```

**Reproduction:**
Code Sandbox - https://codesandbox.io/s/github/AimHigher-Web-Design/aimhigher/tree/emotion-issue
Github Repo - https://github.com/AimHigher-Web-Design/aimhigher/tree/emotion-issue
Branch Deploy - https://5ce2200dd603e5000700b005--aimhigher.netlify.com/

**Problem description:**
It has issues with particular styles, with no reason as to why. And yes the variables do exist, that is not the issue.

**Suggested solution:**
🤷‍♀️ I want the code to work like it used to

**Comment by danielhusar** [comment] 2019-08-02 20:53
I can reproduce too.

Using backslash + hex values would trigger it, like: `content: '\00d7';`

**Comment by Andarist** [comment] 2019-08-02 21:45
I have just tried to write a failing test for this to fix it and I'm afraid I can't reproduce the issue. Could you post a repro case (the original is not working anymore 😢)?

**Comment by danielhusar** [comment] 2019-08-02 22:26
Hey!

Here's the repro case:
https://github.com/danielhusar/emotion-error-demo/blob/master/src/index.js
Live demo: https://emotion-error-demo.netlify.com/

I think the key is that you need to use emotion babel plugin, without it it works fine.
It fails in this demo silently (which is even worse) and all styles are ignored.
But sometimes I manage to see same error message like Amy.

**Comment by Andarist** [comment] 2019-08-03 10:22
This is actually weird that it works without the babel plugin, because this is not a valid escape sequence and this shouldn't work as per [ES2018 revision of illegal escape sequences](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#ES2018_revision_of_illegal_escape_sequences)

You can check out how it behaves in the console by pasting in such code:
```js
function test(arg) {
 console.log({ arg: arg.slice(), raw: arg.raw })
}
test`\00d7`
```

Babel is transpiling this [correctly](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=C4UwzsAGDkA6AM8AmB2akBQACLQ&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=7.5.5&externalPlugins=) (providing undefined in strings array for such illegal escape sequence), but cannot reproduce the same on [codesandbox](https://codesandbox.io/s/nostalgic-sun-312r9) (yet) - it doesn't replace that illegal sequence with undefined.

I think this is a tooling problem - i.e. [TS compiler](https://www.typescriptlang.org/play/?target=1#code/MYewdgzgLgBFCm0YF4YAoCGAnA5gLhgzAE8BKFAPhlEhABt4A6OkHTXUgKAWgAMAdAAyCAJgHZeQA) doesn't obey correct rules either.

We could introduce dev-only warnings for this though. Keep also in mind that both those versions (on provided codesandbox which demonstrates how both works, even though the second one shouldn't) still yield different results as to what gets inserted as content, but it doesn't have a visual difference.

I'm going to investigate this further to see why this works when it shouldn't (might be that codesandbox has older version of babel setup there) but those are my findings so far.

**Comment by Andarist** [comment] 2019-08-03 10:47
I've downloaded that codesandbox and after doing a fresh install the second component was not rendered with blue color right from the start. 

This has changed in babel between 7.4.2 and 7.4.3 ([commits](https://github.com/babel/babel/compare/7dea0f23de51af336a2fab0286a73af30cddf3be...508fde4009f31883f318b9e6546459ac1b086a91)), and the package which affects this is @babel/parser so the most likely commit that has changed this behavior is [this one](https://github.com/babel/babel/commit/c7587c016efa04d2497be475e00e41660203bd52).

Anyway - as those are correct semantics today the only thing we can do in emotion is to provide a helpful dev-only warning about this to help developers fix their problem.

**Comment by danielhusar** [comment] 2019-08-03 15:13
Yes helpful warning would be totally fine!
The main issue is, that this is a valid css. So it’s confusing for beginners.

**Comment by jwvance** [comment] 2019-09-24 18:59
I seem to be hitting this error, but for hidden formatting symbols like `\t` and `\n`. Does anybody know a workaround for this? Not sure if the solution would be to configure Babel differently or if Emotion should be stripping these characters. 
Any help would be appreciated! Thanks!

**Comment by Andarist** [comment] 2019-09-24 20:46
@jwvance could you prepare a repro case? That would help a lot.

**Comment by jwvance** [comment] 2019-09-25 00:01
@Andarist thank you for checking in. I copied the dist file that's giving me issues into a new file called Banner.esm.js. In the chrome console I can see the `illegal escape sequence` error message. 

Please take a look, and thanks again for your time :) 

https://codesandbox.io/s/funny-sea-ehszs

**Comment by Andarist** [comment] 2019-09-25 19:04
@jwvance great! seems like the code might need to get adjusted on our side (not 100% sure about it yet, but it's very likely). Could you add to that codesandbox.io the untranspiled version of that Banner component? It can be put there only as a point of reference, you don't have to use that untranspiled version anywhere.

**Comment by jwvance** [comment] 2019-09-25 19:31
@Andarist Thank you for taking a look. I posted the untranspiled version as `Banner.ts`. Note that Emotion is used to create a Styled Component, and to apply some CSS via the css prop.

**Comment by Andarist** [comment] 2019-09-26 07:51
Ok, seems this is caused by our babel plugin inserting source maps in a specific way. Gonna look into this in following days to see what can be done to prevent this mismatch. Thank you for the repro case!

**Comment by Andarist** [comment] 2019-10-01 21:56
@jwvance so the problem here seems to be that you pass TS ES5 output to Babel. I'll think about how we could improve this situation here - the quick fix on your side would be to just strip types with TS and hand out such output to Babel (which would in turn compile down to ES5)

**Comment by jwvance** [comment] 2019-10-01 23:43
@Andarist This fixed the issue. I just had to target es6 in the tsconfig. Thank you for investigating :)

**Comment by Andarist** [comment] 2019-10-28 20:41
As a result of this issue, I've fixed 2, rather edge-case, problems. The thread here is no longer focused on the OP's problem which I'm not sure it is still a problem (could have been fixed along the way). Closing this right now - but if you still experience any problems, similar or not, with emotion then please just raise a new issue so we could discuss it there.

**Closed by Andarist** 2019-10-28 20:41 UTC

**Comment by ShivangiKhandelwal27** [comment] 2020-10-20 18:10
@Andarist 
I am facing the same ILLEGAL ESCAPE SEQUENCE WARNING when i run the test case for the component containing my emotion components.
I get the error as

```
 "console.error ../../node_modules/@emotion/styled-base/dist/styled-base.cjs.dev.js:85
      You have illegal escape sequence in your template literal, most likely inside content's property value.
      Because you write your CSS inside a JavaScript string you actually have to do double escaping, so for example "content: '\00d7';" should become "content: '\\00d7';".
```

Changing my target to es6 from es5 in tsconfig removes this error in jest but I want to know why this happens ?
Why can't we have output as 'es5' from TScompiler which is then transferred to babel. (Babel shouldn't do any changes in this case )
